### ISSUE TITLE
pilup log aligns exactly 50% of reads in al samples

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#105]
I don't know why but in the assembly report of my samples. The aligned fraction of reads is always 50%, I tried both assemblers and increased the min id during the mapping. 

probably there is a bug in my script.

**Comment by brwnj** [comment]
A bug in the report script you think?

**Comment by SilasK** [comment]
Yes, I ment the report script.

**Comment by SilasK** [comment]
However when I check the log file from the pileup rule is states also about 49% mapped reads in all the filrs. Strange! @brwnj do you get the same?

**Comment by SilasK** [comment]
I have the same error again.

The log file of bbwrap shows me that for different samples reads are mapped usually 40-70% of the paired and 30-50% of the singeltons. However, the pileup log files say that in all samples 48-49% of reads were mapped. This makes no sense to me. 

I used v 37.78 and activated physical coverage. 
Can pileup not handle paired end + singletons in the same file?

**Comment by SilasK** [comment]
It seems it's due to the physicalcov option.

**Comment by SilasK** [comment]
There is still something strange. 

in the log file of bbwrap I have 


  | Paired end | Se
-- | -- | --
Total reads | 2 x 16895000 | 31401969
mapped | 2x 13408609 | 29907540
  |   |  
mapped | 79% | 95%


Which seem to be correct. e.g. the number of unmapped reads are found in  `outu`


in the logfile of pilup it is written: 

Reads: | 27370533
-- | --
Mapped reads: | 26817218
Mapped bases: | 4022582700
Ref scaffolds: | 851270
Ref bases: | 1216084673
  |  
Percent mapped: | 97.978
Percent proper pairs: | 97.978


I have no Idea, how pilup finds only 27370533 reads.

**Comment by SilasK** [comment]
The log file from pileup still has ~30% of contigs without any reads mapping even after filtering_by_coverage. 

I don't know if there is a problem with the filtering step or in the pileup.

**Comment by SilasK** [comment]
This is still a problem even it is now 100% in all the samples.
