### ISSUE TITLE
update of software

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#107]
Looking forward to integrate that into Atlas.
https://twitter.com/spadesassembler/status/996750701538799617?s=19

**Comment by brwnj** [comment]
Other potential updates include:

```
- python=3.6
- bbmap=37.99
- diamond=0.9.21
- pandas=0.23.0
- prokka=1.13
- samtools=1.8
- subread=1.6.1
```

**Comment by SilasK** [comment]
Ah also, I see 5 hours ago: https://github.com/MrOlm/drep/issues/37
Drep v2.2.2 apparently mislabelled things with > 20 genomes.
