### ISSUE TITLE
update prokka

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#124]
From @sofie8
prokka was updated some days ago (tseemann/prokka#320), and now it breaks my atlas runs:
Can't locate Bio/Root/Version.pm in @inc (you may need to install the Bio::Root::Version module) (@inc contains: /opt/conda/envs/prokka/lib/site_perl/5.26.2/x86_64-linux-thread-multi /opt/conda/envs/prokka/lib/site_perl/5.26.2 /opt/conda/envs/prokka/lib/5.26.2/x86_64-linux-thread-multi /opt/conda/envs/prokka/lib/5.26.2 .) at /opt/conda/envs/prokka/bin/prokka line 30.

When I reinstall prokka and run outside atlas, it works, but not within atlas. Can we edit this in the snakemake file, that it retrieves only the last, working prokka version?

**Comment by SilasK** [comment]
Currently, we are using: 
`prokka=1.12` I can't understand how 
I think this week we should finish implementing eggNOG #120  , so we probably won't continue with prokka.

**Comment by mdjlynch** [comment]
Hi. Is there a work-a-round for this issue or should we wait for the eggNOG implementation? I have been annotating the atlas results directly with prokka. Thanks.

**Comment by jmtsuji** [comment]
@mdjlynch I found a rough workaround included in the thread at https://github.com/tseemann/prokka/issues/320 . Unfortunately, I can only use this workaround outside of ATLAS. Current steps for me are:

1. Run ATLAS. Will error at the prokka step.
2. Via the `atlas [ options ] --dryrun` command, determine the prokka commands that ATLAS wants to run.
3. Run these outside of ATLAS manually using a working version of prokka via the workaround shown above (specifying the correct perl library for BioPerl).
4. Continue the ATLAS run.

Jackson

**Comment by SilasK** [comment]
If there is a prokka version which can be downloaded via biocanda, you
could only change it in the env file. Sometimes the order of the channels
matter. How comes that a old version of prokka stopt working. Otherwise,
the eggNOG should be ready soon.

**Comment by Sofie8** [comment]
Hello Michael,

Yes I solved it eventually that it works within atlas again, set cd to the
conda environment with prokka. Typ cpan and then install the module that
throws the error, it was Bio/Root/Version.pm this might on his turn ask for
another dependency to install, also execute that. Then you can exit cpan,
as a check typ prokka and see if it's fixed. Worked for me and atlas runs
complete now.
Sofie


Op vr 27 jul. 2018 17:04 schreef Michael D.J. Lynch <
notifications@github.com>:

**Comment by jmtsuji** [comment]
Hi @SilasK  @mdjlynch @Sofie8 ,

The conda install now works, as referenced in https://github.com/tseemann/prokka/issues/320

But note that the conda command must be appropriately chosen to allow prokka to install (include the `-c conda-forge` flag for `prokka=1.13` but omit for `prokka=1.12`). I haven't tested yet whether the ATLAS implementation of prokka works now.

**Comment by LakshmanTejaG** [comment]
run conda install perl=5.22.0 or export the path of perl 5.22 to .bashrc
