### ISSUE TITLE
Running atlas on OSX

### ISSUE THREAD

**Issue by mykophile** [metagenome-atlas/atlas#142]
It seems like pplacer is not installing properly with Atlas on OSX. 

BIO-C02WG1PRHTDF:Test_Metagenomics kabirpeay$ atlas assemble test.config.yaml
[2018-10-16 15:59 INFO] Executing: snakemake --snakefile /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/Snakefile --directory /Users/kabirpeay/Desktop/metagenomics/Test_Metagenomics --printshellcmds --jobs 8 --rerun-incomplete --configfile '/Users/kabirpeay/Desktop/metagenomics/Test_Metagenomics/test.config.yaml' --nolock --use-conda  --config workflow=complete -- 
You have 2 in 2 groups
localrules directive specifies rules that are not present in the Snakefile:
	finalize_QC

Building DAG of jobs...
Creating conda environment /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/metabat.yaml...
Downloading remote packages.
Environment for ../../../anaconda3/lib/python3.6/site-packages/atlas/envs/metabat.yaml created (location: .snakemake/conda/8fd67bb2)
Creating conda environment /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/eggNOG.yaml...
Downloading remote packages.
Environment for ../../../anaconda3/lib/python3.6/site-packages/atlas/envs/eggNOG.yaml created (location: .snakemake/conda/fadbc843)
Creating conda environment /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/required_packages.yaml...
Downloading remote packages.
Environment for ../../../anaconda3/lib/python3.6/site-packages/atlas/envs/required_packages.yaml created (location: .snakemake/conda/ade5988e)
Creating conda environment /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/report.yaml...
Downloading remote packages.
Environment for ../../../anaconda3/lib/python3.6/site-packages/atlas/envs/report.yaml created (location: .snakemake/conda/2703c97b)
Creating conda environment /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/sequence_utils.yaml...
Downloading remote packages.
Environment for ../../../anaconda3/lib/python3.6/site-packages/atlas/envs/sequence_utils.yaml created (location: .snakemake/conda/209c7f06)
Creating conda environment /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/checkm.yaml...
Downloading remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/envs/checkm.yaml:
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - pplacer=1.1.alpha17

[2018-10-16 16:23 CRITICAL] Command 'snakemake --snakefile /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/atlas/Snakefile --directory /Users/kabirpeay/Desktop/metagenomics/Test_Metagenomics --printshellcmds --jobs 8 --rerun-incomplete --configfile '/Users/kabirpeay/Desktop/metagenomics/Test_Metagenomics/test.config.yaml' --nolock --use-conda  --config workflow=complete -- ' returned non-zero exit status 1.
BIO-C02WG1PRHTDF:Test_Metagenomics kabirpeay$ ./pplacer
-bash: ./pplacer: No such file or directory

The stand alone conda install for pplacer only works for Linux and I've tried to install pplacer using the MacOSX binaries from Matsen's website but it doesn't seem to work properly and I get some "version unknown errors"

BIO-C02WG1PRHTDF:pplacer-Darwin-v1.1.alpha17-6-g5cecf99 kabirpeay$ cd scripts
BIO-C02WG1PRHTDF:scripts kabirpeay$ python setup.py install
/Users/kabirpeay/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:397: UserWarning: The version specified ('unknown') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
creating pplacer_scripts.egg-info
writing pplacer_scripts.egg-info/PKG-INFO
writing dependency_links to pplacer_scripts.egg-info/dependency_links.txt
writing top-level names to pplacer_scripts.egg-info/top_level.txt
writing manifest file 'pplacer_scripts.egg-info/SOURCES.txt'
reading manifest file 'pplacer_scripts.egg-info/SOURCES.txt'
writing manifest file 'pplacer_scripts.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.macosx-10.7-x86_64
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.6
copying and adjusting split_qiime.py -> build/scripts-3.6
copying and adjusting extract_taxonomy_from_biom.py -> build/scripts-3.6
copying and adjusting deduplicate_sequences.py -> build/scripts-3.6
copying and adjusting update_refpkg.py -> build/scripts-3.6
copying and adjusting refpkg_align.py -> build/scripts-3.6
copying and adjusting multiclass_concat.py -> build/scripts-3.6
copying and adjusting hrefpkg_query.py -> build/scripts-3.6
copying and adjusting classif_table.py -> build/scripts-3.6
copying and adjusting check_placements.py -> build/scripts-3.6
copying and adjusting add_classifications.py -> build/scripts-3.6
copying and adjusting sort_placefile.py -> build/scripts-3.6
copying and adjusting pca_for_qiime.py -> build/scripts-3.6
copying and adjusting classif_rect.py -> build/scripts-3.6
changing mode of build/scripts-3.6/split_qiime.py from 644 to 755
changing mode of build/scripts-3.6/extract_taxonomy_from_biom.py from 644 to 755
changing mode of build/scripts-3.6/deduplicate_sequences.py from 644 to 755
changing mode of build/scripts-3.6/update_refpkg.py from 644 to 755
changing mode of build/scripts-3.6/refpkg_align.py from 644 to 755
changing mode of build/scripts-3.6/multiclass_concat.py from 644 to 755
changing mode of build/scripts-3.6/hrefpkg_query.py from 644 to 755
changing mode of build/scripts-3.6/classif_table.py from 644 to 755
changing mode of build/scripts-3.6/check_placements.py from 644 to 755
changing mode of build/scripts-3.6/add_classifications.py from 644 to 755
changing mode of build/scripts-3.6/sort_placefile.py from 644 to 755
changing mode of build/scripts-3.6/pca_for_qiime.py from 644 to 755
changing mode of build/scripts-3.6/classif_rect.py from 644 to 755
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/split_qiime.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/extract_taxonomy_from_biom.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/deduplicate_sequences.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/update_refpkg.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/refpkg_align.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/multiclass_concat.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/hrefpkg_query.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/classif_table.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/check_placements.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/add_classifications.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/sort_placefile.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/pca_for_qiime.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/classif_rect.py -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/split_qiime.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/extract_taxonomy_from_biom.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/deduplicate_sequences.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/update_refpkg.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/refpkg_align.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/multiclass_concat.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/hrefpkg_query.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/classif_table.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/check_placements.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/add_classifications.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/sort_placefile.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/pca_for_qiime.py to 755
changing mode of build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/scripts/classif_rect.py to 755
copying pplacer_scripts.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying pplacer_scripts.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying pplacer_scripts.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying pplacer_scripts.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pplacer_scripts-unknown-py3.6.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing pplacer_scripts-unknown-py3.6.egg
Copying pplacer_scripts-unknown-py3.6.egg to /Users/kabirpeay/anaconda3/lib/python3.6/site-packages
Adding pplacer-scripts unknown to easy-install.pth file
Installing add_classifications.py script to /Users/kabirpeay/anaconda3/bin
Installing check_placements.py script to /Users/kabirpeay/anaconda3/bin
Installing classif_rect.py script to /Users/kabirpeay/anaconda3/bin
Installing classif_table.py script to /Users/kabirpeay/anaconda3/bin
Installing deduplicate_sequences.py script to /Users/kabirpeay/anaconda3/bin
Installing extract_taxonomy_from_biom.py script to /Users/kabirpeay/anaconda3/bin
Installing hrefpkg_query.py script to /Users/kabirpeay/anaconda3/bin
Installing multiclass_concat.py script to /Users/kabirpeay/anaconda3/bin
Installing pca_for_qiime.py script to /Users/kabirpeay/anaconda3/bin
Installing refpkg_align.py script to /Users/kabirpeay/anaconda3/bin
Installing sort_placefile.py script to /Users/kabirpeay/anaconda3/bin
Installing split_qiime.py script to /Users/kabirpeay/anaconda3/bin
Installing update_refpkg.py script to /Users/kabirpeay/anaconda3/bin

Installed /Users/kabirpeay/anaconda3/lib/python3.6/site-packages/pplacer_scripts-unknown-py3.6.egg
Processing dependencies for pplacer-scripts===unknown
Finished processing dependencies for pplacer-scripts===unknown

Any suggestions / work arounds for getting pplacer to work on OSX with Atlas?

**Comment by SilasK** [comment]
First are you sure you want to run atlas on OS X.  To get optimal results of the assembly I suggest to use spades assembler, which needs ~8CPU days x 250GB ram. But you can also use metabat. 

Atlas is not tested on mac osX, and some dependencies cannot be installed on osx, at least not with conda. 

A work around would be to use a container, and run atlas within. 
e.g. https://hub.docker.com/r/continuumio/miniconda/

**Comment by SilasK** [comment]
If I'm right you should at least beeing able to run `atlas qc` , to clean the reads and have a first impression for atlas.

**Comment by jmtsuji** [comment]
@mykophile I'm pretty sure that the conda pplacer install only works for linux currently -- I just ran into this problem with a colleague a few weeks ago. See https://anaconda.org/bioconda/pplacer (note how there is no 'Mac' label). This would break ATLAS on Mac OSX.

I've had good experiences installing/running ATLAS in the miniconda Docker container that @SilasK recommended, however. I've considered publishing the ATLAS Docker container to Dockerhub -- would this be helpful?

**Comment by mykophile** [comment]
thanks @SilasK and @jmtsuji. right now i am mostly trying to fine-tune the pipeline with test samples on OSX to figure out how I want to run things before trying to move to our HPC cluster. having the ATLAS Docker published on Dockerhub would be really helpful although i'm happy to try the  miniconda Docker container as well if it's much trouble.

i did also have one unrelated question that I should probably post in another thread, but... i know ATLAS is currently geared towards bacteria, but are there any recommendations for modifications to the standard pipeline when dealing with metatranscriptomes that have high eukaryote abundance?
