### ISSUE TITLE
Atlas for metatranscriptomes

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#143]
> i did also have one unrelated question that I should probably post in another thread, but... i know ATLAS is currently geared towards bacteria, but are there any recommendations for modifications to the standard pipeline when dealing with metatranscriptomes that have high eukaryote abundance?

@mykophile I haven't used Atlas for metatranscriptomes. Do you have DNA and RNA or only RNA?

You should use rna-spades, by changing the following parameters in the config file.

```
assembler: spades
spades_preset: rna
spades_extra: "" # extra command line options
```

I added the option in the lates commits to the master branch. So you would need to update.

I think prodigal can predict genes in assembled rna, so cou can make a gene catalog using
` atlas assemble gene_catalog `

and `atlas assemble`to get all the other reports and so on.

**Comment by mykophile** [comment]
I've got RNA only, about 50% Euk and 50% Prok.  I think the main problem is that Prokka and Prodigal are trained for prokaryotic genomes. I wonder it would be reasonable to skip gene prediction and just use Diamond on assembled transcripts since it searches all possible reading frames.

**Comment by SilasK** [comment]
Should this become part of Atlas? https://www.biorxiv.org/content/early/2018/08/07/386110.full.pdf+html

**Comment by SilasK** [comment]
@mykophile Can I just take the RNA contigs as genes and cluster them with cd-hit? Do you want to use diamond to annotate the transcripts to eggNOG and the taxonomy?

**Comment by mykophile** [comment]
PLASS looks quite promising and would be great to see as part of ATLAS. I was thinking of using diamond for the annotation / taxonomy steps, not clustering.

**Comment by SilasK** [comment]
@MCamp91 Your happy to continue the discussen here. 
I have no metatranscriptome data available. So, I could not test it. 

I'm not sure what the contigs of rnaSpades look like, and if prodigal can predict genes on them or if they are the genes. 

Could you test to run rnaSpades, and then send me one of the ouptut files. 

e.g. sample/sample_contigs.fasta

**Comment by MCamp91** [comment]
Matthew Campbell has shared a OneDrive for Business file with you. To view it, click the link below.


<https://studentcurtinedu-my.sharepoint.com/personal/15164810_student_curtin_edu_au/Documents/Attachments/MM1-SB_contigs(1).fasta>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://studentcurtinedu-my.sharepoint.com/personal/15164810_student_curtin_edu_au/Documents/Attachments/MM1-SB_contigs(1).fasta>

MM1-SB_contigs(1).fasta<https://studentcurtinedu-my.sharepoint.com/personal/15164810_student_curtin_edu_au/Documents/Attachments/MM1-SB_contigs(1).fasta>




Hello,


I've attached an output file from the run I did with metahit. The pipeline was unable to assemble contigs with spades and suggested config settings.


However, the spades run produced these kinds of outputs in the assembly - hard_filtered_transcripts.fasta,  transcripts.fasta, before_rr.fasta  dataset.info  and soft_filtered_transcripts.fasta .... would you be interested in seeing any of these?


Cheers,


Matt

________________________________

**Comment by MCamp91** [comment]
Looks like the attachment didn't work.


https://www.dropbox.com/s/juc16etah9tev50/MM1-SB_contigs.fasta?dl=0


Let me know if you can use this link.


Matt


________________________________

**Comment by SilasK** [comment]
OK, I see then with rna-spades I should use the `transcripts.fasta`with RNA spades. 
If it worked with megahit.

Do you know if prodigal can predict genes from transcripts? 

Can you try to run 
 `atlas run gene catalog`

with  

```
assembler: megahit

genecatalog:
  source: contigs

```

**Comment by MCamp91** [comment]
Hello,


I did the run genecatalog but ran into this issue (see below).


Looks like its still trying to bin the contigs...


These were the inputs I used..


run with config parameters set to:

assembler: megahit

genecatalog:
  source: contigs

running script - nohup /data/work/atlas_scripts/run.sh genecatalog &

Cheers,


Matt


40 of 83 steps (48%) done

[Thu Feb 14 04:09:40 2019]
rule maxbin:
    input: MM2-SB/MM2-SB_contigs.fasta, MM2-SB/binning/coverage/MM2-SB_coverage.txt
    output: MM2-SB/binning/maxbin/intermediate_files
    log: MM2-SB/logs/binning/maxbin.log
    jobid: 60
    wildcards: sample=MM2-SB
    threads: 16


        mkdir MM2-SB/binning/maxbin/intermediate_files 2> MM2-SB/logs/binning/maxbin.log
        run_MaxBin.pl -contig MM2-SB/MM2-SB_contigs.fasta             -abund MM2-SB/binning/coverage/MM2-SB_coverage.txt             -out MM2-SB/binning/maxbin/intermediate_files/MM2-SB             -min_contig_length 1000             -thread 16             -prob_threshold 0.9             -max_iteration 50 >> MM2-SB/logs/binning/maxbin.log

        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.summary MM2-SB/binning/maxbin/intermediate_files/.. 2>> MM2-SB/logs/binning/maxbin.log
        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.marker MM2-SB/binning/maxbin/intermediate_files/..  2>> MM2-SB/logs/binning/maxbin.log
        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.marker_of_each_bin.tar.gz MM2-SB/binning/maxbin/intermediate_files/..  2>> MM2-SB/logs/binning/maxbin.log
        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.log MM2-SB/binning/maxbin/intermediate_files/..  2>> MM2-SB/logs/binning/maxbin.log


Activating conda environment: /databases/conda_envs/189bcd05
[Thu Feb 14 04:09:46 2019]
Error in rule maxbin:
    jobid: 60
    output: MM2-SB/binning/maxbin/intermediate_files
    log: MM2-SB/logs/binning/maxbin.log
    conda-env: /databases/conda_envs/189bcd05

RuleException:
CalledProcessError in line 212 of /opt/conda/lib/python3.6/site-packages/atlas/rules/binning.snakefile:
Command 'source activate /databases/conda_envs/189bcd05; set -euo pipefail;
        mkdir MM2-SB/binning/maxbin/intermediate_files 2> MM2-SB/logs/binning/maxbin.log
        run_MaxBin.pl -contig MM2-SB/MM2-SB_contigs.fasta             -abund MM2-SB/binning/coverage/MM2-SB_coverage.txt             -out MM2-SB/binning/maxbin/intermediate_files/MM2-SB             -min_contig_length 1000             -thread 16             -prob_threshold 0.9             -max_iteration 50 >> MM2-SB/logs/binning/maxbin.log

        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.summary MM2-SB/binning/maxbin/intermediate_files/.. 2>> MM2-SB/logs/binning/maxbin.log
        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.marker MM2-SB/binning/maxbin/intermediate_files/..  2>> MM2-SB/logs/binning/maxbin.log
        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.marker_of_each_bin.tar.gz MM2-SB/binning/maxbin/intermediate_files/..  2>> MM2-SB/logs/binning/maxbin.log
        mv MM2-SB/binning/maxbin/intermediate_files/MM2-SB.log MM2-SB/binning/maxbin/intermediate_files/..  2>> MM2-SB/logs/binning/maxbin.log ' returned non-zero exit status 255.
  File "/opt/conda/lib/python3.6/site-packages/atlas/rules/binning.snakefile", line 212, in __rule_maxbin
  File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job maxbin since they might be corrupted:
MM2-SB/binning/maxbin/intermediate_files
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/work/24samples/atlas_201_genecat_test/.snakemake/log/2019-02-14T024844.817097.snakemake.log
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
[2019-02-14 04:09 CRITICAL] Command 'snakemake --snakefile /opt/conda/lib/python3.6/site-packages/atlas/Snakefile --directory /data/work/24samples/atlas_201_genecat_test --printshellcmds --jobs 16 --rerun-incomplete --configfile '/data/work/24samples/atlas_201_genecat_test/config.yaml' --nolock  --use-conda  --conda-prefix /databases/conda_envs   genecatalog   ' returned non-zero exit status 1

________________________________

**Comment by MCamp91** [comment]
Hello,

Just to simplify my previous email.

The output file /data/work/24samples/atlas_201_genecat_test/out_run_1, this is the task that fails:

rule maxbin:
    input: MM2-SB/MM2-SB_contigs.fasta, MM2-SB/binning/coverage/MM2-SB_coverage.txt
    output: MM2-SB/binning/maxbin/intermediate_files
    log: MM2-SB/logs/binning/maxbin.log
    jobid: 60
    wildcards: sample=MM2-SB
    threads: 16

so it looks like the input files are indeed the assembled contigs.

Can I restart the run just by re-executing any atlas command in the same folder? I’m not sure how I can do this going off the current documentation for atlas.

Another question … I’ve tried running my RNAseq data as metagenomes but had issues with the binning. Is there any thing I could change in the config file to increase chances of binning?

Cheers,

Matt


________________________________

**Comment by SilasK** [comment]
The genecatlog and binning are linked. which for metagenomic samples assures that you don't continue with having forgotten something. 

In your case try:
```
atlas run None "Genecatalog/all_genes_unfiltered.faa"
```



to predict the genes and concatenate them. . 
`atlas run None` runs atlas with no specific workflow. 

If this works you can run:

```
atlas run None "Genecatalog/gene_catalog.faa"
```
to get the clustered gene catalog.
```
"Genecatalog/counts/median_coverage.tsv.gz"
```
To get coverages

and/or 
```
atlas run None "Genecatalog/annotations/eggNog.tsv"
```
for annotation.

**Comment by SilasK** [comment]
For your other questions:
> Can I restart the run just by re-executing any atlas command in the same folder?
Yes, you can and should run atlas in the same folder if you use the same assembler. 

The difference for metatranscriptome and metagenome are mainly on the level of contaminant removal. 
'rRNA' is not considered as a contaminant for metagenomes. But I'm not sure if you have added them to be removed. 

> How to cluster metatranscriptomes?

Can you tell me what you have for data and what you want to achive? why not on slack .
may be `final_binner: concoct` works better for that.

**Comment by MCamp91** [comment]
Hello,


I've been trying to run atlas in a few different configurations in regards to the the QC and assemblers, but i'm running into these issue (see attached).


Not sure if it's issue with the pipeline or the quality of my samples? Is it possible to change some of the parameters of rnaSpades i.e contig length?


cheers



________________________________

**Comment by SilasK** [comment]
Probably your attached files didn't pass through.

Yes you can parametrize the (rna) spades in the config file, generated with `atlas init`:


```

# Spades
#------------
spades_skip_BayesHammer: False
spades_use_scaffolds: false # otherwise use contigs
#Comma-separated list of k-mer sizes to be used (all values must be odd, less than 128 and listed in ascending order).
spades_k: auto
spades_preset: rna    # meta, ,normal, rna  single end libraries doesn't work for metaspades
spades_extra: "" # extra keywords 

# Filtering
#------------
prefilter_minimum_contig_length: 200
# filter out assembled noise
# after filtering
minimum_contig_length: 300
```

**Comment by MCamp91** [comment]
Hello,


I've reattached the files. Can you view them?


Would lowering the contig length make a difference?


Cheers,


Matt

________________________________

**Comment by SilasK** [comment]
Sorry, I don’t see the logs.

Try to add them directly to https://github.com/metagenome-atlas/atlas/issues/143


I don’t think that lowering the contigs length lower than 200bp is a good Idea.

**Comment by MCamp91** [comment]
[Metatranscriptome_metaSpades_run.txt](https://github.com/metagenome-atlas/atlas/files/2943893/Metatranscriptome_metaSpades_run.txt)
[Metagenome_run.txt](https://github.com/metagenome-atlas/atlas/files/2943894/Metagenome_run.txt)
[Metatranscriptomics_rnaSpades_run.txt](https://github.com/metagenome-atlas/atlas/files/2943895/Metatranscriptomics_rnaSpades_run.txt)

**Comment by SilasK** [comment]
@MCamp91 @mykophile  could you try out #183
