### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#147]
Dear @brwnj @sofie8

I like to centralize the information about the debugging. If you have problems don't hesitate to add issues and reference #147.

What should work:
`atlas assemble` gives you the gene catalog, with abundances

`atlas bin-genomes` a set of dereplicated genomes, with abundances

Note: DasTool is not yet on bioconda. I suggest to set 
`final_binner: metabat`in the config file. 

Todo:
 - [x] DASTool bia conda package
 - [ ] Taxonomy for genomes
 - [ ] ...

**Comment by Sofie8** [comment]
#147 Master:
snakemake --config workflow="complete" -R gene_catalog

rule predict_single_copy_genes:
    input: Genecatalog/gene_catalog.faa
    output: Genecatalog/annotation/single_copy_genes_bacteria.tsv
    log: logs/Genecatalog/annotation/predict_single_copy_genes_bacteria.log
    jobid: 40
    wildcards: domain=bacteria
    threads: 20
error:
mv: cannot stat Genecatalog/gene_catalog.faa.bacteria.scg: No such file or directory

solution:
In genecatalog.snakefile
line 462:        "mv {input[0]}.{wildcards.domain}.scg {output} "
should be: "mv {input[0]}.scg {output} "

**Comment by SilasK** [comment]
Thank you, It's now in the master branch.
