### ISSUE TITLE
Snakemake Environments Failing to Activate

### ISSUE THREAD

**Issue by Lswhiteh** [metagenome-atlas/atlas#149]
I'm attempting to run Atlas on a TORQUE cluster with a different data storage area than my home dir containing snakemake and conda files. Not sure if this is too similar to #95 but the snakemake rule governing where the conda environments are created fail to activate at seemingly random jobs, and I have yet been able to figure out the specific cause

I'm attaching 2 output logs, one from an attempt on all my samples and one from a test run with just one sample. If anyone can figure out the pattern behind the failures and help me fix it I'd appreciate it, I'm not sure if this is on my end with Snakemake or something I need to change with my installation/config of atlas.

[atlas_assembly.o831774.txt](https://github.com/pnnl/atlas/files/2570514/atlas_assembly.o831774.txt)
[atlas_assembly_test.o835510.txt](https://github.com/pnnl/atlas/files/2570515/atlas_assembly_test.o835510.txt)

**Comment by SilasK** [comment]
I suggest to append the command option `--conda-prefix path/where/you/want/the/envs `

It seems that snakemake doesn't find the path to a conda environment. Some rules are execuded locally, if they use only low memory and high IO, but most are submitted to the cluster. This could lead to the random error. 

Are you using a profile to submit the jobs?

Does the Torque cluster have access to the to the home directory (e.g. shared filesystem)?

**Comment by Lswhiteh** [comment]
Do you mean appending the conda prefix to the atlas command or in the actual snakemake file?

No profile as far as I know, but I am by no mean super familiar with HPC setups.

Yes it does, which is where I'm storing everything else (data and the actual atlas install as well)

**Comment by SilasK** [comment]
Atlas is a wrapper for a snakmake execution (see docs) so you can almost
all snakemake-comand options to a atlass call.

**Comment by Lswhiteh** [comment]
Adding `--conda-prefix path ` to the end of a call worked, thank you. Now I just need to troubleshoot some plotly errors.

**Comment by SilasK** [comment]
Can you show me the logs?

**Comment by SilasK** [comment]
In the meantime if you add -k, unaffected jobs contnue.

**Comment by Lswhiteh** [comment]
The -k option is nice, I wasn't aware of that, I'll give it a shot. Here's a log file from an attempt at running assemble on one sample. I can provide more data files as needed, or we can open a new issue if this isn't just me not being familiar enough. Thank you for the help! 
[atlas_assembly_test.o838314.txt](https://github.com/pnnl/atlas/files/2582155/atlas_assembly_test.o838314.txt)

**Comment by SilasK** [comment]
One of the two errors should be solved with 
https://github.com/pnnl/atlas/commit/21f0c7e194530c506f4b1d187facc431e4ed68d8
