### ISSUE TITLE
ValueError in get_contigs_from_gene_names

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#152]
I'm testing out the ATLAS master branch and noticed a bug in `localrules: get_contigs_from_gene_names` (in `gene_annotation.snakefile`) that I do not think has yet been addressed in any branch.

# Problem description
I think that `localrules: get_contigs_from_gene_names` currently requires that the sample name contain no underscores because of how it parses the contig and gene ID from prodigal output.

When running, I got the following error:
```
Error in rule get_contigs_from_gene_names:
    jobid: 0
    output: Jul18_304_6m/annotation/predicted_genes/Jul18_304_6m.tsv

RuleException:
ValueError in line 138 of ~/miniconda3/envs/atlas_master_0e477a4/lib/python3.6/site-packages/atlas/rules/gene_annotation.snakefile:
too many values to unpack (expected 3)
```

Looking at the code, I see:
```
    localrules: get_contigs_from_gene_names
    rule get_contigs_from_gene_names:
        input:
            faa = "{sample}/annotation/predicted_genes/{sample}.faa",
        output:
            tsv= "{sample}/annotation/predicted_genes/{sample}.tsv"
        run:
            header = ["gene_id", "Contig", "Gene_nr", "Start", "Stop", "Strand", "Annotation"]
            with open(output.tsv, "w") as tsv:
                tsv.write("\t".join(header) + "\n")
                with open(input.faa) as fin:
                    gene_idx = 0
                    for line in fin:
                        if line[0] == ">":
                            text = line[1:].strip().split(" # ")
                            old_gene_name = text[0]
                            text.remove(old_gene_name)
                            sample, contig_nr, gene_nr = old_gene_name.split("_")
                            tsv.write("{gene_id}\t{sample}_{contig_nr}\t{gene_nr}\t{text}\n".format(
                                text="\t".join(text),
                                gene_id=old_gene_name,
                                i=gene_idx,
                                sample=sample,
                                gene_nr=gene_nr,
                                contig_nr=contig_nr))
                            gene_idx += 1
```

The line that appears to be the problem is:
```
sample, contig_nr, gene_nr = old_gene_name.split("_")
```

In my case, where the sample ID is `Jul18_304_6m`, the prodigal FastA (.faa) header looks like:
```
>Jul18_304_6m_0_1 # 2 # 304 # 1 # ID=1_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.739
```

Which results in,
`old_gene_name` = `Jul18_304_6m_0_1`
 `old_gene_name.split("_")` = `[ 'Jul18', '304', '6m', '0', '1' ]`
which is longer than three entries.

# Proposed solution
To make the rule able to handle sample names containing underscores, take the last two entries of  `old_gene_name.split("_")` as the contig and gene ID, and then re-join the first entries to become the sample name (for example, consider if `old_gene_name = "Jul18_304_6m_0_1"`):
```
old_gene_name_split = old_gene_name.split("_")
gene_nr = old_gene_name_split[-1]
contig_nr = old_gene_name_split[-2]
sample = "_".join(old_gene_name_split[:len(old_gene_name_split)-2])
```

I've tested this, and it looks like it works for my samples:
```
$ head Jul18_304_6m.tsv
gene_id	Contig	Gene_nr	Start	Stop	Strand	Annotation
Jul18_304_6m_0_1	Jul18_304_6m_0	1	2	304	1	ID=1_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.739
Jul18_304_6m_0_1	Jul18_304_6m_0	1	1	195	1	ID=2_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.569
Jul18_304_6m_0_1	Jul18_304_6m_0	1	210	317	1	ID=2_2;partial=01;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.509
Jul18_304_6m_0_1	Jul18_304_6m_0	1	1	318	1	ID=4_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.582
Jul18_304_6m_0_1	Jul18_304_6m_0	1	1	300	-1	ID=5_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.470
Jul18_304_6m_0_1	Jul18_304_6m_0	1	1	330	1	ID=6_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.179
Jul18_304_6m_0_1	Jul18_304_6m_0	1	90	329	1	ID=7_1;partial=01;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.338
Jul18_304_6m_0_1	Jul18_304_6m_0	1	3	326	-1	ID=8_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.386
Jul18_304_6m_0_1	Jul18_304_6m_0	1	110	322	-1	ID=9_1;partial=00;start_type=TTG;rbs_motif=None;rbs_spacer=None;gc_cont=0.521

```

I could make a PR if helpful.

Thanks again for your work on ATLAS! Looking forward to `v2.0.0`.

Jackson

**Comment by SilasK** [comment]
Hey Jackson,

Yes, can make a PR. Great, You managed to run Atlas without problems with
underscores in sanple names?
 Thank you very much for your contribution..

**Comment by jmtsuji** [comment]
Hi @SilasK 

Now back from the winter break. Sure, I can make a PR. Which branch would you like me to make the PR to? Dev?

I managed to run successfully (with underscores in the sample names) up to the EggNOG search, where the job number increased substantially, and the run eventually failed. This looks related to #153 

Once #153 is resolved, I can try again and see how the run goes with my samples.

Jackson

**Comment by SilasK** [comment]
I'm officially back next week.

But I've resolved #153 on the dev branch. There should be now less jobs.
However you may need to delete the files in Genecatalog/annotation/subsets


Could you join the Slack (see readme), to discuss the futer of the
Genecatalog workflow.

>

**Comment by jmtsuji** [comment]
Sure, I've joined the Slack channel.

**Comment by jmtsuji** [comment]
This seems to be addressed now -- closing this issue.
