### ISSUE TITLE
Add dependency version reporting

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#158]
Currently, ATLAS generates several conda environments for different portions of the run. Software versions for these environments are defined in .yaml files in the `envs` folder. However, some software versions are defined loosely (e.g., `prodigal >=2.6.1`), meaning that they can potentially change from run to run.

As an enhancement feature, it would be great if ATLAS saved a log file (e.g., via `conda list`) of the versions of all dependencies used in the run for each conda environment. Currently, I can mine the ATLAS conda environments myself after the run to find software versions, but it would be convenient to have all the info pre-printed to a log.

Not sure how easy it is to call conda itself (e.g., `conda list`) from within a snakefile, though -- I've never tried.

Thanks again for all your work!

**Comment by SilasK** [comment]
Once the programs are installed they shouldn't update. But We should maybe fix the versions (e.g. `prodigal =2.6.1`) and then update with the version of Atlas.

**Comment by jmtsuji** [comment]
@SilasK Yes, the programs should not update once they are installed, but if you perform another ATLAS run later with the same version of ATLAS, you might software with different version numbers.

I agree, one good solution would be to fix the version numbers associated with each ATLAS version.
