### ISSUE TITLE
'table_source_header' is not defined in tables.py

### ISSUE THREAD

**Issue by cam315** [metagenome-atlas/atlas#160]
Dear developers,

When I use merge-tables function in atlas, there is NameError: name 'table_source_header' is not defined. 

I think it should be changed from 'table_source_header' to 'table_source' in line 170 of tables.py :

def do_merge(gene_tsv, refseq_tsv, counts_tsv=None, eggnog=None):
        """Reads input files, creates temporary dataframes, and performs the merge."""
        logging.info("Parsing Prokka TSV: %s" % gene_tsv)
        gene_tsv_header = **table_source_heade**r(gene_tsv)

**Comment by SilasK** [comment]
This should be solved with #162
