### ISSUE TITLE
per bin coverage values

### ISSUE THREAD

**Issue by espasov** [metagenome-atlas/atlas#164]
Is there a file that has the per bin coverage values? I can find the per contig coverage values in the `assemblyname_contig_coverage.tsv file`, but not one that seems to have it calculated per bin.
I'm looking for the estimated depth of sequencing coverage. If there isn't a file that contains this, could this perhaps be added in the future? It would be very useful information to have. In the meantime, could you describe the best way to calculate the coverage for each bin?

Another question: Could you tell me how those contig coverage values (in the `assemblyname_contig_coverage.tsv file`)  are calculated? 
Also, I used ATLAS version 1.0.22

Thank you!

**Comment by SilasK** [comment]
Hallo @espasov,

Thank you for using Atlas. I just updated the API of atlas 2. So I recommend you to update.  It shouldn't change the process you have already done. You just need to update the config file. 

For your question:

if you run:
`atlas bin-genomes <config.file> `with atlas 1
or 
`atlas run genomes -w <workingdirectory> ` 

Atlas will dereplicate bins from different sample which are the same and make a consistent set of genomes (found in genones/genomes) as well as quantify the raw reads and coverage. That is what you are looking fore, isn't it?

The coverage values are calculated with pileup.sh from bbmap. I think it is the mean coverage over the contig.
