### ISSUE TITLE
issue during the example run

### ISSUE THREAD

**Issue by solna** [metagenome-atlas/atlas#169]
I went into this issue during the example run. Could you give some suggestions on solving this? I followed exactly the instruction online for the installation.

[Tue Feb 12 14:40:34 2019]
Error in rule align_reads_to_prefilter_contigs:
    jobid: 0
    output: S005/sequence_alignment/alignment_to_prefilter_contigs.sam
    log: S005/logs/assembly/post_process/align_reads_to_prefiltered_contigs.log
    conda-env: /home/chage/Public/atlas_databases/conda_envs/83ee959a

RuleException:
CalledProcessError in line 394 of /home/chage/miniconda3/envs/metagenome-atlas/lib/python3.6/site-packages/atlas/rules/assemble.snakefile:
Command 'source activate /home/chage/Public/atlas_databases/conda_envs/83ee959a; set -euo pipefail;  
                bbwrap.sh nodisk=t                 ref=S005/assembly/S005_prefilter_contigs.fasta                 in1=S005/sequence_quality_control/S005_QC_R1.fastq.gz,S005/sequence_quality_control/S005_QC_se.fastq.gz in2=S005/sequence_quality_control/S005_QC_R2.fastq.gz,null                 trimreaddescriptions=t                 out=S005/sequence_alignment/alignment_to_prefilter_contigs.sam                 threads=4                 pairlen=1000                 pairedonly=t                 minid=0.76                 mdtag=t                 xstag=fs                 nmtag=t                 sam=1.3                 local=t                 ambiguous=all                 secondary=t                 saa=f                 append=t                 machineout=t                 maxsites=10                 -Xmx3G 2> S005/logs/assembly/post_process/align_reads_to_prefiltered_contigs.log ' returned non-zero exit status 1.
  File "/home/chage/miniconda3/envs/metagenome-atlas/lib/python3.6/site-packages/atlas/rules/assemble.snakefile", line 394, in __rule_align_reads_to_prefilter_contigs
  File "/home/chage/miniconda3/envs/metagenome-atlas/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
[Tue Feb 12 14:40:35 2019]
Finished job 6.
30 of 103 steps (29%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /home/chage/Documents/atlas/.snakemake/log/2019-02-12T142818.012047.snakemake.log
[2019-02-12 14:40 CRITICAL] Command 'snakemake --snakefile /home/chage/miniconda3/envs/metagenome-atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /home/chage/Documents/atlas --printshellcmds --jobs 8 --rerun-incomplete --configfile '/home/chage/Documents/atlas/config2.yaml' --nolock  --use-conda  --conda-prefix /home/chage/Public/atlas_databases/conda_envs   all   ' returned non-zero exit status 1.

**Comment by SilasK** [comment]
Hi @solna ,
The example_data is not ideal. It won't pass the binning. 
It should however pass trough the assemlby step. `atlas assemble`

I assume it doesn't work for you with only 3G of memory. The alligning step is relatively memory demanding, ~30G. 

You can also have a look at the log file: S005/logs/assembly/post_process/align_reads_to_prefiltered_contigs.log

**Comment by solna** [comment]
Thanks a lot for the prompt reply. I just tried with another set of real raw data on a workstation and it worked well. However I went into the same issue  #29 as you mentioned with maxbin.

**Comment by SilasK** [comment]
This is not really a bug, it's more the sign that the assembly is too small.

- check the assembly report
Possible solutions:
- use metabat (I think the best binner)
- use spades for assembly
  - when memory is a porblem you can deactivate the second error correction:
by setting
``spades_skip_BayesHammer: true ``
in the config file

**Comment by SilasK** [comment]
Have you used a snakemake profile, like [this](https://github.com/metagenome-atlas/generic)

**Comment by solna** [comment]
not yet, I will try to follow what you suggested above.
thanks a lot for the help.

**Comment by SilasK** [comment]
I think this issue is solved. Don't hesitate to re-open it.
