### ISSUE TITLE
Problem with up to date conda

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#176]
Apparently, there is an [error](https://bitbucket.org/snakemake/snakemake/issues/1115/cannot-activate-conda-enironment-using) in snakemake with the new conda (v.4.6.7) 

A workaround from @jmtsuji  is the following:

```
conda activate atlas_env

path=/path/to/miniconda #or anaconda

cp  $path/bin/*activate $path/envs/atlas_env/bin/
```

**Comment by jmtsuji** [comment]
@SilasK I had the same problem. Less elegantly, I resolved the issue by manually copying `activate` and `deactivate` from `/path/to/miniconda/bin` into the bin folder of the conda environment where atlas is installed. The issue is permanently solved for the atlas conda environment after this.

**Comment by SilasK** [comment]
This should be solved with snakemake v.5.4.3

**Comment by SilasK** [comment]
I still have the same problem when using snakemake inside a conda environment.

‌

snakemake version: 5.5.4

conda 4.7.8 and 4.7.10

I use Using shell: /bin/bash by default.

‌

It' is true the conda command is not in the path, but somehow it still works, e.g. you can use conda deactivate.

‌

Does this means one can run snakemake only from the main conda environment?

‌

‌

As a hack I managed to link the conda executable in my environment.

‌

ln -s ~/scratch/miniconda3/bin/conda ~/scratch/miniconda3/envs/myenv/bin/
