### ISSUE TITLE
Contig annotation and quantification 

### ISSUE THREAD

**Issue by raw937** [metagenome-atlas/atlas#186]
Hello, 

If I have assembled contigs and just want to annotation/quantify (eggnog4, SEED etc) is that option still available? Not the bins but the contigs directly. 
I couldn't find it if it is.

**Comment by SilasK** [comment]
genes are predicted on all contigs in with `atlas run  assembly `

Annotation is automated in the  genecatalog module 

Change the source for the gene catalog in the config file.
```
########################
# Gene catalog
#######################
genecatalog:
  source: contigs
...
```

Rhen run.
`atlas run genecatalog  <options> combine_gene_coverages `

The advantage is with the genecatalog you have all genes in all samples and the time-consuming annotation is done only once.

**Comment by raw937** [comment]
Not working. 

#no run command
atlas run genecatalog test_1k.fasta combine_gene_coverages
Usage: atlas [OPTIONS] COMMAND [ARGS]...
Try "atlas -h" for help.

Error: No such command "run".

#tried with assemble command
atlas assemble genecatalog test_1k.fasta combine_gene_coverages
[2019-03-14 13:40 CRITICAL] Config not found: /data/friesen/clean/CQ/results/assemblies/subsampled/genecatalog

added this to the end of the file:
########################
# SAMPLES
########################
samples: 'pwd'

########################
# Gene catalog
#######################
genecatalog:
  source: contigs

atlas assemble genecatalog testatlas_contig combine_gene_coverages
[2019-03-14 13:43 CRITICAL] Config not found: /data/friesen/clean/CQ/results/assemblies/subsampled/1k/genecatalog

Do I also need to point to the reads?

**Comment by SilasK** [comment]
Seems you are using atlas 2.0.0 or less.
Try to update and follow the Readme or docs how to use the new API with
atlas run.

Kind regards Silas
And may be subscribe to follow the releases on github. I continue to add
minior bug fixes.

**Comment by SilasK** [comment]
@raw937 Did you succeed? 
How would you use SEED? is there a command line application?

**Comment by raw937** [comment]
I didn't succeed yet. I have to wait on my HPC admin. I will let you know?
Hmm. I have always wanted to integrate metacyc and SEED to ATLAS. SEED hasn't been updated in a while or metacyc as well. However, I do have older databases that could be used (~2014). I could share. The FOAM database maybe a more useful way to get KOs. 
However, I do like eggnog's mapper which is useful. 
Databases are very hard to maintain funding. Only Uniprot has been able to maintain the funding over the long term. KEGG, metacyc, cog, nog, etc all pay models or extinct. Its a real crime that we can't maintain funding to keep up with maintaining tools, databases, with the ever growing masses of sequence data.

**Comment by SilasK** [comment]
Continue discussion on https://github.com/metagenome-atlas/atlas/discussions/599
