### ISSUE TITLE
How to skip dereplication?

### ISSUE THREAD

**Issue by dtnaylor124** [metagenome-atlas/atlas#195]
Hi, I was just wondering how I could skip over the dereplication steps when running ATLAS. I'm working with a sample of an isolate, so there's only one genome and therefore nothing to dereplicate. This causes an error that makes ATLAS stop, and I'd like it to continue on regardless. Thanks!

**Comment by SilasK** [comment]
Sorry I was on vacation. 

Could you send me the log of the dereplication step. Ideally dREP should be intelligent enough. 

With `atlas run binning` you run the pipeline utill the dereplication step, this gives you the checkm Results, however not the CAT taxonomy, or the gene prediction.

In which output would you be interested?

**Comment by dtnaylor124** [comment]
Both outputs ideally, I want to get all the annotations possible. Here's the log!

[pre_dereplication.log](https://github.com/metagenome-atlas/atlas/files/3056580/pre_dereplication.log)

**Comment by dtnaylor124** [comment]
I'm having an issue with that first step (having a missing input, I'm guessing). Error message is attached.
[error_04092019.txt](https://github.com/metagenome-atlas/atlas/files/3060773/error_04092019.txt)

**Comment by SilasK** [comment]
This is somehow related to #194
