### ISSUE TITLE
Fails after allbins2genome.tsv

### ISSUE THREAD

**Issue by mdjlynch** [metagenome-atlas/atlas#200]
I am having a similar issue to #194. Suggestions from #195 are not resolving the problem. The behaviour is occurring in metagenomes with no replicated bins and one metagenome with potential replication (near threshold). Thanks.

[2019-04-15T175347.006770.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3081595/2019-04-15T175347.006770.snakemake.log)

**Comment by SilasK** [comment]
Hey @mdjlynch what snakemake and Atlas version are you using? 
The problem arises from a bug in snakemake not going beyond a checkpoint.

**Comment by mdjlynch** [comment]
Thanks for the response.
snakemake version 5.4.4
atlas version 2.0.7

**Comment by SilasK** [comment]
You are also trying to skip the dereplication step?

**Comment by mdjlynch** [comment]
I primarily just want the updated analog of the previous *annotations.txt file. So, a table of annotations with abundances within a metagenome (or set of metagenomes). I like how informative the eggNOG.tsv is, but the count data and mapping back to the sample aren't explicit. I wasn't sure if the end of the pipeline generated such a file as a few different metagenomes seem to be crashing at the same point.

**Comment by mdjlynch** [comment]
And the files/directories.

genomes/clustering/old2newID.tsv:
BinID   MAG
TBL5m-S1-L001-001_concoct_08    MAG1
TBL5m-S1-L001-001_maxbin_02     MAG2
TBL5m-S1-L001-001_maxbin_06     MAG3

ls genomes/pre_dereplication/dereplicated_genomes:
TBL5m-S1-L001-001_concoct_08.fasta  TBL5m-S1-L001-001_maxbin_02.fasta  TBL5m-S1-L001-001_maxbin_06.fasta

ls genomes/Dereplication/dereplicated_genomes:
TBL5m-S1-L001-001_concoct_08.fasta  TBL5m-S1-L001-001_maxbin_02.fasta  TBL5m-S1-L001-001_maxbin_06.fasta

**Comment by SilasK** [comment]
OK, I don't see why the rule should fail. 
Could you rerun atlas in the same working dir so that it runs again the rule which fails. Tell me if there are any other log information which are not in the log file?

**Comment by SilasK** [comment]
If you are interested mainly in the global annotation of genes and their abundance the **genecatalog** workflow is what you need. 

`atlas run genecatalog`

This will give you a genecatalog of all genes in all samples, their abundance and eggNOG annotation. 

If you are not so much interested in the binns, e.g. tax annotation you can focus rather on all the contigs by seting:
```
########################
# Gene catalog
#######################
genecatalog:
  source: contigs
...
```

otherwise only the genes of your 4 MAGs will be used. By the way, do you expect much more then 4 genomes in your metagenome?

**Comment by mdjlynch** [comment]
So, starting over and just using the genecatalog option seems to have worked. Yes, I am not expecting many MAGs in this sample.

The annotation folder (e.g., eggNog.tsv) doesn't appear to have gene abundances or sample information I can get that from the orf2gene.tsv file but where can I find the gene abundance data?

Thanks.

**Comment by SilasK** [comment]
With `run atlas genecatalog <options>  combine_gene_coverages` you get the quantifications.

**Comment by mdjlynch** [comment]
Great. Thanks.
