### ISSUE TITLE
Error in rule init_pre_assembly_processing

### ISSUE THREAD

**Issue by susheelbhanu** [metagenome-atlas/atlas#213]
Hi, 

The log hasn't been much help in understanding why the error happened. Could you please let me know how I can correct this issue. 

```
7698 Error in rule init_pre_assembly_processing:
7699     jobid: 1352
7700     output: 14-Susheel-S16-001/assembly/reads/QC_R1.fastq.gz, 14-Susheel-S16-001/assembly/reads/QC_R2.fastq.gz, 14-Susheel-S16-001/assembly/reads/QC_se.fastq.gz
7701     log: 14-Susheel-S16-001/logs/assembly/init.log (check log file(s) for error message)
7702     conda-env: /mnt/lscratch/users/sbusi/metagenome-atlas/atlas/databases/conda_envs/109a2af1
7703     shell:
7704
7705         reformat.sh in1=14-Susheel-S16-001/sequence_quality_control/14-Susheel-S16-001_QC_R1.fastq.gz,14-Susheel-S16-001/sequence_quality_control/14-Susheel-S16-001_QC_se.fastq.gz in2=14-Susheel-S16-001/sequence_quality_control/14-Susheel-S16-001_QC_R2.fastq.gz             interleaved=f             out1=14-Sushe     el-S16-001/assembly/reads/QC_R1.fastq.gz,14-Susheel-S16-001/assembly/reads/QC_se.fastq.gz out2=14-Susheel-S16-001/assembly/reads/QC_R2.fastq.gz             iupacToN=t             touppercase=t             qout=33             overwrite=true             verifypaired=t             addslash=t             trimreaddes     cription=t             threads=4             -Xmx8G 2> 14-Susheel-S16-001/logs/assembly/init.log
7706
7707         (exited with non-zero exit code)
```

I'm also attaching the full log file. 

Thank you,
Susheel 

[2019-06-12T162351.751024.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3284777/2019-06-12T162351.751024.snakemake.log)

**Comment by susheelbhanu** [comment]
Sorry, but a quick update. I also checked the ```14-Susheel-S16-001/logs/assembly/init.log``` file. 

Interestingly enough, it says can't read the files, but the files exist where they are supposed to be.

**Comment by SilasK** [comment]
The error is fixed in my last commit (v2.1.2). Could you try to pul the newest master or wait a bit until it will be available on conda.

**Comment by susheelbhanu** [comment]
Thank you Silas. I'd ideally prefer the conda version, so any idea on a timeline? Alternatively, I can try pulling the new master too. Will keep you posted if I do the latter. 

Thanks a lot!

**Comment by SilasK** [comment]
It should be available tomorrow.

**Comment by susheelbhanu** [comment]
Awesome, thank you very much!

**Comment by susheelbhanu** [comment]
Alright, spoke too soon. Failed this time on a different error. Please see attached log file. I also checked the resources with my jobID, and this is what it looks like:
```
State: FAILED (exit code 1)
Nodes: 2
Cores per node: 12
CPU Utilized: 00:24:58
CPU Efficiency: 4.11% of 10:08:00 core-walltime
Job Wall-clock time: 00:25:20
Memory Utilized: 8.17 GB
Memory Efficiency: 1.29% of 632.81 GB
```

[2019-06-13T105212.987921.snakemake.log](https://github.com/metagenome-atlas/atlas/files/3285167/2019-06-13T105212.987921.snakemake.log)
[calculate_insert_size.log](https://github.com/metagenome-atlas/atlas/files/3285178/calculate_insert_size.log)

**Comment by SilasK** [comment]
Apparently this rule needs more memory.

Option 1: pull latest commit
Option 2: add “simplejob_mem: 20” to the config.yaml file


Note you can add the option -k (keep going) so the pipeline runs even if some (non-central rules fail).

**Comment by susheelbhanu** [comment]
For option 1, was there another commit after the new master pull I did earlier?
I'll try it again and see what happens. 

Thank you!
