### ISSUE TITLE
Coverage of 'contig' genecatalog 

### ISSUE THREAD

**Issue by mdehollander** [metagenome-atlas/atlas#219]
If the source for the genecatalog is set to `contigs` in stead of `genomes` no coverage information is produced. Is there a specific reason why this file is commented out in the `Snakefile`?: https://github.com/metagenome-atlas/atlas/blob/master/atlas/Snakefile#L225

**Comment by SilasK** [comment]
It has to do with my philosophical reflection on how to quantify genes. My intermediate conclusion was that the abundance of a gene should not be quantified by the reads mapping to it and then normalising somehow, rather the abundance of a gene is the sum of the abundance of the genomes containing it.


But I agree if you use the genomecatalog workflow a quantification would be useful. Too get it you can simply run ‘atlas run genomecatlog "Genecatalog/counts/median_coverage.tsv.gz” <options>'

**Comment by mdehollander** [comment]
Yep, indeed. Those are different ways to quantify genes. For cases where binning is not possible, the read mapping approach is very useful. Indeed, specifying the file in question works. Thanks.
