### ISSUE TITLE
Error with database download (linux system)

### ISSUE THREAD

**Issue by mradz19** [metagenome-atlas/atlas#225]
Hi, 

Just wanted to confirm I installed ATLAS correctly. I followed the instructions outlined on github using:

conda create -n atlas -c bioconda -c conda-forge python=3.6 snakemake pandas bbmap=37.78 click=7 ruamel.yaml biopython

git clone https://github.com/metagenome-atlas/atlas.git
cd atlas
pip install --editable .

Everything seemed to install correctly. Am I correct in now assuming that I need to download the databases before running ATLAS with my data?

I tried doing this using the command:

atlas download --db-dir databases/

After a while it failed with the following message:

Executing: snakemake --snakefile /mnt/nfs/home/30041036/atlas/atlas/rules/download.snakefile --jobs 1 --rerun-incomplete --nolock  --use-conda  --conda-prefix /mnt/nfs/home/30041036/atlas/databases/conda_envs --config database_dir='/mnt/nfs/home/30041036/atlas/databases' -- 
Building DAG of jobs...
Creating conda environment atlas/envs/cat.yaml...
Downloading remote packages.
Environment for atlas/envs/cat.yaml created (location: databases/conda_envs/e47c043f)
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Unlimited resources: mem
Job counts:
	count	jobs
	1	download
	3	download_atlas_files
	1	download_cat_db
	1	download_eggNOG_fastas
	3	download_eggNOG_files
	1	unpack_checkm_data
	10

[Mon Aug 19 12:36:56 2019]
localrule download_eggNOG_files:
    output: /mnt/nfs/home/30041036/atlas/databases/EggNOG/eggnog_proteins.dmnd
    jobid: 5
    wildcards: filename=eggnog_proteins.dmnd

Job counts:
	count	jobs
	1	download_eggNOG_files
	1
[Mon Aug 19 12:42:04 2019]
Finished job 5.
1 of 10 steps (10%) done

[Mon Aug 19 12:42:04 2019]
localrule download_atlas_files:
    output: /mnt/nfs/home/30041036/atlas/databases/adapters.fa
    jobid: 1
    wildcards: filename=adapters.fa

Job counts:
	count	jobs
	1	download_atlas_files
	1
[Mon Aug 19 12:42:07 2019]
Finished job 1.
2 of 10 steps (20%) done

[Mon Aug 19 12:42:07 2019]
localrule download_eggNOG_files:
    output: /mnt/nfs/home/30041036/atlas/databases/EggNOG/og2level.tsv
    jobid: 6
    wildcards: filename=og2level.tsv

Job counts:
	count	jobs
	1	download_eggNOG_files
	1
[Mon Aug 19 12:42:11 2019]
Finished job 6.
3 of 10 steps (30%) done

[Mon Aug 19 12:42:11 2019]
localrule download_atlas_files:
    output: /mnt/nfs/home/30041036/atlas/databases/checkm_data_v1.0.9.tar.gz
    jobid: 9
    wildcards: filename=checkm_data_v1.0.9.tar.gz

Job counts:
	count	jobs
	1	download_atlas_files
	1
[Mon Aug 19 12:43:20 2019]
Finished job 9.
4 of 10 steps (40%) done

[Mon Aug 19 12:43:20 2019]
localrule unpack_checkm_data:
    input: /mnt/nfs/home/30041036/atlas/databases/checkm_data_v1.0.9.tar.gz
    output: /mnt/nfs/home/30041036/atlas/databases/checkm/taxon_marker_sets.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/selected_marker_sets.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/pfam/tigrfam2pfam.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/pfam/Pfam-A.hmm.dat, /mnt/nfs/home/30041036/atlas/databases/checkm/img/img_metadata.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms_ssu/SSU_euk.hmm, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms_ssu/SSU_bacteria.hmm, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms_ssu/SSU_archaea.hmm, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms_ssu/createHMMs.py, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms/phylo.hmm.ssi, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms/phylo.hmm, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms/checkm.hmm.ssi, /mnt/nfs/home/30041036/atlas/databases/checkm/hmms/checkm.hmm, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/missing_duplicate_genes_97.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/missing_duplicate_genes_50.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree.taxonomy.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_reduced.refpkg/phylo_modelJqWx6_.json, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_reduced.refpkg/genome_tree.tre, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_reduced.refpkg/genome_tree.log, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_reduced.refpkg/genome_tree.fasta, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_reduced.refpkg/CONTENTS.json, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree.metadata.tsv, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_full.refpkg/phylo_modelEcOyPk.json, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_full.refpkg/genome_tree.tre, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_full.refpkg/genome_tree.log, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_full.refpkg/genome_tree.fasta, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree_full.refpkg/CONTENTS.json, /mnt/nfs/home/30041036/atlas/databases/checkm/genome_tree/genome_tree.derep.txt, /mnt/nfs/home/30041036/atlas/databases/checkm/.dmanifest, /mnt/nfs/home/30041036/atlas/databases/checkm/distributions/td_dist.txt, /mnt/nfs/home/30041036/atlas/databases/checkm/distributions/gc_dist.txt, /mnt/nfs/home/30041036/atlas/databases/checkm/distributions/cd_dist.txt
    jobid: 7

[Mon Aug 19 12:43:35 2019]
Finished job 7.
5 of 10 steps (50%) done

[Mon Aug 19 12:43:35 2019]
localrule download_eggNOG_files:
    output: /mnt/nfs/home/30041036/atlas/databases/EggNOG/eggnog.db
    jobid: 4
    wildcards: filename=eggnog.db

Job counts:
	count	jobs
	1	download_eggNOG_files
	1
[Mon Aug 19 12:58:33 2019]
Finished job 4.
6 of 10 steps (60%) done

[Mon Aug 19 12:58:33 2019]
localrule download_eggNOG_fastas:
    output: /mnt/nfs/home/30041036/atlas/databases/EggNOG/OG_fasta
    jobid: 3

Job counts:
	count	jobs
	1	download_eggNOG_fastas
	1
[Mon Aug 19 15:54:16 2019]
Finished job 3.
7 of 10 steps (70%) done

[Mon Aug 19 15:54:16 2019]
rule download_cat_db:
    output: /mnt/nfs/home/30041036/atlas/databases/CAT/downloaded
    jobid: 8
    resources: mem=100

Activating conda environment: /mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f
# CAT v4.6.

CAT prepare is running, constructing only parts of the database that are missing. Rawr!

WARNING: CAT prepare at this point does not check whether the existing files are OK or corrupted, only if they are there.
WARNING: note that the database and taxonomy files should be downloaded preferably at the same date.
WARNING: preparing the database files may take a couple of hours.

Supplied command: /mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/bin/CAT prepare -d /mnt/nfs/home/30041036/atlas/databases/CAT -t /mnt/nfs/home/30041036/atlas/databases/CAT --existing --nproc 1

Supplied command: /mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/bin/CAT prepare -d /mnt/nfs/home/30041036/atlas/databases/CAT -t /mnt/nfs/home/30041036/atlas/databases/CAT --existing --nproc 1

Taxonomy folder: /mnt/nfs/home/30041036/atlas/databases/CAT/
Database folder: /mnt/nfs/home/30041036/atlas/databases/CAT/
Log file: 2019-08-19.CAT_prepare.existing.log

-----------------

Doing some pre-flight checks first.
[2019-08-19 15:54:36.447597] DIAMOND found: diamond version 0.9.24.
[2019-08-19 15:54:36.449907] Taxonomy folder found.
[2019-08-19 15:54:36.450935] Nodes.dmp and names.dmp will be downloaded to taxonomy folder.
[2019-08-19 15:54:36.451963] Prot.accession2taxid file will be downloaded to taxonomy folder.
[2019-08-19 15:54:36.453315] Database folder found.
[2019-08-19 15:54:36.454328] Nr file will be downloaded to database folder.
[2019-08-19 15:54:36.455375] DIAMOND database will be constructed from the nr file.
[2019-08-19 15:54:36.456407] File fastaid2LCAtaxid will be created.
[2019-08-19 15:54:36.457395] File taxids_with_multiple_offspring will be created.
Ready to fly!

-----------------

[2019-08-19 15:54:36.459703] Downloading and extracting taxonomy files from ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz to /mnt/nfs/home/30041036/atlas/databases/CAT.
[2019-08-19 15:54:57.584800] Download complete!
[2019-08-19 15:54:57.587130] Downloading mapping file from ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz to /mnt/nfs/home/30041036/atlas/databases/CAT/2019-08-19.prot.accession2taxid.gz.
[2019-08-19 15:59:02.674487] Download complete!
[2019-08-19 15:59:02.677062] Downloading nr database from ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz to /mnt/nfs/home/30041036/atlas/databases/CAT/2019-08-19.nr.gz.
[2019-08-19 18:01:20.422321] Download complete!
[2019-08-19 18:01:20.434238] Constructing DIAMOND database /mnt/nfs/home/30041036/atlas/databases/CAT/2019-08-19.nr.dmnd from /mnt/nfs/home/30041036/atlas/databases/CAT/2019-08-19.nr.gz. Please be patient...
[2019-08-20 01:32:10.922752] DIAMOND database constructed!
[2019-08-20 01:32:10.949086] Loading /mnt/nfs/home/30041036/atlas/databases/CAT/2019-08-19.prot.accession2taxid.gz into memory. Please be patient...
Traceback (most recent call last):
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/bin/CAT", line 76, in <module>
    main()
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/bin/CAT", line 56, in main
    prepare.run()
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/share/cat-4.6-0/CAT_pack/prepare.py", line 825, in run
    run_existing(args, date)
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/share/cat-4.6-0/CAT_pack/prepare.py", line 817, in run_existing
    quiet)
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/share/cat-4.6-0/CAT_pack/prepare.py", line 385, in prepare
    quiet)
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/share/cat-4.6-0/CAT_pack/prepare.py", line 239, in make_fastaid2LCAtaxid_file
    quiet)
  File "/mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f/share/cat-4.6-0/CAT_pack/prepare.py", line 226, in import_prot_accession2taxid
    prot_accession2taxid[line[1]] = line[2]
MemoryError
[Tue Aug 20 02:08:16 2019]
Error in rule download_cat_db:
    jobid: 8
    output: /mnt/nfs/home/30041036/atlas/databases/CAT/downloaded
    conda-env: /mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f
    shell:
         CAT prepare -d /mnt/nfs/home/30041036/atlas/databases/CAT -t /mnt/nfs/home/30041036/atlas/databases/CAT --existing --nproc 1
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred while downloading reference databases.
ATLAS databases can be manually downloaded from: https://zenodo.org/record/1134890
eggNOG databases can be manually downloaded from: http://eggnogdb.embl.de/download/emapperdb-4.5.1
CAT databases can be manually downloaded from: https://github.com/dutilh/CAT
Complete log: /mnt/nfs/home/30041036/atlas/.snakemake/log/2019-08-19T123139.960583.snakemake.log
[2019-08-20 02:08 CRITICAL] Command 'snakemake --snakefile /mnt/nfs/home/30041036/atlas/atlas/rules/download.snakefile --jobs 1 --rerun-incomplete --nolock  --use-conda  --conda-prefix /mnt/nfs/home/30041036/atlas/databases/conda_envs --config database_dir='/mnt/nfs/home/30041036/atlas/databases' -- ' returned non-zero exit status 1.

**Comment by SilasK** [comment]
> Everything seemed to install correctly. Am I correct in now assuming that I need to download the databases before running ATLAS with my data?

No, actually you could run atlas directly and all databases are downloaded on the fly. Obviously to be sure everything works downloading before is good. Most databases, are used for the annotation after the QC, assembly and binning has passed. It seems in your case that most databases are downloaded correctly.

The error comes from the CAT database, which is used to annotate the taxonomy of genomes. It builds a diamond database from all NR, this is expected to need 100GB RAM.

Questions:
Do you have enough memory?

It seems also that you only use 1 thread, was is written in your config.yaml file for diamond_threads?

If you have access to a cluster system, I also highly recommend to use a snakelike profile, which allows atlas to schedule jobs on your cluster system, see the docs of atlas.

You have different options:
1.  Postpone or skip using CAT an start using atlas
2. Increase memory and threads and run again.
3. You can do even 1. and 2. On the same time: atlas run binning <options> get’s you running until the binning, before the annotation starts to be needed.
4. Debug CAT outside of Atlas:
The following code should give you the output of the step which broke.

 cd working_dir
 conda activate  /mnt/nfs/home/30041036/atlas/databases/conda_envs/e47c043f
 CAT prepare -d /mnt/nfs/home/30041036/atlas/databases/CAT -t /mnt/nfs/home/30041036/atlas/databases/CAT --existing --nproc <treads>
touch /mnt/nfs/home/30041036/atlas/databases/CAT/downloaded

5. Download the database manually from:  https://github.com/dutilh/CAT
In this case you would need to touch /mnt/nfs/home/30041036/atlas/databases/CAT/downloaded

**Comment by mradz19** [comment]
@SilasK Hi Silas thanks for the response!

I have left downloadiung the databases to allow ATLAS to do it on the fly. I have since run the atlas init command which worked well. However, the atlas run command failed during the QC step. The log file of the failure and termination of the program is below:

java -ea -Xmx8G -cp /scratch_mollison/users/30041036/atlas_trial/databases/conda_envs/83ea54c8/opt/bbmap-37.78/current/ jgi.ReformatReads in1=/scratch_mollison/users/30041036/atlas_trial/data/run1_Flex-HH10_S75_M_R1_001.fastq.gz in2=/scratch_mollison/users/30041036/atlas_trial/data/run1_Flex-HH10_S75_M_R2_001.fastq.gz interleaved=f out1=run1-Flex-HH10-S75-M-001/sequence_quality_control/run1-Flex-HH10-S75-M-001_raw_R1.fastq.gz out2=run1-Flex-HH10-S75-M-001/sequence_quality_control/run1-Flex-HH10-S75-M-001_raw_R2.fastq.gz iupacToN=t touppercase=t qout=33 overwrite=true verifypaired=t addslash=t trimreaddescription=t threads=4 -Xmx8G
Executing jgi.ReformatReads [in1=/scratch_mollison/users/30041036/atlas_trial/data/run1_Flex-HH10_S75_M_R1_001.fastq.gz, in2=/scratch_mollison/users/30041036/atlas_trial/data/run1_Flex-HH10_S75_M_R2_001.fastq.gz, interleaved=f, out1=run1-Flex-HH10-S75-M-001/sequence_quality_control/run1-Flex-HH10-S75-M-001_raw_R1.fastq.gz, out2=run1-Flex-HH10-S75-M-001/sequence_quality_control/run1-Flex-HH10-S75-M-001_raw_R2.fastq.gz, iupacToN=t, touppercase=t, qout=33, overwrite=true, verifypaired=t, addslash=t, trimreaddescription=t, threads=4, -Xmx8G]

Set INTERLEAVED to false
Set threads to 4
Input is being processed as paired
java.lang.AssertionError: 
Error in /scratch_mollison/users/30041036/atlas_trial/data/run1_Flex-HH10_S75_M_R1_001.fastq.gz, line 82528259, with these 4 lines:
@D00775:84:CCYUTANXX:7:2203:13GCTAAAGCCAATTACCATACACTTAGTGACTTAAAACAACACAAATTTATTATCTAAACTCTGGAGATCAGAATTCAAAAACGGGTTTCACTGGGCTAAAATAAAGATGTCATTGGCTGTCTCTT
+
BBBBBBF<FFFB<FFFB<FBFFFFFFFF<<BFFFFBFFFFFFFFFF<FFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB<BFBFFFFFFFFFFFFFFFFFBFFFFFFFFBB
@D00775:84:CCYUTANXX:7:2203:20512:93948 1:N:0:CTCTCTAC+GTAAGGAG

        at stream.FASTQ.quadToRead(FASTQ.java:782)
        at stream.FASTQ.toReadList(FASTQ.java:711)
        at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:109)
        at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:94)
        at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:677)
        at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:653)
java.lang.AssertionError: 
There appear to be different numbers of reads in the paired input files.
The pairing may have been corrupted by an upstream process.  It may be fixable by running repair.sh.
java.lang.AssertionError: 
There appear to be different numbers of reads in the paired input files.
The pairing may have been corrupted by an upstream process.  It may be fixable by running repair.sh.
        at stream.ConcurrentGenericReadInputStream.pair(ConcurrentGenericReadInputStream.java:497)
        at stream.ConcurrentGenericReadInputStream.readLists(ConcurrentGenericReadInputStream.java:362)
        at stream.ConcurrentGenericReadInputStream.run0(ConcurrentGenericReadInputStream.java:206)
        at stream.ConcurrentGenericReadInputStream.run(ConcurrentGenericReadInputStream.java:182)
        at java.base/java.lang.Thread.run(Thread.java:834)

Do you know what is causing this issue?
