### ISSUE TITLE
Optimsing java mem issues

### ISSUE THREAD

**Issue by mradz19** [metagenome-atlas/atlas#229]
I've been trying to run ATLAS on a few samples but I am running into memory issues. I am running ATLAS on a server which should have more than enough RAM. However I get the below error messages:

java -Djava.library.path=/scratch_mollison/users/30041036/atlas_trial/raw_test/databases/conda_envs/46c17b28/opt/bbmap-37.78/jni/ -ea -Xmx20G -Xms20G -cp /scratch_mollison/users/30041036/atlas_trial/raw_test/databases/conda_envs/46c17b28/opt/bbmap-37.78/current/ jgi.BBDukF in1=run1-Flex-HH7-S72-M-001/sequence_quality_control/run1-Flex-HH7-S72-M-001_deduplicated_R1.fastq.gz in2=run1-Flex-HH7-S72-M-001/sequence_quality_control/run1-Flex-HH7-S72-M-001_deduplicated_R2.fastq.gz ref=/scratch_mollison/users/30041036/atlas_trial/raw_test/databases/adapters.fa interleaved=f out=run1-Flex-HH7-S72-M-001/sequence_quality_control/run1-Flex-HH7-S72-M-001_filtered_R1.fastq.gz out2=run1-Flex-HH7-S72-M-001/sequence_quality_control/run1-Flex-HH7-S72-M-001_filtered_R2.fastq.gz outs=run1-Flex-HH7-S72-M-001/sequence_quality_control/run1-Flex-HH7-S72-M-001_filtered_se.fastq.gz stats=run1-Flex-HH7-S72-M-001/logs/run1-Flex-HH7-S72-M-001_quality_filtering_stats.txt overwrite=true qout=33 trd=t hdist=1 k=27 ktrim=r mink=8 trimq=10 qtrim=rl threads=8 minlength=51 maxns=-1 minbasefrequency=0.05 ecco=t prealloc=t -Xmx20G
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000300000000, 21474836480, 0) failed; error='Not enough space' (errno=12)

Is there any way to optimize java memory usage in the config file?

FYI this is the available memory when running atlas:

              total        used        free      shared  buff/cache   available
Mem:         257843       45866       69396        3812      142581      207199
Swap:         16381         478       15903

**Comment by SilasK** [comment]
The error you send me comes from a job which uses 20-30GB of memory.

Atlas runs many jobs simultaneously each with the memory and processors defined in the config file.
The idea behind this is to run each job on a cluster ,but you can also try to run them on the same machine.

I assume that several different jobs are started on the same time which collectively used to much memory.


You can control how many jobs are started by adding the comand line argument

--resources mem={memory of your machine in GB}95%

This tells atlas the limits of your machine and it should not start more jobs than you have memory for.

**Comment by mradz19** [comment]
Hi @SilasK thanks for the help.

When running the following command as a test:

atlas run --resources mem=16

I get the following error:

Error: Invalid value for "[[qc|assembly|binning|genomes|genecatalog|None|all]]": invalid choice: --resources. (choose from qc, assembly, binning, genomes, genecatalog, None, all)

It seems like I cannot call a lot of the snakemake arguments. Do you know how I could fix this?

**Comment by SilasK** [comment]
You have to add one of the run arguments e.g. genomes or all in front of the snakemake arguments.

**Comment by mradz19** [comment]
Thanks for your help @SilasK but I'm still having issues getting the run to start.

Running the command:

atlas run all snakemake --resources mem=64 --keep-going

Is giving the following error:

[2019-09-24 07:41 INFO] Executing: snakemake --snakefile /mnt/nfs/home/30041036/.conda/envs/ATLAS/lib/python3.6/site-packages/atlas/Snakefile --directory /scratch_mollison/users/30041036/atlas_trial/conda_atlas_trial --jobs 44 --rerun-incomplete --configfile '/scratch_mollison/users/30041036/atlas_trial/conda_atlas_trial/config.yaml' --nolock  --use-conda  --conda-prefix /scratch_mollison/users/30041036/atlas_trial/conda_atlas_trial/databases/conda_envs   all  snakemake --resources mem=64 --keep-going 
Building DAG of jobs...
MissingRuleException:
No rule to produce snakemake (if you use input functions make sure that they don't raise unexpected exceptions).
[2019-09-24 07:41 CRITICAL] Command 'snakemake --snakefile /mnt/nfs/home/30041036/.conda/envs/ATLAS/lib/python3.6/site-packages/atlas/Snakefile --directory /scratch_mollison/users/30041036/atlas_trial/conda_atlas_trial --jobs 44 --rerun-incomplete --configfile '/scratch_mollison/users/30041036/atlas_trial/conda_atlas_trial/config.yaml' --nolock  --use-conda  --conda-prefix /scratch_mollison/users/30041036/atlas_trial/conda_atlas_trial/databases/conda_envs   all  snakemake --resources mem=64 --keep-going ' returned non-zero exit status 1.

I'm not sure how to fix this

**Comment by SilasK** [comment]
There is one snakemake to many:
Use: `atlas run all --resources mem=64 --keep-going`


Take also note that I fixed several bugs (see #232 )  in atlas v2.1.5 available from github. I recommend to update before starting the genome workflow.

**Comment by mradz19** [comment]
Thanks @SilasK it's running now. Hopefully it can get all the way through!

**Comment by telatin** [comment]
Hello,
As a comment, trying to run the pipeline on a selection of 3 samples, it crashes at the `bbmerge.sh` step for lack of memory (using a single VM with only 8 cores but 256Gb RAM).

```
Initial:
Ways=31, initialSize=128000, prefilter=f, prealloc=f
Memory: max=28991m, free=28978m, used=13m

Estimated kmer capacity:        540221466
After table allocation:
Memory: max=28991m, free=28895m, used=96m

java.lang.OutOfMemoryError: Java heap space
        at shared.KillSwitch.allocLong2D(KillSwitch.java:234)
        at ukmer.AbstractKmerTableU.allocLong2D(AbstractKmerTableU.java:196)
        at ukmer.HashArrayU1D.resize(HashArrayU1D.java:187)
        at ukmer.HashArrayU1D.incrementAndReturnNumCreated(HashArrayU1D.java:90)
        at ukmer.HashBufferU.dumpBuffer_inner(HashBufferU.java:196)
        at ukmer.HashBufferU.dumpBuffer(HashBufferU.java:168)
        at ukmer.HashBufferU.incrementAndReturnNumCreated(HashBufferU.java:57)
        at ukmer.KmerTableSetU$LoadThread.addKmersToTable(KmerTableSetU.java:574)
        at ukmer.KmerTableSetU$LoadThread.run(KmerTableSetU.java:499)

This program ran out of memory.
Try increasing the -Xmx flag and using tool-specific memory-related parameters.
```

Maybe the k-mer extension could be optional?
I'm trying as suggested to pass `--resources mem=64` now.

**Comment by SilasK** [comment]
There are two levels of resources:
in the config file, you can set the per job mem and threads. 
And then you can tell atlas how much memory and threads there are available on your machine. 
with the command line arguments.


In your case, you will set the command line arguments:
`atlas run assemble --resources mem=256 -j 8`  8 threads, 256 Gb ram.

In the config, you can set
```
config:
java_mem: 100
threads: 4
```
allowing for two jobs be run simultaneously:
or 
```
config:
java_mem: 256
threads: 8
```
If you need more memory. 

You can toggle off the merging or the extension of paired-end reads with the options in the config file. However, the memory issue will re-appear later by the mapping. 

See bbmerge guide for more information of the different parameters. 
```
########################
# Pre-assembly-processing
########################

error_correction_before_assembly : true

# join R1 and R2 at overlap; unjoined reads are still utilized
merge_pairs_before_assembly : true
merging_k: 62
# extend reads while merging to this many nucleotides
merging_extend2: 40
# Iterations are performed until extend2 x iterations
merging_flags: "ecct iterations=5"

```


You don't have a computing cluster available, do you?

**Comment by mradz19** [comment]
Hi @SilasK 

Seems ATLAS still seems to be stalling at some point (with no error messages). It is currently stuck at 21% and has been for about 24 hours now.

Given that the server I am running atlas on generally has about 180GB of RAM available. Can you reccoment what settings would best suit me? In terms of setting the --resources mem, the number of jobs and also configuring the threads/memory in the config file.

I'm not sure if maybe I'm just setting these incorrectly for my environment.

**Comment by SilasK** [comment]
If you passed the bbmerge step you may be in the assembly which might take more than 1 day. So beeing stuck at 21% can be expected. Check the snakemake log file.

If you have to, you can stop atlas (ctr-c) and restart,  It even has the options to restart from checkpoints of the assembly. 

I usually run atlas on a computer cluster where it automatically runs different jobs on different nodes. Snakemake has also options to run on clusters like google cloud. 

Do you have access to a cluster system? what do you mean by
>  the server I am running atlas on generally has about 180GB of RAM available

Now if you just want to run your three samples, you might change the assembler to megahit, which is less resource hungry. 

I would go for 

```
config:
java_mem: 100
threads: 4
assembly_threads: 8
assembly_memory: 256 # will be reduced automatically to 180
```

`atlas run assemble --resources mem=180 -j 8`


If you want to check if atlas works on your system, check the script in `.test/test_assembly.sh``
It downloads tow mini samples and runs them trought the assemlby pipeline. This will however not use the limits of your system.
