### ISSUE TITLE
error in rule get_genome_for_cat:

### ISSUE THREAD

**Issue by tianlei22** [metagenome-atlas/atlas#231]
I have met error in running atlas as below:
![picturemessage_slc4npsi gct](https://user-images.githubusercontent.com/55546015/65251826-9667b880-db2a-11e9-94f4-51bd1eca188d.png)

**Comment by tianlei22** [comment]
How can I cope with it.
Many thanks for anyone who can help me.

**Comment by jmtsuji** [comment]
@tianlei22 @SilasK I can confirm that I am getting the same error. I just moved to using ATLAS `2.1.4` (was using `2.0.6` with success). Here are the results of some debugging I've done so far:

The issue appears to have to do with when the `run` or `script` command in ATLAS rules receive variables from snakemake, e.g., `input[0]`.

Command description in the log file (looks normal):
![get_genomes_for_cat_top](https://user-images.githubusercontent.com/18713012/65294346-51dd1c80-db2c-11e9-9680-af4e379e674e.png)

Error message after running (same as @tianlei22 ):
![output](https://user-images.githubusercontent.com/18713012/65294367-615c6580-db2c-11e9-8b0a-5d41b1460227.png)

However, when I modify the rule `get_genomes_for_cat` in `cat_taxonomy.smk` to have some extra print statements:
![cat_rule](https://user-images.githubusercontent.com/18713012/65294410-7c2eda00-db2c-11e9-87e8-34396d64a3a6.png)

I see this printed along with the error message above:
![output_appended](https://user-images.githubusercontent.com/18713012/65294422-83ee7e80-db2c-11e9-8c58-2a79e71b2dfd.png)

So it seems that although snakemake (before initiating the script) knows that the `input` variable ought to be `genomes/genomes/MAG4.fasta`, the string actually passed to `input[0]` is `genomes/genomes`. This seems to be what causes the 'IsADirectoryError' in the above code.

It looks like `get_genomes_for_cat` is not the only rule affected by this issue. `predict_genes_genomes` (in `genomes.smk`) is also getting an error. The log says that the command run by prodigal was:
```bash
subprocess.CalledProcessError: Command 'set -euo pipefail;  prodigal -i genomes/genomes -o genomes/annotations/genes/genomes.gff  -d genomes/annotations/genes/genomes.fna -a genomes/annotations/genes/genomes.faa -p meta -f gff 2>> logs/genomes/prodigal.log' returned non-zero exit status 18
```

So here also, `genomes/genomes` is being received by `snakemake.input` and passed to the `-i` flag of prodigal. (I also confirmed this by adding a print statement to `predict_genes_of_genomes.py`.

Lastly, both of these rules rely on the helper functions (in `genomes.smk`) `get_genome_dir_` and/or `get_genomes_fasta`. I wondered if these were causing the issue. However, I confirmed (via adding print statements to the code) that `get_genome_dir_` indeed returns `genomes/genomes` and that `get_genomes_fasta` indeed returns a list of all genomes (e.g., `genomes/genomes/MAG4.fasta`).

This debugging is what leads me to wonder if snakemake itself is having an issue passing variables to `run` or `script` commands. I'm using snakemake `5.5.4` now, whereas atlas 2.0.6 used snakemake `5.4.5`, I think.

Hope this helps,
Jackson

**Comment by tianlei22** [comment]
Hi, Jackson,
Many thanks for your comments.
I will try to use atlas 2.0.6.
By the way, how can I install atlas 2.0.6 by conda.
Many thanks.
Lei Tian

**Comment by tianlei22** [comment]
I also have one error rule run_all_checkm_lineage_wf before the rule get_genome_for_cat:
![1568961290(1)](https://user-images.githubusercontent.com/55546015/65304859-46353880-dbb4-11e9-9780-d95850497b59.png)

**Comment by SilasK** [comment]
Thank you for the debugging. 

All these errors are related to the use of snakemake checkpoints, which I used in atlas 2.1. 


I raised an [issue](https://bitbucket.org/snakemake/snakemake/issues/1239/weird-behaviour-of-input-functions-after) on the snakemake repository. Stay tuned.

There are two work arounds:

1. use atlas 2.0.6 
e.g. `conda install metagenome-atlas=2.0.6 ` which doesn't have some of the newest [features](https://github.com/metagenome-atlas/atlas/releases).

2. with atlas 2.1+

Run run `atlas run genomes --omit-from "rename_genomes" ` or just until the error you described.  

After the error, 
rename the genomes directory:

```mv <atlas_working_dir>/genomes/genomes <atlas_working_dir>/genomes/Genomes ```

continue:

```atlas run genomes <options > --config genome_dir=genomes/Genomes```

**Comment by tianlei22** [comment]
That's great, SilasK.
I will try the code as you said.
Many thanks.

**Comment by jmtsuji** [comment]
@SilasK Thanks -- this workaround fixes the error.

**Comment by tianlei22** [comment]
Yes, This workaround fixes the error in rule get_genome_for_cat.
But a new error occurred as below:
![阿里旺旺图片20190921193450](https://user-images.githubusercontent.com/55546015/65372779-e9667a80-dca6-11e9-80aa-54b77f9ee00b.jpg)

**Comment by SilasK** [comment]
@jmtsuji @tianlei22 the new master branch should solve ll your problems. 
No workaround needed, but possible. 

Use the descriptions in the readme to get metagenome-atlas 2.1.6 from the GitHub.
Conda version will come a bit later.
