### ISSUE TITLE
Error in rule cluster_genes

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#238]
Hello @SilasK ,

I've run into an additional error in ATLAS 2.1.4 (running on Ubuntu 18.04 on a local server, not a cluster).

The error occurs at the end of `rule cluster_genes` in the Genecatalog step:
```
rule cluster_genes:
    input: Genecatalog/all_genes/predicted_genes.faa
    output: Genecatalog/all_genes/predicted_genes.db, Genecatalog/all_genes/predicted_genes.db.dbtype, Genecatalog/all_genes/predicted_genes.db.index, Genecatalog/all_genes/predicted_genes.db.lookup, Genecatalog/all_genes/predicted_genes.db_h, Genecatalog/all_genes/predicted_genes.db_h.index, Genecatalog/clustering/protein_clusters.db, Genecatalog/clustering/protein_clusters.db.index
    log: logs/Genecatalog/clustering/cluster_proteins.log
    jobid: 8
    reason: Missing output files: Genecatalog/all_genes/predicted_genes.db.dbtype, Genecatalog/all_genes/predicted_genes.db_h, Genecatalog/all_genes/predicted_genes.db_h.index, Genecatalog/clustering/protein_clusters.db.index, Genecatalog/all_genes/predicted_genes.db.lookup, Genecatalog/all_genes/predicted_genes.db.index, Genecatalog/all_genes/predicted_genes.db, Genecatalog/clustering/protein_clusters.db; Input files updated by another job: Genecatalog/all_genes/predicted_genes.faa
    threads: 20

Activating conda environment: /Data/reference_databases/atlas/2.1.x/conda_envs/d5bf8789

# [ Everything works fine after this until: ]

Program call:
mergeclusters Genecatalog/all_genes/predicted_genes.db Genecatalog/clustering/protein_clusters.db /Analysis/jmtsuji/Documents/02_Active_workfolders/49_190205_DNAseq_ELA1718_analysis/07_atlas_2.1.4_vs1a/atlas_tmp/mmseqs/7298142864430123625/pre_clust /Analysis/jmtsuji/Documents/02_Active_workfolders/49_190205_DNAseq_ELA1718_analysis/07_atlas_2.1.4_vs1a/atlas_tmp/mmseqs/7298142864430123625/clust --threads 20 --compressed 0 -v 3 

List amount 1909375
Clustering step 1...
Clustering step 2...
Writing the results...
Time for merging files: 0h 0m 0s 612ms
Time for processing: 0h 0m 1s 831ms
Waiting at most 5 seconds for missing files.
MissingOutputException in line 62 of /Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.1.4/lib/python3.6/site-packages/atlas/rules/genecatalog.snakefile:
Missing files after 5 seconds:
Genecatalog/clustering/protein_clusters.db
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Removing output files of failed job cluster_genes since they might be corrupted:
Genecatalog/all_genes/predicted_genes.db, Genecatalog/all_genes/predicted_genes.db.dbtype, Genecatalog/all_genes/predicted_genes.db.index, Genecatalog/all_genes/predicted_genes.db.lookup, Genecatalog/all_genes/predicted_genes.db_h, Genecatalog/all_genes/predicted_genes.db_h.index, Genecatalog/clustering/protein_clusters.db.index
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Looking in `Genecatalog/clustering`, I see:

```
protein_clusters.db.0
protein_clusters.db.1
protein_clusters.db.10
protein_clusters.db.11
protein_clusters.db.12
protein_clusters.db.13
protein_clusters.db.14
protein_clusters.db.15
protein_clusters.db.16
protein_clusters.db.17
protein_clusters.db.18
protein_clusters.db.19
protein_clusters.db.2
protein_clusters.db.3
protein_clusters.db.4
protein_clusters.db.5
protein_clusters.db.6
protein_clusters.db.7
protein_clusters.db.8
protein_clusters.db.9
protein_clusters.db.dbtype
```

So my impression is that `rule cluster_genes` finishes properly, but maybe because of the size of the input MAG collection (~750 MAGs!), it splits the clusters DB into multiple subfiles by number. The rule expects `protein_clusters.db` but instead gets `protein_clusters.db.0` and so on.

I tried running the commands of this and the next rule (`rule get_rep_proteins`) manually on the command line. All commands finish without error. Thus, it appears that subsequent commands in mmseqs (in `rule get_rep_proteins`) are able to handle the cluster DB being split across multiple files.

Because of this, I wonder if simply changing the expected output of `rule cluster_genes` to look for files in the format of `protein_clusters.db.[#]` would fix the issue. The only potential complication with this fix is that you do not know how many `protein_clusters.db.[#]` files will be created in advance, or whether a single `protein_clusters.db` file will be created (if there are not many input MAGs).

**Comment by SilasK** [comment]
I will check that.
Could you check your: logs/Genecatalog/clustering/cluster_proteins.log

The output file: Genecatalog/all_genes/predicted_genes.db have to exist for the rule  cluster_genes to finish correctly.

But It might be that there is still a problem with the checkpoints in genome catalog.

**Comment by jmtsuji** [comment]
Thanks -- see attached log file:

[cluster_proteins.log](https://github.com/metagenome-atlas/atlas/files/3645252/cluster_proteins.log)

**Comment by SilasK** [comment]
I could manage to cluster the >4mio genes from 1600 MAGs with no error.

The [suffixes](https://github.com/soedinglab/mmseqs2/wiki#important) may come from too long sequences.

Do you expect to have genes that are longer than 65535 residues?

**Comment by jmtsuji** [comment]
I just checked, and the longest entry in `predicted_genes.faa` is 45057. So long sequences does not seem to be the issue, unless the `.fna` file is also considered.

**Comment by SilasK** [comment]
I run in the same issue and working on it.
