### ISSUE TITLE
CondaValueError: Malformed version string '~': invalid character(s).

### ISSUE THREAD

**Issue by Annie-msi** [metagenome-atlas/atlas#261]
Getting the following error while trying to install metagenome-atlas with conda
Command:
conda install -c bioconda metagenome-atlas
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels

**Comment by SilasK** [comment]
What is the next line of the error log?

Did you forget -c conda-forge
Are you on a linux?

**Comment by Annie-msi** [comment]
Hi,
I used the following, Command:
module load python3
jahan036@ln0003 [~] % source activate Atlas
(Atlas) jahan036@ln0003 [~] % conda install -c bioconda -c conda-forge metagenome-atlas
Solving environment: failed

CondaValueError: Malformed version string '~': invalid character(s).

**Comment by Annie-msi** [comment]
Yes, i am on Linux (MacOS)

**Comment by SilasK** [comment]
> Yes, i am on Linux (MacOS)
You mean you are on unix command line on a mac?

Unfortunately, not all stepd are supported on mac. But you can do the assembly. 

I check the conda install error.

Can you try to install atlas from GitHub see docs.

**Comment by SilasK** [comment]
For the `~` error. I suggest you try this: https://stackoverflow.com/questions/56084960/condavalueerror-malformed-version-string-invalid-characters
