### ISSUE TITLE
GTDB-Tk database error

### ISSUE THREAD

**Issue by jfourquet2** [metagenome-atlas/atlas#277]
Hi,
I wanted to test ATLAS and I have this error with GTDB-Tk database:
```
Downloading the GTDB-Tk database to /work/jfourquet/ATLAS/databases/GTDB-TK...
--2020-02-03 19:06:38--  https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz
Résolution de data.ace.uq.edu.au (data.ace.uq.edu.au)... 130.102.99.4
Connexion vers data.ace.uq.edu.au (data.ace.uq.edu.au)|130.102.99.4|:443...connecté.
requête HTTP transmise, en attente de la réponse...404 Not Found
2020-02-03 19:06:40 ERREUR 404: Not Found.

tar (child): /work/jfourquet/ATLAS/databases/GTDB-TK/gtdbtk_r89_data.tar.gz : open impossible: Aucun fichier ou dossier de ce type
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: impossible de supprimer « /work/jfourquet/ATLAS/databases/GTDB-TK/gtdbtk_r89_data.tar.gz »: Aucun fichier ou dossier de ce type
GTDB-Tk database has been successfully downloaded.
Touching output file /work/jfourquet/ATLAS/databases/GTDB-TK/downloaded_success
```

It is weird because the file `gtdbtk_r89_data.tar.gz` is not downloaded but `GTDB-Tk database has been successfully downloaded`. Do you have an idea how to fix this issue ?
Thanks a lot in advance !

**Comment by SilasK** [comment]
Thank you for highlighting this issue. It seems they made an update of the GTDB-tk.

I have a look at the problem. For now maybe try to download the file https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_data.tar.gz
And unpack it in your folder /work/jfourquet/ATLAS/databases/GTDB-TK

**Comment by SilasK** [comment]
https://github.com/bioconda/bioconda-recipes/pull/20133 should fix the problem. (wait until merged)
But for this, the gtdb conda package needs to be downloaded again. 

This can be done by removing the old one, which should be somewhere at `/work/jfourquet/ATLAS/databases/conda_envs/1a3e86e2`

**Comment by jfourquet2** [comment]
Your solution to download the file and and unpack it in my folder /work/jfourquet/ATLAS/databases/GTDB-TK works thanks !
