### ISSUE TITLE
understanding filter step

### ISSUE THREAD

**Issue by noirot** [metagenome-atlas/atlas#279]
So, the mock data I used (retrieved from another lab) contain reads with quality set to 'I' corresponding to 40 in phred 33 but 9 in phred 66.
In the QC report it is interpreted as 40.

During the filter step most of the reads are discarded, I'm unable to find which command line was launch to understand why all my reads are discarded even if I suspect it.

Here is the report.
[QC_report.html.gz](https://github.com/metagenome-atlas/atlas/files/4171871/QC_report.html.gz)

Could you help me please ?

**Comment by noirot** [comment]
If I set sequence as uppercase in whole fastq file, then no more problem !
Strange ! But make sense with issue #278. 
Maybe you should stop pipeline if fastq are in lower case ?!

**Comment by SilasK** [comment]
I should add the to uppercase to the first step of the qc protocol. Good idea. I never encountered the problem.
Now you have atlas working or is there still a problem?

**Comment by noirot** [comment]
I finally found why the binning didn't finish ! 
"No bins detected with binner metabat in sample mockgut-1M."

Actually it's a bit tricky to found errors in snakemake logs, as you did for finished step (finished_QC, finished_assembly) maybe you should create a file error_binning which contain the reason?
