### ISSUE TITLE
Pooled assembly for mapping of individual metagenomes within a study site

### ISSUE THREAD

**Issue by dscheah** [metagenome-atlas/atlas#283]
Hello! I have a set of metagenomes of samples that were obtained from a subsurface petroleum reservoir. These samples comprise different types (_i.e.,_ formation water, production water, crude oil, and production fluid) but essentially come from the same setting. I am considering pooling these samples, carrying out a pooled assembly, and [mapping the individual metagenomes against the pooled assembly](https://rdcu.be/b1Dig). 

I have two main questions regarding this process: 
1. Would pooling the samples involve combining all the sequenced fasta files into one interleaved file prior to running `atlas init`? 
2. How would we alter the configuration such that binning and annotation can be carried out against the pooled assembly? 

Thanks very much! I appreciate whatever advice that you're able to give me :)

**Comment by SilasK** [comment]
First We completely redesigned atlas since the first version. V2 allows of prediction which are comparable between sample (e.g. the same gene catalog, the same MAGs) in contrast to the first version.
I didn’t implemented the cross-assembly, because It seems to produce more fragmented assemblies.

If you want to improve the assembly, try to use metaspades, which however uses more memory.
What can easily be done, is cross sample binning. Use the coverage in different samples for binning. You can set the BinGroup in the sample table for each group.

But obviously you can merge the samples prior to assembly in atlas e.g the Quality controlled reads.
If you really  want to do them map the individual samples you could do this with a hack:

- Make a new atlas directory and create folders according to the sample names
- Symlink the cross-assembly to each sample directory as sample/sample_contigs.fasta
- copy the sample table from the first atlas run (it should contain the absolute path to the qc reads.
- run atlas binning.

**Comment by dscheah** [comment]
> V2 allows of prediction which are comparable between sample (e.g. the same gene catalog, the same MAGs) in contrast to the first version.

So if I'm understanding correctly, samples that are run concurrently may have different annotations than samples run separately as due to the comparative predictions? I only ask because I ran just one metagenome as a test run to get my head around the Atlas workflow. So I'll probably run that metagenome sample again with my other samples to enable for comparative gene prediction. 

> If you want to improve the assembly, try to use metaspades, which however uses more memory.
What can easily be done, is cross sample binning. Use the coverage in different samples for binning. You can set the BinGroup in the sample table for each group.

I did use metaspades for that first run. For the cross-sample binning, that would be the Cage1 groups that is mentioned in the [example sample table](https://github.com/metagenome-atlas/atlas/files/4199530/Atlas_samples.txt)? Sorry, but I'm not sure what Cage1 refers to in this context. 

I haven't yet decided if it will be worth the effort to do mapping to pooled assembly. Based on my limited understanding, the mapping to pooled assembly would enable MAGs to be created from unique sequenced reads from samples of a unique study site, which would be advantageous if the site is quite niche (mine is a subsurface petroleum reservoir). If you don't mind me asking, what's your opinion on using pooled assembly? Do you think it's necessary given that ATLAS V2 can carry out cross-sample annotations? 

Thanks!

**Comment by SilasK** [comment]
>  samples that are run concurrently may have different annotations than samples run separately as due to the comparative predictions

In the QC, assembly and binning step, each sample is processed individually (with the exception of the reports). 

Genecatalog combines all predicted genes from all samples in the sample table, and the genome workflow replicates the genomes (to species).  

In short the list of `gene001?` and the genomes `MAG001` are not comparable between samples from different atlas runs.

**Comment by SilasK** [comment]
I suggest not to do a cross-assembly. 
What I see in many publications is that they precess each sample individually due to scalability.
Cross- assembly might help to recover low abundant genomes but increases also the risk of chimera. Finally, metaspades doesn't do cross-assembly.  I haven't seen a formal comparison except in the [Drep paper](https://drep.readthedocs.io/en/latest/#)


If you want to do binning based on the coverage profiles from different samples you can use the BinGroup attribute. I work with mice microbiota, so `cage1` would describe all mice rom the same cage. In your case it would be `studysite1`, `studysite2`. All samples where you expect the same species/strain to be pressent. 

>  the mapping to pooled assembly would enable MAGs to be created from unique sequenced reads from samples of a unique study site,

On the contrary, it would allow generating consensus genomes present at different sites.

**Comment by dscheah** [comment]
Hi Silas, thanks very much for the information. I attempted to carry out `atlas run all` on my samples using the BinGroup attribute, but I ran into the problem of [memory constraints](https://github.com/metagenome-atlas/atlas/files/4218160/hs_err_pid28669.log) once more. I'm now looking into installing SLURM cluster execution for my cloud system, but I am wondering if it is possible to carry out the pipeline without having use cluster execution as the installation and set up will take time. I had already set the reduced the threads and memory as follows: 

`threads: 4`
`mem: 25`
`large_mem: 25`
`large_threads: 4`
`assembly_threads: 4`
`assembly_memory: 25`

Thanks again for your help!

**Comment by SilasK** [comment]
I'm sorry metagenomics need a lot of memory. I'm already surprised that you managed to assemble your reads with metaspades. 

Using the binGroup should not require steps that much more memory than before. So if Atlas passed before it should pass with the binGroup as well. 

Here some solutions for your problem:

1.  In your log it stated that the process `Clumpify` didn't had enough memory. clumpify or deduplicate reads is one of the first stepts in the workflow. 
**Why do you need to re-run this step? It shouldn't been the case.**

2. In your log it is written that the memory was set to 40gb.  If you don't have 40g you have to lower it. 

3. The clumpify step needs a lot of memory, but It can be deactivated in the config file: 
`deduplicate: false`. But some of your samples are already processed with deduplicate.

**Comment by SilasK** [comment]
>I'm now looking into installing SLURM cluster execution for my cloud system

If you have a slurm cluster the installation should be done in one command. 

I don't know how your group uses the cluster. But it should be possible that you have access to more memory from time to time, no?

**Comment by dscheah** [comment]
> I'm sorry metagenomics need a lot of memory. I'm already surprised that you managed to assemble your reads with metaspades.

> I don't know how your group uses the cluster. But it should be possible that you have access to more memory from time to time, no?

No need to apologise; unfortunately it is our own fault for not applying for more RAM in the first place. I am the first person in my group to use ATLAS for metagenomics analysis; previous students had used MG-RAST for analysis. Similarly, we had not used a cluster system in our group before, which is why I am currently trying to install it in our cloud. I'm currently the only person fully utilising the cloud, but even so it seems the memory remaining is not enough. 

> Using the binGroup should not require steps that much more memory than before. So if Atlas passed before it should pass with the binGroup as well.

Sorry, I should have been more clear. Previously I had been testing out ATLAS using only one sample out of my set of samples. So I am running all of the steps again on all of my samples this time around. This is likely also why I am facing more memory issues. 

> In your log it is written that the memory was set to 40gb. If you don't have 40g you have to lower it. 

I had initially set it to 40gb memory, but the pipeline didn't work, so I reduced it further to 25gb, but it still did not go through. 

> The clumpify step needs a lot of memory, but It can be deactivated in the config file:
deduplicate: false. But some of your samples are already processed with deduplicate.

Yes, it seemed like there was enough memory to deduplicate a few of the samples but not enough memory for all of them. If I remove the clumpify step, how much do you think PCR-duplicated reads would affect the downstream analysis? I guess it would depend on the type of sample and how it was processed in lab and sequenced?

**Comment by SilasK** [comment]
I know there are Atlas-users that use google cloud or amazon to run their pipelines. It shouldn't be very expensive and snakemake has some good options to deploy pipelines on external clouds. 

the deduplicate step is not the most important, I'd say unless you screwed up your library preparation. Do you use PCR during library preparation? 

I just fear that the heavier samples might not pass later staps. 
Probably assembly you would need to do with megahit.

Do you see multiple steps being executed at the same time? 
Maybe you have to tell atlas about your memory restriction:

If eg. 45gb is the maximum memory on your node:

set mem, largemem .. to 44gb

and add the arguments  `--resources mem=44` to say atlas you don't have more than 44 gb on your cluster. 

If you are the only one on your cluster, there is maybe no need to set up the slurm integration.

**Comment by dscheah** [comment]
Our group is currently uses cloud services from a supercomputing centre based here in Australia, and I did ask for an increase in memory, but unfortunately my request was turned down at this stage without more in-depth consultation.

> the deduplicate step is not the most important, I'd say unless you screwed up your library preparation. Do you use PCR during library preparation?

Yes I did have amplify my samples during library prep. I don't think I messed up the library prep, but the number of cycles I remember were more than 10. 

> and add the arguments --resources mem=44 to say atlas you don't have more than 44 gb on your cluster.

Would this be added to the just the execution parameters section of the `config.yaml` file below? Or to each of the steps in the pipeline? 

`# threads and memory (GB) for most jobs especially from BBtools, which are memory demanding`
`threads: 4`
`mem: 25`

`# threads and memory for jobs needing high amount of memory. e.g GTDB-tk,checkm or assembly`
`large_mem: 25`
`large_threads: 4`
`assembly_threads: 4`
`assembly_memory: 25`

**Comment by SilasK** [comment]
You need to add it only to the atlas command.

`atlas run assembly --resources mem=25 `

Tells atlas, or respective snakelike that your system is limited to 25gb memory. It will therefore schedule no more than 1 job which requests 25gb at the same time.
It is possible that this is the case at the moment.
