### ISSUE TITLE
Problem with missing .tmp files during binning 

### ISSUE THREAD

**Issue by dscheah** [metagenome-atlas/atlas#285]
Hello! I managed to carry out `atlas run all` by limiting `--resources=40`. However, the pipeline shut down during the binning step with the following error messages as output:  

`Activating conda environment:` `/data/work/darrenc/Metagenomes/Enfield/20200217/databases/conda_envs/ef40e9e8`
`Waiting at most 5 seconds for missing files.`
`MissingOutputException in line 158 of /home/darrenc/atlas/atlas/rules/binning.snakefile:`
`Missing files after 5 seconds:`
`DC5-CD27KANXX-GGCTAC-L008/binning/metabat/cluster_attribution.tmp`
`This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait`
`Shutting down, this might take some time.`
`Exiting because a job execution failed. Look above for error message`

Therefore I decided to try `atlas run all` with the appended argument for `--latency-wait`:
`atlas run -w run -c run/config.yaml all --resources mem=40 --latency-wait 30`

I am running this code now to see how it goes but wanted to check if you had other thoughts before then.

Thanks!

**Comment by dscheah** [comment]
I increased the wait time to `--latency-wait=1200` but am still getting the same error. It seems that the `cluster_attribution.tmp` file is not being produced in time for the pipeline to proceed, perhaps due to the limited resource memory. For now I am incrementally increasing the wait time to see if the .tmp file can be produced in time.

**Comment by SilasK** [comment]
Great you managed to run atlas. Does it one job at a time?

Most probably the binning for metabat didn’t yeald any bins for this sample. Therefore the file is not produced and the pipeline stops.
Check the log file of the rule producing this file.

**Comment by dscheah** [comment]
Yes, that sample is actually a metagenome of a drilling fluid that is supposedly sterile, so it would make sense that no bins are produced. Can a script be amended such that the pipeline will keep running even if no bins are produced? 

Thanks!

**Comment by SilasK** [comment]
The simplest way is to remove it from the sample table.
It should already be included in the QC and assembly reports so you can check how much reads there are.

But you want to quantify whatever might be there? I see if I can make a script.

**Comment by dscheah** [comment]
All right, I removed the samples with zero to very little bins, and the pipeline now seems to be running well again. I think the QC and assembly reports will give enough reason and information to exclude those samples from further downstream analysis, so I don't think you need to make a script unless you wish to. 

Thanks very much!
