### ISSUE TITLE
Error in rule cluster_genes - (TestRun with atlas example files)

### ISSUE THREAD

**Issue by srikanthkris** [metagenome-atlas/atlas#292]
Hi, 
I am trying to set up atlas in our server. 
I performed a testrun with example files provided, i am running into an error (pasted below), i am not able to fix it. Can you please help. i edited the config file and tried linclust and mmseqs , both result in the same error.  

**Command used:
atlas run --working-dir testrun**

The log file is attached.  
[cluster_proteins.log](https://github.com/metagenome-atlas/atlas/files/4385049/cluster_proteins.log)

Error in rule cluster_genes:
    jobid: 107
    output: Genecatalog/all_genes/predicted_genes, Genecatalog/clustering/mmseqs
    log: logs/Genecatalog/clustering/cluster_proteins.log (check log file(s) for error message)
    conda-env: /460_info3/project/kris/Coccidiosis/3.Test/databases/conda_envs/5b9455a9
    shell:
        
                mkdir -p /tmp/mmseqs Genecatalog/all_genes/predicted_genes Genecatalog/clustering/mmseqs 2>> logs/Genecatalog/clustering/cluster_proteins.log
                mmseqs createdb Genecatalog/all_genes/predicted_genes.faa Genecatalog/all_genes/predicted_genes/inputdb &> logs/Genecatalog/clustering/cluster_proteins.log

                mmseqs cluster -c 0.9                 --min-seq-id 0.95                  --threads 48 Genecatalog/all_genes/predicted_genes/inputdb Genecatalog/clustering/mmseqs/clusterdb /tmp/mmseqs  &>>  logs/Genecatalog/clustering/cluster_proteins.log

                rm -fr  /tmp/mmseqs 2>> logs/Genecatalog/clustering/cluster_proteins.log
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by SilasK** [comment]
Sorry for responding so late. Strange error.

Did you change the the cluster mode in the config file from `linclust` `cluster` in the config file? 

Or did you run atlas multiple times? 

```
genecatalog:
  source: contigs               # [contigs, genomes] Predict genes from all contigs or only from the representative genomes
  clustermethod: linclust  
```


Could you test to delete the folders 
Genecatalog/all_genes/predicted_genes Genecatalog/clustering/mmseqs /tmp/mmseqs

and try again?

**Comment by srikanthkris** [comment]
Hi,
 Thanks for your comment. Sorry for the late response. I did a lot of things (don't really remember what all I did) but couldn't get the test files to work. Then I just used our own sequence file, and that worked. Great pipeline. Thanks for it.
