### ISSUE TITLE
CondaError: Downloaded bytes did not match Content-Length

### ISSUE THREAD

**Issue by ganiatgithub** [metagenome-atlas/atlas#293]
Hi,

Thanks for the cool program, it's my first try and I got the following error at the beginning:

 `CondaMultiError: CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/conda-forge/linux-64/openblas-0.2.20-8.tar.bz2
  target_path: /home/Staff/uqgni1/miniconda2/pkgs/openblas-0.2.20-8.tar.bz2
  Content-Length: 17776191
  downloaded bytes: 2405420

CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/conda-forge/linux-64/graphviz-2.38.0-hf68f40c_1011.tar.bz2
  target_path: /home/Staff/uqgni1/miniconda2/pkgs/graphviz-2.38.0-hf68f40c_1011.tar.bz2
  Content-Length: 10223914
  downloaded bytes: 6050884

  File "/home/Staff/uqgni1/miniconda2/envs/atlasenv/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 320, in create
[2020-04-25 16:13 CRITICAL] Command 'snakemake --snakefile /home/Staff/uqgni1/miniconda2/envs/atlasenv/lib/python3.6/site-packages/atlas/Snakefile --directory /home/Staff/uqgni1/05_metag-commamox_Min_atlas/working-dir --jobs 16 --rerun-incomplete --configfile '/home/Staff/uqgni1/05_metag-commamox_Min_atlas/working-dir/config.yaml' --nolock  --profile cluster --use-conda --conda-prefix /home/Staff/uqgni1/tools/atlas-db/conda_envs   all   ' returned non-zero exit status 1.`

Any tips on troubleshooting?

**Comment by SilasK** [comment]
Hey Gani, 
Welcome among the metagenome-atlas users. 

The error arises during the download of conda packages. 
(atlas automatically downloads dependencies using conda).



As it's an error with the underlying conda package manager,  I recommend to google the error `CondaMultiError: CondaError: Downloaded bytes did not match Content-Length` 

Maybe it comes from a glitch in the internet connection, in this case just rerun you'd help.

For debugging you can, 
`conda install openblas=0.2.20` gives you the same error.

Finally, to make sure atlas downloaded all packages, and you can start running it, you can run atlas with the argument `--conda-create-envs-only`

I hope this helps you to search for your answer.

**Comment by ganiatgithub** [comment]
Hey,

Thanks for the tips. I simply run the same command again, and it gave me a similar error for another package:
`CondaMultiError: CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/bioconda/noarch/das_tool-1.1.1-r36_3.tar.bz2
  target_path: /home/Staff/uqgni1/miniconda2/pkgs/das_tool-1.1.1-r36_3.tar.bz2
  Content-Length: 44370467
  downloaded bytes: 16519996`

I ran individual conda install for all these three packages.

- For `conda install das_tool=1.1.1`, I got:

`The following packages will be DOWNGRADED:
  pyyaml                               5.3.1-py36h8c4c3a4_0 --> 5.1.2-py36h516909a_0
  yaml                                     0.2.4-h516909a_0 --> 0.1.7-h14c3975_1001
Proceed ([y]/n)? y
Downloading and Extracting Packages
pyyaml-5.1.2         | 184 KB    | ############################################################################################################# | 100%
das_tool-1.1.1       | 42.3 MB   | ############################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::r-base-3.6.3-h316533a_2'.
Rolling back transaction: done
CondaMultiError: [Errno 12] Cannot allocate memory
()`

- for `conda install graphviz=2.38.0` I got:

`Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed
CondaMemoryError: The conda process ran out of memory. Increase system memory and/or try again.`

- But `openblas=0.2.20` was installed successfully. 

I didn't really get how to use `--conda-create-envs-only`. When I do `atlas run -w ./working-dir -j 16 --profile cluster --conda-create-envs-only`
I got `Invalid value for'[[qc|assembly|binning|genomes|genecatalog|None|all]]': invalid choice: --conda-create-envs-only. (choose from qc, assembly, binning, genomes, genecatalog, None, all)`

Not sure if it helps, but I also did a dry run, it seems to work:

`Job counts:
	count	jobs
	1	add_eggNOG_header
	1	align
	2	align_reads_to_MAGs
	2	align_reads_to_final_contigs
	2	align_reads_to_prefilter_contigs
	1	all
	1	all_contigs2bins
	1	all_gtdb_trees
	1	all_prodigal
	2	apply_quality_filter
	1	assembly
	2	assembly_one_sample
	2	bam_2_sam_MAGs
	2	bam_2_sam_binning
	2	bam_2_sam_contigs
	1	binning
	1	build_assembly_report
	1	build_bin_report
	1	build_db_genomes
	1	build_decontamination_db
	1	build_qc_report
	4	calculate_contigs_stats
	2	calculate_read_length_hist
	1	classify
	1	cluster_genes
	1	combine_bined_coverages_MAGs
	1	combine_coverages_MAGs
	1	combine_egg_nogg_annotations
	1	combine_read_counts
	1	combine_read_length_stats
	1	concat_genes
	4	convert_sam_to_bam
	2	deduplicate_reads
	2	download_atlas_files
	1	download_checkm_data
	1	download_gtdb
	2	error_correction
	2	filter_by_coverage
	1	filter_genes
	2	finalize_contigs
	2	finalize_sample_qc
	1	first_dereplication
	1	gene2genome
	1	gene_subsets
	1	genecatalog
	1	genomes
	1	get_all_bins
	2	get_bins
	2	get_contig_coverage_from_bb
	2	get_contigs_from_gene_names
	2	get_maxbin_cluster_attribution
	2	get_metabat_depth_file
	1	get_quality_for_dRep_from_checkm
	10	get_read_stats
	1	get_rep_proteins
	4	get_unique_bin_ids
	4	get_unique_cluster_attribution
	1	identify
	2	init_pre_assembly_processing
	1	initialize_checkm
	2	initialize_qc
	2	maxbin
	1	merge_checkm
	2	metabat
	2	pileup
	2	pileup_MAGs
	2	pileup_for_binning
	2	pileup_prefilter
	2	predict_genes
	1	qc
	2	qcreads
	2	rename_contigs
	1	rename_gene_catalog
	1	rename_genomes
	1	rename_protein_catalog
	2	rename_spades_output
	1	run_all_checkm_lineage_wf
	2	run_checkm_lineage_wf
	2	run_checkm_tree_qa
	2	run_das_tool
	2	run_decontamination
	2	run_spades
	1	second_dereplication
	2	write_read_counts
	143
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.`

It this a network thing?  I'm also not sure how to address the memory issue in conda installation. Any tips? Many thanks!!

**Comment by SilasK** [comment]
The command would be:

`atlas run all -w ./working-dir --conda-create-envs-only`

As you get the memory error, are you working on a node with very low memory?

Would it be possible to run itself in a cluster job, so you can submit the atlas command to a cluster and it will run on a cluster node with a bit more memory.

You could start with the command:
`atlas run assembly -w ./working-dir --conda-create-envs-only`
This installs only packages needed for assembly. If this works you can 1. run atlas without the -conda-create-envs-only in one job and 2. Run the above command to install all packages.

What cluster system are you working with?
