### ISSUE TITLE
Bin naming collision error when using DASTool

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#296]
Hi @SilasK 

I found a possible bin naming collision error when using ATLAS. I think this is related to #290 and is a bit complex in its origin but easy to fix. However, it might be a major issue because it causes some bins to be lost during the dereplication step of the genomes module.

In `binning.snakefile`, the rule get_unique_cluster_attribution is meant to provide all bins from a given sample with a unique ID to avoid bin naming collisions:

```
rule get_unique_cluster_attribution:
    input:
        "{sample}/binning/{binner}/cluster_attribution.tmp"
    output:
        "{sample}/binning/{binner}/cluster_attribution.tsv"
    run:
        import pandas as pd
        import numpy as np


        d= pd.read_csv(input[0],index_col=0, squeeze=True, header=None,sep='\t')

        assert type(d) == pd.Series, "expect the input to be a two column file: {}".format(input[0])

        old_cluster_ids = list(d.unique())
        if 0 in old_cluster_ids:
            old_cluster_ids.remove(0)

        map_cluster_ids = dict(zip(old_cluster_ids,
                                   utils.gen_names_for_range(
                                       len(old_cluster_ids),
                                        prefix="{sample}_{binner}_".format(**wildcards)
                                         )
                                   ))

        new_d= d.map(map_cluster_ids)
        new_d.dropna(inplace=True)
        if new_d.shape[0]==0:
            logger.error(f"No bins detected with binner {wildcards.binner} in sample {wildcards.sample}.\n"
                          "This will break the continuationof the pipeline. "
                          "Check what happened. Maybe the the assembly is too small. "
                          "You can either remove the binner (for all samples) from the config.yaml file or the sample from the sample.tsv"
                            )
            raise Exception("No bins detected with binner {wildcards.binner} in sample {wildcards.sample}.")
        new_d.to_csv(output[0],sep='\t')
```

This used to (e.g., in an old conda env of ATLAS 2.0.6 I have) generate an output file like this (e.g., for metabat):
```
Cfx3_2018_0     Cfx3_2018_metabat_01
Cfx3_2018_1     Cfx3_2018_metabat_01
Cfx3_2018_2     Cfx3_2018_metabat_02
Cfx3_2018_3     Cfx3_2018_metabat_01
Cfx3_2018_4     Cfx3_2018_metabat_03
...
```

However, as of pandas 0.24.0 (January 25, 2019), the default settings of Series.to_csv() changed so that by default `header = True` (instead of `header = False`). See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.to_csv.html This affects the last line of the above rule: `new_d.to_csv(output[0],sep='\t')`

So now, in all conda envs made for ATLAS that use pandas 0.24.0, the output `cluster_attribution.tsv` file looks like this (note the added header):
```
0       1
Cfx3_2018_0     Cfx3_2018_metabat_01
Cfx3_2018_1     Cfx3_2018_metabat_01
Cfx3_2018_2     Cfx3_2018_metabat_02
Cfx3_2018_3     Cfx3_2018_metabat_01
Cfx3_2018_4     Cfx3_2018_metabat_03
...
```

This causes an error in DASTool. DASTool thinks that the header is a real data row and that `0` is the expected name of a bin. Because no bin is found, DASTool then renames all samples itself and throws a warning like this:
```
...
WARNING: Some scaffold names ofCfx3_2018/binning/DASTool/metabat.scaffolds2bindo not match assembly headers:
0
WARNING: Some scaffold names ofCfx3_2018/binning/DASTool/maxbin.scaffolds2bindo not match assembly headers:
0
WARNING: non-unique bin-IDs found
creating unique bin-IDs 
...
```

As a result, the final `cluster_attribution.tsv` file made by DASTool looks like:
```
Cfx3_2018_5     metabat.005
Cfx3_2018_12    metabat.005
Cfx3_2018_17    metabat.005
Cfx3_2018_28    metabat.005
Cfx3_2018_32    metabat.005
Cfx3_2018_33    metabat.005
```

Note how the sample name prefix (Cfx3_2018_) was erased.The bins are also named like this. They are no longer unique between different samples:
```bash
jmtsuji@Mellea:.../Cfx3_2018/binning/DASTool$ ls bins

maxbin.002.fasta  maxbin.003.fasta  maxbin.004.fasta  maxbin.009.fasta  metabat.004.fasta  metabat.005.fasta  metabat.010.fasta  metabat.011.fasta  metabat.013.fasta
```

Thus, when performing the `genomes` step of ATLAS, bins with colliding names between samples are silently erased and not run through the dereplication step!

I just discovered this issue this past week when trying to look at two enrichment culture metagenomes in detail. Some bins are randomly erased during dereplication.

I completely fixed the error with a simple code change -- I explicitly set `header = False` in the final line of `rule get_unique_cluster_attribution`:
```
new_d.to_csv(output[0],sep='\t',header=False)
```

Now, the `cluster_attribution` file made by DASTool looks as expected:
```
Cfx3_2018_5     Cfx3_2018_metabat_04
Cfx3_2018_12    Cfx3_2018_metabat_04
Cfx3_2018_17    Cfx3_2018_metabat_04
Cfx3_2018_28    Cfx3_2018_metabat_04
Cfx3_2018_32    Cfx3_2018_metabat_04
Cfx3_2018_33    Cfx3_2018_metabat_04
```
And bin filenames are normal again:
```bash
jmtsuji@Mellea:.../Cfx3_2018/binning/DASTool$ ls bins

Cfx3_2018_maxbin_01_sub.fasta  Cfx3_2018_maxbin_03.fasta  Cfx3_2018_metabat_03.fasta  Cfx3_2018_metabat_09_sub.fasta  Cfx3_2018_metabat_12_sub.fasta                           Cfx3_2018_maxbin_02.fasta      Cfx3_2018_maxbin_08.fasta  Cfx3_2018_metabat_04.fasta  Cfx3_2018_metabat_10.fasta
```

This seems like a critical bug that might affect all ATLAS versions since pandas upgraded in around Jan. 2019. Maybe DASTool should throw an error instead of a warning in situations like this.

Happy to follow up if helpful or to make a PR.

**Comment by SilasK** [comment]
Hmm, I should have listened to the warnings thrown by pandas.
Yes, this is a critical bug. Could you make a PR. 

I think we also should keep using pandas<0.24

**Comment by jmtsuji** [comment]
@SilasK I've made a simple PR that addresses `rule get_unique_cluster_attribution` specifically. I agree that setting pandas = 0.23 (or pandas < 0.24) temporarily is wise to ensure that other areas of the ATLAS code are not also affected by the new pandas version. However, some additional testing might be needed to ensure that restricting the pandas version doesn't break other conda envs.
