### ISSUE TITLE
error in build_qc_report

### ISSUE THREAD

**Issue by will-rowe** [metagenome-atlas/atlas#297]
Hi,

Thanks for the great pipeline. I installed via conda and am following the docs. I keep hitting a process error:

```
[Thu Jun 25 09:37:52 2020]
Error in rule build_qc_report:
    jobid: 91
    output: reports/QC_report.html
    log: logs/QC/report.log (check log file(s) for error message)
    conda-env: /cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca

RuleException:
CalledProcessError in line 624 of /home/ubuntu/miniconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/qc.snakefile:
Command 'source /home/ubuntu/miniconda3/bin/activate '/cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca'; set -euo pipefail;  python /data/.snakemake/scripts/tmp9e57ejj6.qc_report.py' returned non-zero exit status 1.
  File "/home/ubuntu/miniconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/qc.snakefile", line 624, in __rule_build_qc_report
  File "/home/ubuntu/miniconda3/envs/atlasenv/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing temporary output file Genecatalog/representatives_of_clusters.fasta.
```

Also in the traceback:

```
  File "/data/.snakemake/scripts/tmp9e57ejj6.qc_report.py", line 7, in <module>
    from cufflinks import iplot
  File "/cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca/lib/python3.6/site-packages/cufflinks/__init__.py", line 14, in <module>
    from . import tools
  File "/cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca/lib/python3.6/site-packages/cufflinks/tools.py", line 1, in <module>
    import plotly.plotly as py
  File "/cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca/lib/python3.6/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca/lib/python3.6/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError:
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.
```

**Comment by SilasK** [comment]
Hey @will-rowe 

The error is caused because I used an old plotly version in the reports.

you should run
```
conda activate /cephfs/lomanlabz/will/matlas/conda_envs/ab23aeca
conda install -y plotly=2.2.2

conda deactivate
```
I will also fix this in the master branch. 

If it doesn't work, you can always run: 
`atlas run all --keep-going`

And atlas will finish without the reports.

**Comment by will-rowe** [comment]
Perfect - thanks for the quick response. Makes sense. The pipeline is chugging along again now.

**Comment by MalbertRogers** [comment]
Hi, 

Is it possible that it only works with a specific version of plotly? I have tried with newer version via:

`pip install plotly==4.0`

I still got the same error message. Now trying version 2.2.2 as we speak.

Furthermore, this is an error in the QC module, right? So, one would not expect to get this error when the flag `--skip-qc` is added, but for some reason I kept getting this error.

**Comment by SilasK** [comment]
Yes, I wrote the report script some time ago. For me it worked with plotly 2.2.2, and that's what is installed with the newest version of atlas since 85372e7 . In theory you don't need to change the plotly version if you have an up to data atlas. Tell me if I'm wrong. 


You can always use the `--keep-going` flag. 

The QC report is also produced even when qc reads are inputted to get a report of how many reads you have.
