### ISSUE TITLE
add_eggNOG_header issue

### ISSUE THREAD

**Issue by baptisteavot** [metagenome-atlas/atlas#300]
<img width="751" alt="issues" src="https://user-images.githubusercontent.com/54843422/87133343-78c13680-c297-11ea-8cf4-a1774cfeb57f.PNG">

Pandas seems to be expecting a certain number of columns and therefore everything else shuts down, do you have any suggestions on how to overcome that issue?

**Comment by SilasK** [comment]
I think I know where this come from:

The eggNOG annotation is build in different subsets. If one of this subset tables didn’t finished correctly, e.g. one missing real.
The next one get added and we have 43 fields.

The simples is to delete the input file 'Genecatalog/annotations/eggNog.emapper.annotations’ and to restart atlas. This should re-run all eggNOG annotation again.

Do you think it’s feasible?

**Comment by baptisteavot** [comment]
I am doing that right now, I will let you know if it fixes it, but thanks for your quick response!

**Comment by baptisteavot** [comment]
It seems to have worked out, thank you
