### ISSUE TITLE
gtdb downloading Error 404

### ISSUE THREAD

**Issue by JesseKerkvliet** [metagenome-atlas/atlas#305]
Hi,
The download_gtdb rule raises a 404 Error when trying to download https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_data.tar.gz

Is there a way to fix this?

```
Downloading the GTDB-Tk database to [path]
--2020-07-22 10:06:03--  https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_data.tar.gz
Resolving data.ace.uq.edu.au (data.ace.uq.edu.au)... 130.102.99.4
Connecting to data.ace.uq.edu.au (data.ace.uq.edu.au)|130.102.99.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-22 10:06:04 ERROR 404: Not Found.
```

**Comment by SilasK** [comment]
Hmm. GDB made new release which creates this bug.

**Comment by SilasK** [comment]
@JesseKerkvliet Let's try a simple hack:

Do you know where you installed atlas? 
Can you make [this](https://github.com/metagenome-atlas/atlas/pull/306/files) change in your installed atlas and see if it solves the problem?

**Comment by JesseKerkvliet** [comment]
Updating the version got the database to download. Looks solved to me, but I'll check back when the download is finished, to be sure.

**Comment by SilasK** [comment]
I keep the issue open until I merge #306

**Comment by SilasK** [comment]
Thank you for the issue.

**Comment by SohaibNQ** [comment]
Hi SilasK,
I recently installed the Atlas on ubuntu and tried to run it on example data and got the following error. Can you please help me regarding this. Although, software did  a lot of attempts before giving up. Thanks
gtdbtk_data.tar.gz                                           48%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                                        ]  15.82G  66.1KB/s    in 97s
2021-02-13 23:12:20 (440 KB/s) - Connection closed at byte 16983228416. Giving up.

[Sat Feb 13 23:12:21 2021]
Error in rule download_gtdb:
    jobid: 120
    output: /mnt/c/test/databases/GTDB_V05/downloaded_success
    conda-env: /mnt/c/test/databases/conda_envs/52bcf200
    shell:
        GTDBTK_DATA_PATH=/mnt/c/test/databases/GTDB_V05 ;  download-db.sh ;
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by jmtsuji** [comment]
@SohaibNQ A couple quick questions:

- It looks like you might be running ATLAS on Windows Subsystem for Linux (WSL) based on the paths in your log statement -- is that correct?

- Also, can you check how much disk space you have on the C drive (`/mnt/c`)? I want to rule out whether you are low on disk space.

- When `wget` re-tried downloading the GTDB data files, did it get to the same byte each time before failing, or did it reach a different byte?

- If you retry the same step of ATLAS a few hours later, do you run into the same issue? I wonder if your issue might be an intermittent internet connection issue or an intermittent issue on the GTDB-Tk data hosting end at https://data.gtdb.ecogenomic.org/releases/release95/95.0/auxillary_files/

For others involved in debugging, note that the code that is failing is `download-db.sh` ([link here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gtdbtk/download-db.sh)), which is part of the conda install for GTDB-Tk.

**Comment by SohaibNQ** [comment]
1. Yes, You are right, I am using windows subsystem for Linux( WSL).
2. I have more than 300 gb available space in C drive.
3. I failled at different bytes, initially at 7 percent, then many times until it reached to 48 percent.
4. Can I download the gtdb-tk in computer and then paste it in the database folder.

**Comment by jmtsuji** [comment]
@SohaibNQ Hmm, given that you are failing at different bytes each time, it could be a connectivity issue to the GTDB database file. Yes, you can follow the code at download-db.sh (above) manually and then move the output into the `/mnt/c/test/databases/GTDB_V05` folder. You'll also need to generate an empty file called `downloaded_success` in the `/mnt/c/test/databases/GTDB_V05` folder to tell ATLAS it can move on to the next step in the pipeline.

**Comment by SohaibNQ** [comment]
Thank you, I will try this now.

**Comment by SilasK** [comment]
> 1. Yes, You are right, I am using windows subsystem for Linux( WSL).

Hey @SohaibNQ, 
I'm not sure if I made this clear that you need not only a large disk space for to download the dbs but also quite some RAM (200-250GB). I'm not sure if your Windows subsystem has this resources. 
Usually, we run atlas on a Cluster or Cloud. 
Especially the steps for GTDB and also checkM use ~GB ram. 


However, you are absolutely fine to test atlas on your subsystem for windows. E.g. you can to the [second part of the Tutorial](https://github.com/metagenome-atlas/Tutorial#install-and-run-atlas-with-three-commands) on your computer.

For the Tutorial, I suggest you to [download this folder](https://github.com/metagenome-atlas/Tryitout/tree/main/profile) in your working directory and name it `Demo`.  During the tutorial you will run `atlas run all --profile Demo`  The demo profile limits usage to 2GB/ 2 cpus and will not download the GTDB database (because GTDB will probably be too much for your computer)

```
#also get get example data
wget https://zenodo.org/record/3992790/files/test_reads.tar.gz
tar -xzf test_reads.tar.gz
```

**Comment by marcomeola** [comment]
I run atlas from docker pull metagenomeatlas/atlas and run in following issue with gtdbtk
```
Error in rule align:
    jobid: 173
    output: genomes/taxonomy/gtdb/align
    log: logs/taxonomy/gtdbtk/align.txt, genomes/taxonomy/gtdb/gtdbtk.log (check log file(s) for error message)
    conda-env: /databases/conda_envs/27b2c927
    shell:
        GTDBTK_DATA_PATH=/databases/GTDB-TK ;  gtdbtk align --identify_dir genomes/taxonomy/gtdb --out_dir genomes/taxonomy/gtdb --cpus 8 &> logs/taxonomy/gtdbtk/align.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Job failed, going on with independent jobs.```

I run gtdbtk outside the atlas snakemake. Seems as if the gtdbtk should be updated to 1.5.0 and the database accordingly.

**Comment by SilasK** [comment]
The docker container is not automatically updated, but you can update the atlas version within the docker to v.2.5 witch has the new GTDBtk.
