### ISSUE TITLE
recurrent error during eggNOG homology search

### ISSUE THREAD

**Issue by baptisteavot** [metagenome-atlas/atlas#307]
I am coming up against a recurring issues with the eggNOG_homology_search rule (following the eggNOG_annotation which is much faster now thanks to the dev/shm tip, but the error might actually be due to this change). For only a few subsets, emapper returns the following:

`Traceback (most recent call last):
  File "/data/users/bavot/data/conda_envs/0141129c/bin/emapper.py", line 1213, in <module>
    main(args)
  File "/data/users/bavot/data/conda_envs/0141129c/bin/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/data/users/bavot/data/conda_envs/0141129c/bin/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/data/users/bavot/data/conda_envs/0141129c/bin/diamond blastp -d /data/users/bavot/data/EggNOGV2/eggnog_proteins.dmnd -q /data/users/bavot/he_out/Genecatalog/subsets/genes/subset1.faa --more-sensitive --threads 8 -e 0.001000 -o /data/users/bavot/he_out/.snakemake/shadow/tmpp4cwurkg/emappertmp_dmdn_Kv78Wp/87cfa7f0bf834d068ef144c4980da06e --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status -4
`
Which is the log for the following rule:
`Error in rule eggNOG_homology_search:
    jobid: 5416
    output: Genecatalog/subsets/genes/subset1.emapper.seed_orthologs
    log: Genecatalog/subsets/genes/logs/subset1/eggNOG_homology_search_diamond.log (check log file(s) for error message)
    conda-env: /data/users/bavot/data/conda_envs/0141129c
    shell:

        emapper.py -m diamond --no_annot --no_file_comments             --data_dir /data/users/bavot/data/EggNOGV2 --cpu 8 -i Genecatalog/subsets/genes/subset1.faa             -o Genecatalog/subsets/genes/subset1 --override 2> Genecatalog/subsets/genes/logs/subset1/eggNOG_homology_search_diamond.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 5872466

Error executing rule eggNOG_homology_search on cluster (jobid: 5416, external: 5872466, jobscript: /data/users/bavot/he_out/.snakemake/tmp.4ujl8yyf/snakejob.eggNOG_homology_search.5416.sh). For error details see the cluster log and the log files of the involved rule(s).
`

**Comment by SilasK** [comment]
First, eggNOG_homology_search is prior to eggNOG_annotation.

So the error is: `diamond returned non-zero exit status -4`
but I haven't found an explication what exit status -4 means. 

Do you have a cluster output, A file with the id `5872466` in it? Usually it's placed somewhere in the working directory. 

Can you check if the folder `/data/users/bavot/he_out/.snakemake/shadow/tmpp4cwurkg/emappertmp_dmdn_Kv78Wp/` still exists and may have additional info? 


Usually what can be a problem with on a cluster that the memory get exceeded, do you have a way to give the eggNOG_homology_search rule more memory?

**Comment by baptisteavot** [comment]
Yes, it has solved the issue, thank you!
