### ISSUE TITLE
cloud computing plans?

### ISSUE THREAD

**Issue by KJLambert** [metagenome-atlas/atlas#308]
Hi!
Are there any plans/ ongoing efforts to figure out how to run this in a cloud framework? 
If not, any other thoughts/decisions?

Cheers,
KL

**Comment by SilasK** [comment]
So I don't have yet access to a cloud computing system and my focus was to run it on clusters. 

In theory, the underlying snakemake should allow [easy submission to a could system](https://snakemake.readthedocs.io/en/stable/executing/cloud.html) and I would be happy to help you to set it up. 

In practice, all command-line arguments to snakemake can be appended to the atlas command.

**Comment by SilasK** [comment]
There is even a tutorial how to do it: https://snakemake.readthedocs.io/en/stable/executor_tutorial/tutorial.html#executor-tutorial
