### ISSUE TITLE
Meaning of values into stats/read_counts.tsv

### ISSUE THREAD

**Issue by jfourquet2** [metagenome-atlas/atlas#310]
Hi,
I am trying to understand the file stats/read_counts.tsv generated with ATLAS.
For each sample, there are 5 lines.

```
first	raw	26780934.0	8034280200	26780934.0	8034280200	0	0	2020-04-02-19:03:52
first	deduplicated	26761774.0	8028532200	26761774.0	8028532200	0	0	2020-04-02-19:14:55
first	filtered	26751251.0	7970092026	26447856.0	7924643834	303395	45448192	2020-04-02-19:20:22
first	clean	26447856.0	7924643834	26447856.0	7924643834	0	0	2020-04-02-19:24:23
first	QC	26751251.0	7970092026	26447856.0	7924643834	303395	45448192	2020-04-02-19:24:23
```
What is the difference between the line "clean" and the line "QC" ?
Thanks in advance for your answer !

**Comment by SilasK** [comment]
You don’t get a QC report, like this https://metagenome-atlas.readthedocs.io/en/latest/_static/QC_report.html , do you


In the filter step I remove R-ribosomal reads and in the QC step they are aded again for meta genome reads, for metatranscriptomic reads they would be left out.

**Comment by jfourquet2** [comment]
Yes, I get a QC report but I don't understand well the number of reads in the file stats/read_counts.tsv or in this report. I am in the case of a metagenomic study. so after the filter step there is the same number of reads than after the QC step if I understand well ? What are the reads after "clean" step ?

**Comment by SilasK** [comment]
StepOutput
raw The input reads specified in the configuration
deduplicated Counts after (optional) deduplication step
filtered Low quality reads have been removed
clean Contaminants removed
QC Passing reads -- for metagenomic samples, 16S reads are returned to
sequence pool


Contaminants are what you pot in the config file. by default it is PhiX
adapters ara also filtered out


Your numbers for the first sample look good. Do you have any issues with
other samples

**Comment by jfourquet2** [comment]
Thanks a lot for your answer ! I haven't any issue with the results for my others samples but I tried to better understand each line of the table.
