### ISSUE TITLE
error in genome step

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#311]
I run each step separately and in the "atlas run genomes -w working_dir" step I got this message in the pre-dereplication step... 

raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.

I can go on to the genecatalog step but many of the genomes/  folders are not created... only all_bins, pre-dereplication,  check-m and quality.csv are there...

any ideas?

**Comment by SilasK** [comment]
One guess would be that you don’t any or only a view bins with too low quality. Check the genomes/quality.csv file.
Could this be expected? What type of meta genome do you have, e.g. soil?

In the meantime, yes go ahead with the gene catalog step. You might also check out t#276

**Comment by botellaflotante** [comment]
> One guess would be that you don’t any or only a view bins with too low quality. Check the genomes/quality.csv file. 
thanks! the quality.csv says 
genome,completeness,contamination,strain heterogeneity
SRR6436017_maxbin_3.fasta,89.59,1.94,33.33

Could this be expected? What type of meta genome do you have, e.g. soil? 
yes, rhizosphere, so may be too much diversity..
In the meantime, yes go ahead with the gene catalog step. You might also check out t#276

**Comment by botellaflotante** [comment]
So, I have tried with different soil and rhizosphere samples but I am still getting the same error 

in the quality.csv I get
"genome,completeness,contamination,strain heterogeneity
SRR6797247_metabat_06.fasta,53.0,1.42,30.0"

With the two soil samples I didn't find the error and I found 4 MAGs in the genomes folder

Do you know any way I could solve this issue??
Is there any way to change parameters to get more MAGs (although they are less complete)??

**Comment by SilasK** [comment]
In the quality.csv file, you have only one genome or are there more lines? 
If there is only one genome this would obviously lead to the error of an empty distance matrix. 


I assume you are using DASTool. them You can change the following parameters:

<pre>
DASTool:
  search_engine: 'diamond'
  score_threshold: <b>0.0</b>              #Score threshold until selection algorithm will keep selecting bins [0..1].

genome_dereplication:
  ANI: 0.95
  overlap: 0.6
  opt_parameters: ""
  filter:
      noFilter: <b>true</b>
      length: 5000
      completeness: 50
      contamination: 10
</pre>

**Comment by botellaflotante** [comment]
Thanks a lot, it worked fine. Now I am trying to map MAG genes annotations to genecatalog. In the example there is a orf2gene.tsv file which is very usefull for this, but I cannot find this file in my datasets (in genomes/annotation....). Is there ant other way to link MAGs with genecatalog?

**Comment by jmtsuji** [comment]
@botellaflotante `orf2gene.tsv` is typically stored in `Genecatalog/clustering` -- do you find it there?

Jackson

**Comment by botellaflotante** [comment]
I meant gene2genome, which I cannot fiind..

**Comment by jmtsuji** [comment]
@botellaflotante Ah, so sorry, I mis-read your comment -- this is why I should not try to help with Github issues while finalizing my PhD thesis...

Yes, `gene2genome.tsv` appears to be a new feature in ATLAS. I had not been aware of this file previously and have used `orf2gene.tsv` to accomplish the same type of gene-to-MAG linkage.

Probably best to wait for Silas to comment here.

**Comment by SilasK** [comment]
No, @jmtsuji your help is very much appreciated.

@botellaflotante to get the gene2genome.tsv

You need to run specifically 'atlas run all' with atlas  V>2.3 I believe.

Do also have a look at https://github.com/metagenome-atlas/atlas_analyze. Which is a small extension that uses this file and calculates the abundance of KO and Cazy per genome and per sample.

**Comment by botellaflotante** [comment]
OK, thanks @SilasK , to "run all" was then the issue. I had trouble with atlas run all but running each instead worked with my dataset (don't know why), so I guess that I won't have gene2genome file. So, @jmtsuji you did linked the eggNog annotations to each MAG? which other file did you use besides orf2gene? Thanks a lot both!

**Comment by SilasK** [comment]
If you want to try to combine the annotations yourselves in the orf2gene.tsv ou get 



Orf Name | Gene name
-- | --
<Contig>_<gene nr> | Gene001

Where the contigs you can map to your bins (genomes) and the gene name to the annotations in the eggNOg. Obvisoulsy this is already implemented in Atlas. So I don't know if it wold be easier to make Atlas run. 
You sid: 

> Thanks a lot, it worked fine. Now I am trying to map MAG genes annotations to genecatalog. In the example there is a gene2genome.tsv file which is very usefull for this, but I cannot find this file in my datasets (in genomes/annotation....). Is there ant other way to link MAGs with genecatalog?

You managed to get the bins (although with lower quality). Did the dereplication step pass? What happens if you run `atlas run all ` ?

**Comment by botellaflotante** [comment]
Ok, I am checking now. If it works... I am doing a filtering before the assembly (to filter plant sequences). But then I cannot run thee run all in these cases, right? because I would start from _QC_fastq files...

**Comment by SilasK** [comment]
I think I don't understand your comment. 

Atlas has different steps. `atlas run all`  runs all steps [QC, assembly,binning, genomes,genecatalog, and all] . The genomes step dereplicates MAGs and the genecatalog creates the annotations in the 'all' step combines annotation and genomes and creates e.g. genes2genomes.tsv.




If you want that atlas removes host reads for you [here](https://metagenome-atlas.readthedocs.io/en/latest/usage/configuration.html#remove-reads-from-host) is how you do it.

If you have already reads with host removed and some basic quality filtering. You can start directly with `atlas init --skip-qc` and give your qc reads..

**Comment by botellaflotante** [comment]
OK, so I should simply run "atlas run all" after genecatalog in all samples... this generates genes2genomes.tsv and any other file??

thanks a lot

**Comment by SilasK** [comment]
Yes If you managed to run ‘atlas run gene catalog’ and ‘atlas run genomes’ then is simply run ‘atlas run all’ and you have the gene2genomes.tsv.

Is there a way I should explain it differently in the docs to make this more clearer?

Als have a look at the atlas_analyze extension.

**Comment by botellaflotante** [comment]
both "atlas run all" options is what confused me (I didn't realize I had to run it even if I had done each step separately).
now that I run it I get this error. What I had done previously was to remove the SRR6797243/assembly/K* files to get some extra space, is it possible that is related?
[2020-09-21T173124.555790.snakemake.log](https://github.com/metagenome-atlas/atlas/files/5256523/2020-09-21T173124.555790.snakemake.log)

**Comment by SilasK** [comment]
I think the fundamental problem in your case is that you have only two or three genomes, hence the problem of rooting the tree. See also #203 

How many genomes do you have in the folder `genomes/genomes` ?

If you are fine with only the 2 MAGs you can run `atlas run all --keep-going` and you should get the gene2genome.tsv. 

If you expect more MAGs, may be the [changes](https://github.com/metagenome-atlas/atlas/issues/311#issuecomment-688090157) didn't progressed trough the whole pipeline. You can remove or rename the `genome` folder and restart with `atlas run genomes`

**Comment by botellaflotante** [comment]
ok, this is weird. Before I had only 4 MAGs, but now (and after this error) I have 33 MAGs... same happened to my other soil sample...

**Comment by SilasK** [comment]
check the ` logs/genomes/tree/root_tree_gtdbtk.ar122.log` 

Did you get the genes2genomes.tsv with `atlas run all --keep-going`

>ok, this is weird. Before I had only 4 MAGs, but now (and after this error) I have 33 MAGs... same happened to my other soil sample...

- This is probably due to the changes [here](https://github.com/metagenome-atlas/atlas/issues/311#issuecomment-688090157). check the checkM output. 

- You have two samples, are they in the same atlas-project e.g. in the same asmples.tsv?

**Comment by botellaflotante** [comment]
- logs/genomes/tree/root_tree_gtdbtk.ar122.log are empty in these cases
- I got the genes2genomes in all cases despite the error I sent you (so maybe that's it and I can work with that?)
- When you sent me those changes in the config files  (for genomes steps), what I did was to manually delete all folders related to Genecatalog and genomes, and re run everything from genomes steps... because If I didn't remove those folders it would throw me another error
- I treat all samples separately because they are from different biological replicates (two samples of soil, and 12 from plants). Many of the plant samples worked fine now with the atlas run all final step, and didn't throw me any error   
thanks for the help!

**Comment by SilasK** [comment]
Great, we've made it! 👍 

> When you sent me those changes in the config files (for genomes steps), what I did was to 
Perfect!

> I got the genes2genomes in all cases despite the error I sent you (so maybe that's it and I can work with that?)
Yes, you can work with that. The error in root tree is not related to it. 

> I treat all samples separately because they are from different biological replicates (two samples of soil, and 12 from plants). 

My Idea behind Atlas was to combine samples from the same project. In this case MAGs predicted in one sample can be quantified in another also genes are unified and anotate only once. This makes things more comparable. 
But you can do as you want.

> logs/genomes/tree/root_tree_gtdbtk.ar122.log are empty in these cases
Probalby the bacteria tree worked an only the archea tree had to view genomes. I should correct this. 


I think I cole the issue. Don't hesitate to continue writing here if yo have some related questions.

**Comment by botellaflotante** [comment]
- so, sorry I came back here, would you recommend then to treat all samples in a same run, although they are from different biological replicates? so, If I also ant to compare against different soils, would you also merge those in the same project? so that ANI threshold would decide which is the same MAG across samples?

- if I have already filtered by quality (so --skip-qc) should I give only R1 and R2 in a same folder? what about se reads? can they be included also in the samples.tsv file?
what I did was to do the qc step, then filter host and now I also have se-reads left....

**Comment by SilasK** [comment]
1. If you want to *compare* samples, yes I would include them in the same Atlas project. unified gene catalog and MAGs make things easier, isn't it? E.g. if the MAG cannot be annotated to the species it can still be identified as the same in all samples. You can change the Drep -ANI for dereplication if you want. 

2. I think you can create the sample.tsv yourself with all three files. If there are no Raw_seq the QC is skipped or only the QC report is created. 

  | Reads_QC_R1 | Reads_QC_R2 | Reads_QC_se | BinGroup
-- | -- | -- | -- | --
ERR675518 | ERR675518/sequence_quality_control/ERR675518_QC_R1.fastq.gz | ERR675518/sequence_quality_control/ERR675518_QC_R2.fastq.gz | ERR675518/sequence_quality_control/ERR675518_QC_se.fastq.gz | ERR675518

**Comment by botellaflotante** [comment]
yes, I get this 
CyclicGraphException in line 64 of /home/jose/miniconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/qc.snakefile:
Cyclic dependency on rule initialize_qc.
maybe I need some other file besides each sample*/sequence_quality_control/QC_samples* right?

**Comment by SilasK** [comment]
Try to add the raw files as well and fill in values for the Bin group e.g. the sample name. 
Do a dry-run before.
