### ISSUE TITLE
DAS tool cannot be installed

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#313]
Error discovered by @sofie7

![image](https://user-images.githubusercontent.com/7523034/91538270-df69e480-e917-11ea-9c78-44f318a28b81.png)

**Comment by SilasK** [comment]
I hope d0bdba1 solve this. 

@sofie7 could you try to change this directly in your file and try again.

The file is something like `miniconda3/envs/atlas206/lib/python3.6/site-packages/atlas/envs/DASTool.yaml``
If it works I make a new conda release.

**Comment by Sofie8** [comment]
Yes this solved it!
