### ISSUE TITLE
Issue with MaxBin

### ISSUE THREAD

**Issue by baptisteavot** [metagenome-atlas/atlas#314]
Hello,
I've been struggling in the last few weeks with a recurrent issue when the pipeline tries to run MaxBin... I can't understand where it is coming from as it does not occur for every sample...
It seems to be when maxbin tries to load libraries, so the error message differs, it can be:
Cannot run FragGeneScan. Please indicate the file directory in 'setting' file.
Cannot run Bowtie2. Please indicate the file directory in 'setting' file.
Cannot run IDBA-UD. Please indicate the file directory in 'setting' file.
Cannot run HMMER3. Please indicate the file directory in 'setting' file.
Depending on the samples and on the runs. It does not seem to be correlated with the sample type (size or other) since if I restart the pipeline it can work for a sample for which I did not work in a previous run.
I excluded the eventuality where it might be due to a specific node on which the job is run because it does work from time to time on cluster nodes where it failed before...
I tried installing maxbin2 manually but it does not seem to be changing anything.
Would you have any suggestions to fix this?

**Comment by SilasK** [comment]
I encountered this issue from time to time. Sometimes it was related that the maxbin would not find any bins and then tried to do a re-assembly (Idba). I asked for help see above. 

Can you try to exclude the possibility that the sample is too poor to find bins. 

E.g. check the maxbin log and how many bins metabat found. 

A quick fix could also be to set `final_binner: metabat`

**Comment by baptisteavot** [comment]
I got around 50 bins for most samples that failed a first time and for which a second attempt resulted in MaxBin working properly

**Comment by SilasK** [comment]
I heard from others that rerunning mqxbin works often. You can require this using the comman line argument '--restart-times 4' runing a job 4 times before failing.

**Comment by botellaflotante** [comment]
I found these type of errors in some samples, maybe putting only metabat as final binner will fix it? I tried this and run binning -R again but did not work. should I remove all the binning-related files first? or there is another way to force this step?
[2020-12-18T184840.268742.snakemake.log](https://github.com/metagenome-atlas/atlas/files/5717377/2020-12-18T184840.268742.snakemake.log)
[DASTool.log](https://github.com/metagenome-atlas/atlas/files/5717378/DASTool.log)

Thanks again

**Comment by SilasK** [comment]
@botellaflotante You can decrease the min threshold for DAS Tool. so this step passes. The bins will be filtered at the Dereplication step. 

```
DASTool:
  search_engine: 'diamond'
  score_threshold: 0.0   
```

**Comment by botellaflotante** [comment]
thanks, yes. I want to run it again with 
DASTool:
  search_engine: 'diamond'
  score_threshold: 0.0   
but if I use "atlas run binning" again on a project that's finished, it will rerun some steps from assembly and qc..
for example, "run_spades"... or "qc". I am not sure If I should remove some files... modify anything... I also tried with "atlas run binning -R run_das_tool" but the same happens..
21      filter_by_coverage
        21      finalize_contigs
        21      finalize_sample_qc
        21      get_bins
        21      get_contig_coverage_from_bb
        21      get_contigs_from_gene_names
        21      get_maxbin_cluster_attribution
        21      get_metabat_depth_file
        105     get_read_stats
        42      get_unique_bin_ids
        42      get_unique_cluster_attribution
        21      init_pre_assembly_processing
        21      initialize_qc
        21      maxbin
        1       merge_checkm
        21      merge_pairs
        21      metabat
        21      passtrough_se_merged
        21      pileup
        21      pileup_for_binning
        21      pileup_prefilter
        21      predict_genes
        1       qc
        21      qcreads
        21      rename_contigs
        21      rename_spades_output
        21      run_checkm_lineage_wf
        21      run_checkm_tree_qa
        21      run_das_tool
        21      run_decontamination
        21      run_spades
        21      write_read_counts
        1018

**Comment by SilasK** [comment]
This is a bit anoying. Maybe some of the db were re-installed? 

Try to tell atlas that the assembly is finished by the command. 
`touch "finished_assembly" `
You might need to run this before each execution. 


You can ask atlas why he tries to rerun everything with the command line argument `--reason --dry-run`

**Comment by botellaflotante** [comment]
I think this was because I changed the folder's name at some point, and then renamed it again to its original name, something happened there...
now what I do is to save the genomes folder with each parameter settings and run_all after removing binning folders... also changing samples file if I need to run again a subset of samples...

**Comment by SilasK** [comment]
If you rename the folders this can change the timestamp. And snakemake restarts the steps. 
If you are sure what you are doing, you can overwrite the timestamp with the `--touch` argument. Check also the docs.

I hope this problem got more or less solved.
