### ISSUE TITLE
Conda install on Linux hangs while solving environment

### ISSUE THREAD

**Issue by mdjlynch** [metagenome-atlas/atlas#318]
Hello.

Installing through conda on Linux (Ubuntu 18.04 LTS) hangs when solving environment:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ /
```

Version 2.2.1 is installed and working correctly. I am trying to install the most recent version before starting another analysis. Any help/insight is appreciated. Thanks.

**Comment by jmtsuji** [comment]
@mdjlynch I had a similar issue, but I was then able to get ATLAS to install using mamba: https://github.com/mamba-org/mamba

I wonder if something about the environment requirements needs to be cleaned up for conda to solve properly.

Note that at least one of the dependency environments of ATLAS also hung in the same way when ATLAS was setting up the run. I had to generate that environment manually using mamba as well.
