### ISSUE TITLE
error nº100

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#321]
I have some reads which I cannot process because of this error...any clue??? Thanks!!!

RuleException:
CalledProcessError in line 624 of /home/miniconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/qc.snakefile:
Command 'source /home/miniconda3/bin/activate '/home/databases/conda_envs/b1550ec1'; set -euo pipefail;  python 
/Bulgarelli/wdir_bulga/.snakemake/scripts/tmp5jqta9_0.qc_report.py' returned non-zero exit status 1.

[2020-10-05T211954.665427.snakemake.log](https://github.com/metagenome-atlas/atlas/files/5330090/2020-10-05T211954.665427.snakemake.log)

**Comment by SilasK** [comment]
It seems the only error is in the error report

Have a look at logs/QC/report.log

If you don’t need the report you can safely continue with providing -k as command line argument.

**Comment by botellaflotante** [comment]
thanks a lot. yes, that was actually the case with many samples... not sure why it would do that. the size of the reads files is OK, so no reads missing

**Comment by SilasK** [comment]
Is there something in the reports/QC_report.html ?

**Comment by botellaflotante** [comment]
Nope, reports/ is empty... and sequence_quality_control/ has all QC reads...

**Comment by SilasK** [comment]
Sorry, Is there something in the logs/QC/report.log ?

**Comment by botellaflotante** [comment]
in logs/QC/ there are these files

decontamination.log  init.log            read_stats
deduplicate.log      quality_filter.log  stats

but there is no report.log....

thanks!
