### ISSUE TITLE
MAGs genes missing in eggNog.tsv

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#322]
In MAG1 from the testrun (and in most of my data) I found that there's always lots of genes to map in MAGs from gene2genome that have no annotation in eggNog.tsv. Frequently they are hypothetical proteins, but sometimes this type of things (Blp family class II bacteriocin [Streptococcus salivarius]). Is it because they simply don't have an eggNog annotation so they miss this information, or maybe there is something wrong?
Thanks

**Comment by SilasK** [comment]
No, most of the genes of most genomes genome are not annotatable.

The eggNOGmapper uses DIAMOND to map to the gene representatives. This is fast but may not be the most sensitive approach.
One could try to annotate the gene catalog as a whole or the genes of a genome with other tools e.g. MMseqs of KO or uniprot.

Do you look for something specific?

**Comment by botellaflotante** [comment]
ok! thanks, I just wanted to check that this was something expected (that eggNog annotations are not complete for all genes) or if there was something else wrong. Thanks a lot again
