### ISSUE TITLE
maxbin binning fails - Can't locate LWP/Simple.pm in @INC

### ISSUE THREAD

**Issue by skembel** [metagenome-atlas/atlas#328]
Hi,
Running a fresh conda install of metagenome atlas 2.4.3 on CentOS Linux 7, when trying to do binning maxbin keeps crashing with the following error:

```
Activating conda environment: /bio/kembel_s/atlas-databases/conda_envs/b9530507
Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /home/kembel_s/perl5/lib/perl5/x86_64-linux-thread-multi /home/kembel_s/perl5/lib/perl5 /bio/kembel_s/atlas-databases/conda_envs/b9530507/lib/site_perl/5.30.3/x86_64-linux-thread-multi /bio/kembel_s/atlas-databases/conda_envs/b9530507/lib/site_perl/5.30.3 /bio/kembel_s/atlas-databases/conda_envs/b9530507/lib/5.30.3/x86_64-linux-thread-multi /bio/kembel_s/atlas-databases/conda_envs/b9530507/lib/5.30.3 .) at /bio/kembel_s/atlas-databases/conda_envs/b9530507/bin/run_MaxBin.pl line 5.
BEGIN failed--compilation aborted at /bio/kembel_s/atlas-databases/conda_envs/b9530507/bin/run_MaxBin.pl line 5.
[Tue Oct 27 10:20:42 2020]
Error in rule maxbin:
    jobid: 45
    output: r1t1-2018AT-NP/binning/maxbin/intermediate_files, r1t1-2018AT-NP/binning/maxbin/r1t1-2018AT-NP.summary, r1t1-2018AT-NP/binning/maxbin/r1t1-2018AT-NP.marker, r1t1-2018AT-NP/binning/maxbin/r1t1-2018AT-NP.marker_of_each_bin.tar.gz, r1t1-2018AT-NP/binning/maxbin/r1t1-2018AT-NP.log
    log: r1t1-2018AT-NP/logs/binning/maxbin.log (check log file(s) for error message)
    conda-env: /bio/kembel_s/atlas-databases/conda_envs/b9530507
    shell:
```
I have installed both the LWP::Simple module and maxbin2 using conda.
[2020-10-27T101506.554610.snakemake.log](https://github.com/metagenome-atlas/atlas/files/5445948/2020-10-27T101506.554610.snakemake.log)

Sorry if this is a stupid question but I'm at a loss as to how to get maxbin to see the LWP::Simple dependency. Binning works fine with metabat and DASTool.

**Comment by SilasK** [comment]
Hey @skembel ,

I also encountered this issue on a docker container and thought it might be related to that as no one has pointed this out to me until now. 

It is something with the [conda environment of maxbin](https://github.com/bioconda/bioconda-recipes/issues/24707) and I don't know how to fix it. But I will try my best. 
To my experience metabat is the better binner of both but obviously, it would be great to have both.

**Comment by jmtsuji** [comment]
@SilasK @skembel I believe I also ran into the same error with ATLAS v2.4.3. I overcame it by manually re-installing the environment using mamba: https://github.com/mamba-org/mamba

This was a bit tricky to do -- I found the .yaml file in the ATLAS database directory (in the `conda_envs` subdirectory) matching the maxbin yaml file, and I then noted the unique identifier code of the yaml file. (In my case, the file was called `0882e803.yaml`.) I then deleted the corresponding `0882e803` conda env and made that env manually using mamba.

I'll try to put up the code needed for this later this evening (eastern time).

This is a temporary workaround, but it implies that conda has some issue with solving the maxbin environment.

**Comment by SilasK** [comment]
Thank you @jmtsuji , I knew I could count on you. 

The code should be something like:

```
rm -r {atlas_db_dir}/conda_envs/0882e803
conda install -y mamba
#creae new env
mamba create -p {atlas_db_dir}/conda_envs/0882e803 -f {atlas_db_dir}/conda_envs/0882e803.yaml
```


I wonder what is the difference.

@skembel could I ask you for the favour to run the following command **before** and after the fix. and send me the two files. So I might find a permanent solution.

```
conda activate {atlas_db_dir}/conda_envs/0882e803
conda list > maxbin_env_{before|after}.txt
conda deactivate
```

**Comment by skembel** [comment]
Hi, thanks for this!
Here is the environment file created before the fix: 
[maxbin_env_before.txt](https://github.com/metagenome-atlas/atlas/files/5448307/maxbin_env_before.txt)

Trying the code suggested above by @SilasK I get an error when creating the new environment:
```
# the following commands work
$rm -r /bio/kembel_s/atlas-databases/conda_envs/b9530507
$conda install -y mamba
# but unable to create the new environment
$mamba create -p /bio/kembel_s/atlas-databases/conda_envs/b9530507 --file /bio/kembel_s/atlas-databases/conda_envs/b9530507.yaml

CondaValueError: could not parse '- conda-forge' in: /bio/kembel_s/atlas-databases/conda_envs/b9530507.yaml
```

Here is the contents of the yaml file:
```
$cat /bio/kembel_s/atlas-databases/conda_envs/b9530507.yaml
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - maxbin2 =2.2.*
```

**Comment by skembel** [comment]
I realized the command above to create the new environment should actually be
`mamba env create -p /bio/kembel_s/atlas-databases/conda_envs/b9530507 --file /bio/kembel_s/atlas-databases/conda_envs/b9530507.yaml`
... but I am getting a SSL connection error from mamba when I try to run this command. I have to do some troubleshooting to see why mamba is unable to connect to the usual channels. I'm able to use mamba to install/update but can't execute the `mamba env create` command for some reason.

**Comment by skembel** [comment]
A follow up - I have been unable to get mamba to remake the environment. I am getting a SSL connection error which is unique to the `mamba env create` command, I am otherwise able to use mamba to install and update environments and packages.

I did try to force remake the maxbin2 environment using 'conda env create -p /bio/kembel_s/atlas-databases/conda_envs/b9530507 --file /bio/kembel_s/atlas-databases/conda_envs/b9530507.yaml', which oddly leads to some differences in versions of packages compared to the original, but still fails with the same error about LWP::Simple not found: [maxbin_env_after.txt](https://github.com/metagenome-atlas/atlas/files/5452175/maxbin_env_after.txt)

I tried a fresh install of atlas using mamba instead of conda and it has the same issue with maxbin failing due to the missing LWP::Simple dependency.

**Comment by SilasK** [comment]
atlas resp. snakemake uses still conda to install environments. 

If the mamba command works otherwise. You could run:

`mamba create -p /bio/kembel_s/atlas-databases/conda_envs/b9530507 maxbin2=2.2 `

As this is the whole content of the b9530507.yam
Assuming you have added the conda-forge and bioconda channels to the conda config. 

@jmtsuji If you could get us the list of packages in your worrking maxbin environment, this would be cool.

**Comment by SilasK** [comment]
Does the file `/bio/kembel_s/atlas-databases/conda_envs/b9530507.yaml` really exist. I just wondering if it is the same has on all computers.

**Comment by jmtsuji** [comment]
Hi @SilasK and @skembel ,

Sorry for the delay getting back to you. The following command works for me (just tested on my server, which runs on Ubuntu 18.04 LTS):
```bash
# For me, the maxbin2 environment file is 0882e803.yaml
# I run this command in the same folder as where the YAML file is located
mamba env create -p ${PWD}/0882e803 --file=0882e803.yaml
```

The manual installation method recommended by @SilasK above (slightly modified) also works:
```bash
mamba create -p ${PWD}/0882e803 -c conda-forge -c bioconda maxbin2=2.2.*
```

The following command variants do not work:
```bash
mamba create -p ${PWD}/0882e803 --file 0882e803.yaml
# Get: CondaValueError: could not parse '- conda-forge' in: 0882e803.yaml
```

Does this help?

**Comment by skembel** [comment]
Hi, thanks for this. Unfortunately I am unable to verify the solutions you provided @jmtsuji as I'm getting SSL connection errors with mamba whenever I try to create an environment. No idea what is going on with that and my limited troubleshooting attempts so far have not worked.
I will do a reinstall of the atlas environment, mamba, and test the fix you mentioned but I won't be able to get to this until some jobs running on our server are done.

**Comment by gruningerrj** [comment]
So is this a bug? You closed my post about the issue but I have no idea if this is the same error as above. I don't really follow what I am supposed to do here.

**Comment by SilasK** [comment]
@SilasK  I don't think reinstalling atlas would help. But you can raise an issue at the mamba github about your SSL problem;

I think the problem lies in the version of perl which should be 5.26
so 
`conda create -p {path to maxbin env with hash} -c conda-forge -c bioconda maxbin2=2.2.* perl=5.26`

should also work, but I will test it tomorrow.

**Comment by SilasK** [comment]
Ok I tested my solution and it works. The bioconda package should be updated soon, so this fix is no longer needed. Thankyou all for your bug reports and your help.

**Comment by jmtsuji** [comment]
Glad to hear that the conda install will be updated!

**Comment by skembel** [comment]
Hi, thanks again to both of you, @SilasK your solution works for me as well.

**Comment by gruningerrj** [comment]
Hi Silas,
The test data ran and I am testing some of my real data now. Thanks for your help. I also was looking at your tutorial on https://metagenome-atlas.readthedocs.io/en/latest/usage/output.html and found that the link in “See in Atlas example<https://github.com/metagenome-atlas/Atlas_example> how to analyze these abundances” is dead.

I’m sure you are really busy but adding a bit on what files to look at and steps for the downstream analysis would be very useful to newbies.

Best,
Rob

**Comment by SilasK** [comment]
Sorry, my response wasn't sent. I'm glad that the solution worked for you. For the Tutorial. Look at the (closed) issue. There I put the link to my wok in progress.
