### ISSUE TITLE
run time estimation

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#331]
Hi, I am running ATLAS in a 36 CPU 500 GB machine, and if I run each sample separately it would take more or less 50 hs (sample= 35 M reads). Is it expected as a run time or should I do something different? Thanks!

**Comment by SilasK** [comment]
It can take very long. But I suggest you to do the following: https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#cluster-execution

**Comment by botellaflotante** [comment]
[SRR5195131.txt](https://github.com/metagenome-atlas/atlas/files/5717161/SRR5195131.txt)
[SRR5195137.txt](https://github.com/metagenome-atlas/atlas/files/5717163/SRR5195137.txt)
I have not tried the cluster execution yet, but, here are some files from one of the biggest samples I have. I set in the config file 1200 mem and 16 CPUs, and excuted it also with mem=1200 and jobs 20, because I tried before with lower numbers and it failed. Is it possible to try estimate how much memory will use each of these samples based on these benchmark files, in order to correct these values I set? (I may be able to run 2 of these at the same time, instead of one). Thanks..

**Comment by SilasK** [comment]
Just to make sure, your problem above was that you allowed atlas to use more than the available memory. 

I don't know for which step the benchmark files are but it seems that the peak of the memory corresponds to the 1.TB you specified the average is however only 1.6 GB. I don't know if you can decrease the max memory, you have to try and error a bit. I've never encountered a sample that needs 1TB to run, but maybe you have one. 

I suggest you to try the cluster execution. You can run all the steps for all the samples that pass with average resources e.g. 120GB and 8 threads. The view big samples you that don't pass you can increase the resources at the end. 
(Even for the big samples there are steps in the pipeline that don't require a lot of resources) 

Also run with the option `--keep-going` so atlas doesn't stops for samples that fail.
