### ISSUE TITLE
Conda install issues

### ISSUE THREAD

**Issue by bramvandijk88** [metagenome-atlas/atlas#332]
Heya,

I've now tested this accross multiple systems, but the conda installation of metagenome-atlas seems broken. Using:

> conda install -y -c bioconda -c conda-forge metagenome-atlas

will fail to resolve the conda environment. Any ideas what may cause this?

**Comment by IRSADFERHAT** [comment]
hi,
I have encountered a similiar problem. And using mamba solved it. You can use the link to install mamba and use it.
https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html
good day.

**Comment by bramvandijk88** [comment]
Over the weekend it somehow installed it using Conda... it just took forever! I'll test Mamba soon, thanks for the solution.

**Comment by SilasK** [comment]
@IRSADFERHAT Thank you for the response. Yes. Conda is just very slow sometimes. Mamba is faster. 

When you run atlas, one of the first steps is also to install specific environments with conda. Try to be patient and let it run over night.
