### ISSUE TITLE
Slurm execution error: Requested time limit is invalid (missing or exceeds some limit)

### ISSUE THREAD

**Issue by IRSADFERHAT** [metagenome-atlas/atlas#333]
hi, 
I am running Atlas in slurm. In the 'rule deduplicate_reads' and 'rule build_decontamination_db' steps, atlas gave the same error as follows:
Traceback (most recent call last):
  File "/kuacc/users/epaerhati19/.config/snakemake/cluster/scheduler.py", line 66, in <module>
    raise Exception("Job can't be submitted\n"+output.decode("utf-8")+error.decode("utf-8"))
Exception: Job can't be submitted
sbatch: error: Batch job submission failed: The requested time limit is invalid (missing or exceeds some limit)
Error submitting jobscript (exit code 1):
[atlas_251_252-2003552.out.txt](https://github.com/metagenome-atlas/atlas/files/5577586/atlas_251_252-2003552.out.txt)

And it shut down. The message is easy to understand. But I don't know where the problem lies. Cluster configuration or atlas? 
Could you please help me with this issue?
Best
Irsat 
the log file is attached.

**Comment by SilasK** [comment]
Do you have different queues available on your cluster system? Do they have different time/memory limits?
E.g. I have a bigmem-partion or a partition where I can put jobs for >1day.
Which is your default queue?
Check it out with ’sinfo'

**Comment by IRSADFERHAT** [comment]
![Screenshot from 2020-11-27 15-12-54](https://user-images.githubusercontent.com/56880890/100448425-49368d80-30c3-11eb-81e5-ab0590296ebc.png)
![Screenshot from 2020-11-27 15-13-37](https://user-images.githubusercontent.com/56880890/100448442-5489b900-30c3-11eb-9f7f-a6a58413b37c.png)

Yes. As you can see in the attached files, we have different partitions available with different time/memory limits. The default ones have a time limit of 2 hours. 

Sorry for the late reply. I was not very well.
best
Irsat

**Comment by SilasK** [comment]
Ok, If I understand correctly,  the default queue is the `short`, which is too short for you. 

You can set the queue for all rules or specific ones in the [`clusterprofile/cluster_config.yaml`](https://github.com/metagenome-atlas/clusterprofile/blob/e66d2638270de6381c1c38dd420da5db4b4a1b84/%7B%7Bcookiecutter.profile_name%7D%7D/cluster_config.yaml#L8)

I suggest the `mid`by default and may be longer for the assembly and some other rules. You must try and error a bit.
