### ISSUE TITLE
Taxonomic affiliation of genes and contigs

### ISSUE THREAD

**Issue by jfourquet2** [metagenome-atlas/atlas#334]
Hi,
I am trying to understand the differents output files of ATLAS and I am interested about outputs concernaing taxonomy.
genomes/checkm/taxonomy.tsv gives me the taxonomy at bin level. Is there files where there is taxonomic affiliation of genes and contigs? I didn't find these type of files in different output folders but maybe I haven't just seen them. Maybe there are in cached files?
Thanks a lot in advance !

**Comment by SilasK** [comment]
There is a section in the documentation about the output files. Have a look.

I’m also working on this extension to create nice reports from the output: https://github.com/metagenome-atlas/atlas_analyze

The GTDB taxonomy contains the most accurate taxonomy on bin level.
For the genes where there is a EggNOG annotation you also have a taxonomic annotation. However there are some limitation to sign taxonomy to genes. For example genes on the same coating don’t necessarily agree.

One could aggregate the taxonomy of different genes to get the taxonomy per config. Alternatively what people do is to use e.g. Kraken to asign a taxonomy to each config.

**Comment by jfourquet2** [comment]
Thanks for your answer !
In master/docs/usage/output.rst I've seen that Genecatalog/annotations/eggNog.tsv.gz contains taxonomy in the 5th column, is there this file you told about into your answer ? What are the limitations of singing taxonomy to genes ?
Concerning contig taxonomy, thanks for your suggestions ! Is ATLAS doing what you are proposing ?

**Comment by SilasK** [comment]
No in atlas this is not yet implemented. 
Have a look at this https://twitter.com/JacksonTsuji/status/1333351193947512833
