### ISSUE TITLE
executing selected process- Binning

### ISSUE THREAD

**Issue by ShailNair** [metagenome-atlas/atlas#335]
Hi, 
Is there a way to just do binning with quality stats of the bins. I have cleaned my reads and co-assembled contig file (Done manually not via ATLAS). Can I upload it to ATLAS workflow and get the bins?

**Comment by SilasK** [comment]
With a little hack. 
- Run atlas init with --skip-qc 
- set in the sample.tsv the BInGroup to the same name for all samples. 
- In the sample.tsv rename the first sample to `project`' or a name you want to give for the full project
- create a symbolic link from your co-assembly to `project/project_contigs.fasta`
- run: `atlas run None project/binning/metabat/bins sample/binning/metabat/checkm/taxonomy.tsv`

It should get you what you want.

**Comment by razz1618** [comment]
Thanks. i will try that.

**Comment by botellaflotante** [comment]
Hi, is there a way of running binning with only the samples that produce bins? I am using only metabat and some samples have 2 bins, others 0, and I think this is causing error (even using -k)...

**Comment by SilasK** [comment]
Sorry my answer was stuck in the mailbox.

You can remove them from the sample.tsv. then you can add them later I think to do the quantification.


I wonder, is it sufficient if you only get 1-2 bins per sample? You nay get a 10MAGs for the whole project, which will give you only a very low mapping rate.
If you are interested in studying the whole microbioe it's probably better to use the genecatalog.

**Comment by AnneliektH** [comment]
Hello!
I have the same question, but for me the `atlas run None project/binning/metabat/bins sample/binning/metabat/checkm/taxonomy.tsv` returns:
```
[Atlas] INFO: Atlas version: 2.17.2
Config file /home/amhorst/mambaforge/envs/atlas/lib/python3.10/site-packages/atlas/workflow/../config/default_config.yaml is extended by additional config specified via the command line.
Didn't find raw reads in sampleTable - skip QC
Building DAG of jobs...
MissingRuleException:
No rule to produce sample/binning/metabat/checkm/taxonomy.tsv (if you use input functions make sure that they don't raise unexpected exceptions).
[Atlas] CRITICAL: Command 'snakemake --snakefile /home/amhorst/mambaforge/envs/atlas/lib/python3.10/site-packages/atlas/workflow/Snakefile --directory /group/ctbrowngrp2/scratch/annie/2024-pigparadigm/results/low_explain_coass  --rerun-triggers mtime --jobs 32 --rerun-incomplete --configfile '/group/ctbrowngrp2/scratch/annie/2024-pigparadigm/results/low_explain_coass/config.yaml' --nolock   --use-conda --conda-prefix /home/amhorst/database_atlas/conda_envs    --resources mem=59 mem_mb=61065 java_mem=50   --scheduler greedy    PRJNA779404/binning/metabat/bins sample/binning/metabat/checkm/taxonomy.tsv ' returned non-zero exit status 1.
```
Is there another output file I can specify instead of those?

Thank you!
