### ISSUE TITLE
MAG stats and taxonomy

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#336]
Hi! I would like to know which format is the genomes/checkm/storage/bin_stats.analyze.tsv. Is it a JSON? I tried to read it with rjson in rstudio but couldn't...

Also I would like to ask if there is some nice way already implemented to get the predicted taxonomy from each MAG from different ATLAS projects to place them in a tree showing MAGs recovered from an environment 

Best!

**Comment by SilasK** [comment]
The file extension of `genomes/checkm/storage/bin_stats.analyze.tsv` is tsv so I expect it to be a table with tabs separated. But I don't know exactly. It's an output file of checkM, and I suggest you looking in their docs. 

Normally, Atlas builds a tree, for all the MAGs, of a project, based on the GTDB markers. Actually, one for archaea, one for bacteria and it can build one for both based on the check Markers.
by the way here is some code for the plotting of trees: https://github.com/metagenome-atlas/Tutorial/blob/master/R/Draw_Tree.Rmd

But again, If you want to combine MAGS from a different project, you would need to do some hacking. It's possible but It's automatic if all the samples are in the same project.

**Comment by SilasK** [comment]
Just a question, would you like to attend my class about atlas in two days, however it would be 2.dec 9:00 - ~16:00 *CET*

**Comment by botellaflotante** [comment]
yes, I would love to. altough I have some meetings on wednesday and thursday... will it be recorded?
Instead of running the tree for the different projects' MAGs in ATLAS I could simply install and run GTDB-Tk using the database in ATLAS, right? In that case, would that be in databases/GTDB_V05/release95 ??

**Comment by SilasK** [comment]
Yes you can install GTDB-tk via condo and use the database downloaded with atlas.

**Comment by botellaflotante** [comment]
So, I tried doing something like this to configure the databse, but I guess is wrong..
echo "export GTDBTK_DATA_PATH=home/user/databases/GTDB_V05/" > /home/user/miniconda3/envs/gtdbtk/etc/conda/activate.d/gtdbtk.sh

**Comment by SilasK** [comment]
No, it should work, except that there is a missing / before home. I’ve just seen that GTDB-tk made the 1.4 release.

**Comment by botellaflotante** [comment]
ok, tough now I get that the database is wrong somehow...

ERROR                                      
____________________________

           The GTDB-Tk reference data does not exist or is corrupted.           
      GTDBTK_DATA_PATH=/home/jose/jose2/databases/GTDB_V05/gtdbtk_data.tar      

   Please compare the checksum to those provided in the download repository.    
          https://github.com/Ecogenomics/GTDBTk#gtdb-tk-reference-data

this is what I have in that database folder:

downloaded_success  gtdbtk_data.tar  masks     mrca_red  pplacer  release95
fastani             markers          metadata  msa       radii    taxonomy

thanks for the help

**Comment by botellaflotante** [comment]
and the command was
echo "export GTDBTK_DATA_PATH=/home/jose/jose2/databases/GTDB_V05/" > /home/jose/miniconda3/envs/gtdbtk/etc/conda/activate.d/gtdbtk.sh
