### ISSUE TITLE
Mapping of contigs on MAGs

### ISSUE THREAD

**Issue by johanneswerner** [metagenome-atlas/atlas#337]
Is there a possibility (preferably a tsv table) that maps the original contig IDs from the assembly on the MAGs and the new contig IDs? The file `./genomes/clustering/old2newID.tsv` has the old and new MAG IDs, but how can I see which contigs from which assembly file are part of which MAG?

Thank you!

**Comment by SilasK** [comment]
Tese two files should give you what you want:

"genomes/clustering/all_contigs2bins.tsv.gz",
"genomes/clustering/old2newID.tsv",

For your info there are also: 

"genomes/clustering/contig2genome.tsv",
 "genomes/annotations/gene2genome.tsv.gz"

**Comment by johanneswerner** [comment]
Thank you for your answer but this does not solve my problem: 

I have a few different metagenomes, for instance the sample `FT-NS`. Below I am listing the first few contig headers of this sample. 

```
grep "^>" FT-NS/FT-NS_contigs.fasta | head
>FT-NS_0
>FT-NS_1
>FT-NS_2
>FT-NS_3
>FT-NS_4
>FT-NS_5
>FT-NS_6
>FT-NS_7
>FT-NS_8
>FT-NS_9
```

How can I find out which contigs the bin `MAG023` has? In the file `old2newID.tsv`, I can spot that `MAG023` has the old bin ID `FT-NS_maxbin.010`, but this does not give me the information of all (or any of its) contigs. I could get the respective contigs probably out of the fasta file of this dataset `FT-NS/binning/DASTool/bins/FT-NS_maxbin.010.fasta`, but I wondered if there is an easier way.

Thank you very much for your help.

**Comment by SilasK** [comment]
Sorry, 

You can get the information in `{sample}/binning/{final_binner}/cluster_attribution.tsv` This lists contigs to old bin id. Probably I that I renamed the  `.` to `_` in the bin name.

Keep in mind, that the MAGs were dereplicated, which means not all contigs are in the final set of MAGs. 
E.g. contig `FT-NS_9` may belong to a bin `FT-NS_maxbin.005` which then belongs to the same species as a MAG from another sample, something like `FT-abc_maxbin.001` renamed to `MAG050`. So the exact contig `FT-NS_9` may not be in the dereplicated set of MAGs. 

The "genomes/clustering/all_contigs2bins.tsv.gz", gives the information from old bin to species, if you want.


What are you trying to do?

**Comment by johanneswerner** [comment]
Thank you for your answer. 

We are looking for certain biodegradation genes in our metagenomes. In order to do so (and because we have microbiologists in our team), we used prokka for the gene prediction - it does not always provide an exact, yet a for microbiologists useful functional annotation. 

With the gff file generated by prokka, we can identify on which contigs these genes lie on.

And we wanted to find out which of those contigs are binned into MAGs (and also which ones), and which of them are unbinned. 

Do you have an idea on how to solve this scenario? Thank you very much!

**Comment by SilasK** [comment]
If you look on a per sample basis. Each, `{sample}/binning/{final_binner}/cluster_attribution.tsv` gives you the association between contigs and bins. The bins are in `{sample}/binning/{final_binner}/bins` and you have also the checkM annotation `{sample}/binning/{final_binner}/checkm`  

I tired to use Prokka but as it uses a lot of blasts I didn't' manage to make it work in a reasonably efficient way. Can you tell me what are the annotations that are not contained in the eggNOG annotations?

**Comment by johanneswerner** [comment]
PETases and MHETases are some of the enzymes that we are looking for, and those are present in some of the metagenomes, but not detectable with eggNOG. I assume those are classified as alpha/beta hydrolase, therefore we looked into different annotation sources.
