### ISSUE TITLE
Constrain atlas to single compute node on SLURM using --nodelist param

### ISSUE THREAD

**Issue by ejongepier** [metagenome-atlas/atlas#338]
Hi,

I am trying to run atlas on a slurm cluster without shared scratch or tmp space. 
Because I have insufficient storage to run it on the head node, I would like to restrict all jobscripts to a single node using the slurm param -w/--nodelist. This way I can use /scratch of the node I select. 

I set up cluster configuration/deployment/execution following these instructions: https://github.com/metagenome-atlas/clusterprofile, which works great on the test data set.
Could you give me a pointer where / what  I need to modify to ensure all jobscripts are submit to my predefined node?

Many thanks!

Best,
Evelien

versions: 
Linux 5.7.8-1.el7.elrepo.x86_64 x86_64
slurm 18.08.8
atlas, version 2.4.4

**Comment by SilasK** [comment]
How do you access the data after atlas it's finished or before you start it? Isn't the data removed afterwards? I wonder if it wouldn't be easier if you claim the whole node and run atlas on this single node: https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#single-machine-execution

But of course, you can simply adapt the clusterprofile, in the [`key_mapping.yaml`](https://github.com/metagenome-atlas/clusterprofile/blob/e66d2638270de6381c1c38dd420da5db4b4a1b84/%7B%7Bcookiecutter.profile_name%7D%7D/key_mapping.yaml#L5) you add the parameter you want to the `sbatch commnad`
