### ISSUE TITLE
Single copy gene prediction using diamond failed. Aborting

### ISSUE THREAD

**Issue by bhimbbiswa** [metagenome-atlas/atlas#341]
Hi.

I am having this error again and again. Please help to solve.
```
DAS Tool run on  Wed Dec 9 10:47:40 JST 2020

User environment details:
Rscript path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/Rscript
Rscript version:  R scripting front-end version 4.0.3 (2020-10-10)
pullseq path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/pullseq
pullseq version:  Version: 1.0.2 Name lookup method: UTHASH
prodigal path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/prodigal
prodigal version:  Prodigal V2.6.3: February, 2016
ruby path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/ruby
ruby version: 
diamond path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/diamond
diamond version:  diamond version 2.0.5

Running DAS Tool using 1 threads.
identifying single copy genes using diamond version 2.0.5

single copy gene prediction using diamond failed. Aborting
```
Please find the required logs and config file attached.

[S13_DASTool.log](https://github.com/metagenome-atlas/atlas/files/5663070/S13_DASTool.log)
[DASTool.log](https://github.com/metagenome-atlas/atlas/files/5663071/DASTool.log)
[Main_log.txt](https://github.com/metagenome-atlas/atlas/files/5663072/Main_log.txt)
[config.txt](https://github.com/metagenome-atlas/atlas/files/5663078/config.txt)

**Comment by SilasK** [comment]
Check the input files: 
S13/binning/DASTool/metabat.scaffolds2bin, S13/binning/DASTool/maxbin.scaffolds2bin
It should contain contigs to bin mappings similar as to the one we have seen in the class.
Also check 
S13/annotation/predicted_genes/S13.faa

**Comment by bhimbbiswa** [comment]
Hi.

I am sorry, I didn't understand what you mean by class?

Please find attached the bin file and a snap of S13.faa.

[maxbin.scaffolds2bin.txt](https://github.com/metagenome-atlas/atlas/files/5664330/maxbin.scaffolds2bin.txt)
[metabat.scaffolds2bin.txt](https://github.com/metagenome-atlas/atlas/files/5664332/metabat.scaffolds2bin.txt)
![Capture](https://user-images.githubusercontent.com/41138685/101601301-e5578180-3a3f-11eb-9892-50f34de8e5c8.PNG)

**Comment by bhimbbiswa** [comment]
Hi.
As seen in #223 my env file is different. It doesn't have 'R'

```
channels:
    - conda-forge
    - bioconda
    - ruby-lang
    - defaults
dependencies:
    - das_tool=1.1
```

I this normal?

**Comment by SilasK** [comment]
The input files seems ok. 
Sorry, I thought you attended the atlas class on monday, never mind. 
> As seen in #223 my env file is different. It doesn't have 'R'
The r channel in integrated in the default.

It seems you are runnign dastool with only 1 thread. It is possible that this is too little for diamond. I ssuggest you to increase the threads in the config. 
Also you have mem=1000 = 1TB which is quite a lot, but shoudn't affect the DAStool. 

You can try to remove the conda environment for DAS tool to force a reinstall. 
The path is something like this `stre7homebhimbiswaNew_microdatabasesconda_envs92a32d4b`

**Comment by bhimbbiswa** [comment]
Hi.

I did both but again got the same problem and the conda environment for DAS tool still didn't download R.

I am getting a core dump file for each thread.

Please see attached 
[Atlas_all.sh.e11032479.txt](https://github.com/metagenome-atlas/atlas/files/5666131/Atlas_all.sh.e11032479.txt)
the log file and core dump file.
[core.25573.txt](https://github.com/metagenome-atlas/atlas/files/5666116/core.25573.txt)

**Comment by SilasK** [comment]
How do you see that R was not installed with conda? 

The easiest solution would be to use `metabat` as final_binner in the config file. You could also raise an issue at the github of DASTool, as it seems to be related to DAS_Tool.

**Comment by bhimbbiswa** [comment]
Sorry. In a hurry, I checked yml file of DAS_Tool env. R is installed in envs92a32d4b

Ok. I will change final binner to metabat and raise this issue in DASTool page. 

Will update of any new progress.

**Comment by yanhui09** [comment]
@bhimbbiswa 
I'm not sure if it's too late. The bug shall be caused by the `ruby` conflicts in some nodes. I also met this when running DAStool with atlas. See #https://github.com/cmks/DAS_Tool/issues/13#issuecomment-913549908

You can manually revise the isolated `conda` environment for `dastool`, and solely removed `ruby` if admins have installed `ruby` already.

**Comment by bhimbbiswa** [comment]
@yanhui09 Thank you very much. Removing Ruby from my conda environment solved the problem. 

As suggested, I used the following command in the conda environment in which this program was running.
```
conda remove ruby --force
```
Closing this issue as the problem is solved.
