### ISSUE TITLE
Host reads binned?

### ISSUE THREAD

**Issue by Ahmed-Shibl** [metagenome-atlas/atlas#343]
Hi atlas team,

First I want to say thanks for this fantastic and well-rounded pipeline.

I have a question regarding host genomes. I'm currently working with metagenomes that contain bacterial, symbiodinium, and coral reads. I want to tease apart the bacterial reads from the symbiodinium/coral ones - and so, I added the (symbiodinium and coral) genomes to the list of contaminant_references in the configuration file. At the same time, I would still like to use the symbiodinium and coral reads downstream - and so my question is, does ATLAS 'save' these contaminant/host reads somewhere after 'cleaning' the metagenome or are they forever lost?

Thanks!

**Comment by SilasK** [comment]
No atlas saves the reads mapping to the contaminant references in

“{sample}/sequence_quality_control/contaminants/{db}_{fraction}.fastq.gz"
Where db is the name you give in the config file. eg. You get one for symbiodinium and one for coral if you supply the two genomes separately.

**Comment by Ahmed-Shibl** [comment]
Great, so just to confirm I'm getting this right, e.g. reads belonging to the coral genome ASM193914v1 that have been mapped to Read 2 of my PE metagenomic dataset CD151, are found in "CD151/sequence_quality_control/contaminants/ASM193914v1_R2.fastq.gz" ?

Thanks!!

**Comment by SilasK** [comment]
The reads are mapped to the genome not the other way around, but yes this is it.
