### ISSUE TITLE
Error in rule eggNOG_annotation

### ISSUE THREAD

**Issue by bhimbbiswa** [metagenome-atlas/atlas#346]
Hi. I am getting an error in rule eggNOG_annotation. I am not able to figure out what is the problem.
```
Error in rule eggNOG_annotation:[0m
[31m    jobid: 0[0m
[31m    conda-env: /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/76eb774e[0m
[31m    log: Genecatalog/subsets/genes/logs/subset9/eggNOG_annotate_hits_table.log (check log file(s) for error message)[0m
[31m    conda-env: /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/76eb774e[0m
[31m    jobid: 0[0m
[31m    output: Genecatalog/subsets/genes/subset1.emapper.annotations[0m
[31m    shell:
        

            if [ t == "t" ] ;
            then
                cp /dev/shm/eggnog.db /dev/shm/eggnog.db 2> Genecatalog/subsets/genes/logs/subset5/eggNOG_annotate_hits_table.log
            fi

            emapper.py --annotate_hits_table Genecatalog/subsets/genes/subset5.emapper.seed_orthologs --no_file_comments               --override -o Genecatalog/subsets/genes/subset5 --cpu 10 --data_dir /dev/shm 2>> Genecatalog/subsets/genes/logs/subset5/eggNOG_annotate_hits_table.log
```

I had one more error which I asked previously in #341  
Please find the logs here.
[Atlas_all.sh.e11229411.txt](https://github.com/metagenome-atlas/atlas/files/5687573/Atlas_all.sh.e11229411.txt)
[eggNOG_annotate_hits_table.log](https://github.com/metagenome-atlas/atlas/files/5687574/eggNOG_annotate_hits_table.log)

**Comment by jmtsuji** [comment]
@bhimbbiswa Just to check, in your config file, was "eggNOG_use_virtual_disk" set to t?

I think this might be a bug in the ATLAS code where the source location of the eggnog database is not set correctly for copying to virtual disk. @SilasK I ran into what I think is the same issue (and fixed it locally) when finalizing my PhD thesis but did not have time to file a bug at the time (on ATLAS 2.4.2)...

Currently `rule eggNOG_annotation` in [genecatalog.snakefile](https://github.com/metagenome-atlas/atlas/blob/master/atlas/rules/genecatalog.snakefile) looks like this: 
```
rule eggNOG_annotation:
    input:
        eggnog_db_files=get_eggnog_db_file(),
        seed = rules.eggNOG_homology_search.output
    output:
        temp("{folder}/{prefix}.emapper.annotations")
    params:
        data_dir = "/dev/shm" if config['eggNOG_use_virtual_disk'] else EGGNOG_DIR,
        prefix = "{folder}/{prefix}",
        copyto_shm="t" if config['eggNOG_use_virtual_disk'] else 'f'

    threads:
        config.get("threads", 1)
    resources:
        mem=20
    shadow:
        "minimal"
    conda:
        "%s/eggNOG.yaml" % CONDAENV
    log:
        "{folder}/logs/{prefix}/eggNOG_annotate_hits_table.log"
    shell:
        """

            if [ {params.copyto_shm} == "t" ] ;
            then
                cp {params.data_dir}/eggnog.db /dev/shm/eggnog.db 2> {log}
            fi

            emapper.py --annotate_hits_table {input.seed} --no_file_comments \
              --override -o {params.prefix} --cpu {threads} --data_dir {params.data_dir} 2>> {log}
        """
```

I think the issue is that `params.data_dir` gets set to `/dev/shm`, but this makes the copy command (`cp {params.data_dir}/eggnog.db /dev/shm/eggnog.db 2> {log}`) become impossible: `cp /dev/shm/eggnog.db /dev/shm/eggnog.db` as shown in the log from @bhimbbiswa 

To solve this issue, I made a separate param called `eggnog_dir`, as follows:
```
rule eggNOG_annotation:
    input:
        eggnog_db_files=get_eggnog_db_file(),
        seed = rules.eggNOG_homology_search.output
    output:
        temp("{folder}/{prefix}.emapper.annotations")
    params:
        eggnog_dir = EGGNOG_DIR,
        data_dir = "/dev/shm" if config['eggNOG_use_virtual_disk'] else EGGNOG_DIR,
        prefix = "{folder}/{prefix}",
        copyto_shm="t" if config['eggNOG_use_virtual_disk'] else 'f'

    threads:
        config.get("threads", 1)
    resources:
        mem=20
    shadow:
        "minimal"
    conda:
        "%s/eggNOG.yaml" % CONDAENV
    log:
        "{folder}/logs/{prefix}/eggNOG_annotate_hits_table.log"
    shell:
        """

            if [ {params.copyto_shm} == "t" ] ;
            then
                cp {params.eggnog_dir}/eggnog.db /dev/shm/eggnog.db 2> {log}
            fi

            emapper.py --annotate_hits_table {input.seed} --no_file_comments \
              --override -o {params.prefix} --cpu {threads} --data_dir {params.data_dir} 2>> {log}
        """
```

Note that this still seems a bit inefficient because the `eggnog.db` file is re-copied to the virtual disk each time that emapper is run, but this fix seemed to solve the issue.

**Comment by bhimbbiswa** [comment]
@jmtsuji Thank you very much for your response.

Yes, it was set to "True". 

I am now running after setting it as "False". Till now not getting the error (which I was getting immediately after starting the run). 

Will update again after finishing or if encounted a new error.

Thank you very much.

**Comment by jmtsuji** [comment]
Sounds good @bhimbbiswa. I hope your run works out.

**Comment by SilasK** [comment]
@jmtsuji #347 should solve the problem, isn't it? thank you for solving the issue.

**Comment by jmtsuji** [comment]
@SilasK Looks good -- just reviewed and approved the PR.

**Comment by bhimbbiswa** [comment]
Hi. Thank you very much for your help. My analysis finished without any further error.

**Comment by jmtsuji** [comment]
Glad to hear @bhimbbiswa
