### ISSUE TITLE
Installing: stuck at 'solving environment'

### ISSUE THREAD

**Issue by cslamo** [metagenome-atlas/atlas#348]
the installation command 
     conda install -y -c bioconda -c conda-forge metagenome-atlas
starts a series of attempts at 'solving environment' ending with 'Failed with initial frozen solve', and then 'failed with repodata from current_repodata.json, will retry with next repodata source', and it gets stuck doing 'solving environment'

Note: First it stopped saying atlas is not comnpatible with python3.8, so I created an env for python3.6, and this is when the above thing happens.

ANy advice greatly appreciated.

Claudio

**Comment by jmtsuji** [comment]
@cslamo See #332 -- does that help? In short, you might try installing ATLAS using mamba like shown [in the docs](https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html) to help resolve the ATLAS environment. Note that you might need to set the environment to python=3.6 when installing mamba, like you mentioned. Hope this helps.

**Comment by cslamo** [comment]
That worked. However I run the test data but at step 153 it stopped with error. This is the part in the log:
Activating conda environment: /home/claudio/databases/conda_envs/78af40b8
Removing temporary output file genomes/tree/gtdbtk.bac120.unrooted.nwk.
[Tue Dec 29 18:22:49 2020]
Finished job 157.
152 of 155 steps (98%) done

[Tue Dec 29 18:22:49 2020]
rule classify:
    input: genomes/taxonomy/gtdb/align, genomes/genomes
    output: genomes/taxonomy/gtdb/classify
    log: logs/taxonomy/gtdbtk/classify.txt, genomes/taxonomy/gtdb/gtdbtk.log
    jobid: 26
    resources: mem=44, time=24

Activating conda environment: /home/claudio/databases/conda_envs/7c149907
[Tue Dec 29 18:30:08 2020]
Error in rule classify:
    jobid: 26
    output: genomes/taxonomy/gtdb/classify
    log: logs/taxonomy/gtdbtk/classify.txt, genomes/taxonomy/gtdb/gtdbtk.log (check log file(s) for error message)
    conda-env: /home/claudio/databases/conda_envs/7c149907
    shell:
        GTDBTK_DATA_PATH=/home/claudio/databases/GTDB_V05 ; gtdbtk classify --genome_dir genomes/genomes --align_dir genomes/taxonomy/gtdb --out_dir genomes/taxonomy/gtdb --extension fasta --cpus 1 &> logs/taxonomy/gtdbtk/classify.txt
        (exited with non-zero exit code)

Removing output files of failed job classify since they might be corrupted:
genomes/taxonomy/gtdb/classify
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/claudio/.snakemake/log/2020-12-29T120750.104886.snakemake.log

**Comment by jmtsuji** [comment]
@cslamo A more detailed log should exist
at logs/taxonomy/gtdbtk/classify.txt -- does that provide any more info
about what went wrong?

Based on the snakemake log, I would guess that you did not supply enough
memory. The GTDB classifier requires about 100 GB of memory to run,
unfortunately. It is possible to turn the classifier off (or change to a
different classifier) if you do not have that much memory.


2020年12月30日(水) 7:40 Claudio Slamovits <notifications@github.com>:

**Comment by cslamo** [comment]
Memory issue makes sense as it was running on a 44GB VM. Also, I tried a run with my data (larger than the test_reads) and it stopped much earlier, with the same classifier error. I'll try implementing on my centre's cluster.
Any suggestion for a different classifier?
Thanks!

**Comment by jmtsuji** [comment]
@cslamo I believe that ATLAS allows you to alternatively classify the genomes via either CheckM's taxonomy function or using CAT. Both of these options are more RAM-friendly. However, CheckM taxonomy is a bit challenging to work with (GTDB-Tk was meant to replace it, I think), and CAT takes a long time to run for each genome. You can set these classification methods in the "annotations" section of the config.yaml file, I believe (although I do not have the config file in front of me at the moment). Let me know if you'd like more details. I believe that you can also turn off GTDB taxonomy in that area of the config file if you want to run all of ATLAS except for GTDB-Tk on your server.

If at all possible, I recommend getting access to more RAM (like by using your centre's cluster) and using GTDB-Tk. It's unfortunate that the RAM requirements are so high, but this taxonomy method is quickly becoming mainstream in metagenomics and is quite handy.

Hope this helps!
