### ISSUE TITLE
Suggestion to help others running atlas (for biologists as me)

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#349]
@Sofie8  gave me some good advice. I put this here. 

I download the databases separately because it takes quite some hours and 100 Gb of space, and I like to check if everything gets downloaded without errors.
```
atlas download --db-dir /ddn1/vol1/site_scratch/leuven/314/vsc31426/db/atlas
```
Then I run initialise.
```
atlas init --db-dir /path/db/atlas /path/to/fastq
```
Lastly, I always have to fix the names, as I get the sequence data as _1; _2 not R1 and R2, and I noticed your script sees 1 and 2 as separate samples, not as Read1 and Read2. Sometimes with being fast, I forget this little renaming. Maybe it can save others also some head breaking.

**ATTENTION** The sample names have to be alphanumeric, and Read1 and Read2 need to have R in the sample names!! I get the reads without R, like Sample1_1.fastq.gz and Sample1_2.fastq.gz, but a correct name is Sample1_R1.fastq.gz

Check if everything will run without errors

```atlas run all --dryrun  ```
run atlas
```atlas run all ```

**Comment by botellaflotante** [comment]
here's a line to do this quickly, I guess there must be better ways but this works, sequentially for R1 and then R2:

for f in $(find /path/to/fastq/files -name "*fastq.gz");do mv $f "${f//_1/_R1}";done

for f in $(find /path/to/fastq/files -name "*fastq.gz");do mv $f "${f//_2/_R2}";done

**Comment by SilasK** [comment]
I would add two suggestions to get the most of atlas:

1. Do you have a cluster system e.g.  slurm, lsf or pbs? I let you have a look at the cluster submission wrapper which helps you to make the most of atlas. https://github.com/metagenome-atlas/clusterprofile
2. Do you have a shared memory e.g. `/dev/shm` on the cluster nodes? If yes then I would advise you to use it to accelerate the eggnog homology search. In the config file set `eggNOG_use_virtual_disk: true`
