### ISSUE TITLE
re-run atlas after assembly step

### ISSUE THREAD

**Issue by pbaCamille** [metagenome-atlas/atlas#350]
Hello,

I have 2 sample assemblies and I refined one of the assembly manually. I'm trying to re-run atlas with this new assembly (binning, DAS tool, genomes, etc. to the end). I tried in a new folder and re-run atlas (dry run), but I seems that atlas workflow always includes the unnecessary re-assembly, assembly steps. 
Is there a way to skip first steps ?

Thx

**Comment by SilasK** [comment]
Thank you Camille for trying atlas. Could I ask how you refined the assembly?

Did you copy the whole working directory and THEN replaced the sample/sample_contigs.fasta with your refined assembly? You may also delete the sample/assembly/contig_stats/*final* stats

Snakemake is quite sensitive to the timestamp when files are created.

You can ask atlas why it regenerates the samples with ‘-n —reason’ and overwrite the timestamp with ‘—touch’

Not to me: I should add a column in the sample table where users can specify an alternative assembly.

**Comment by pbaCamille** [comment]
Thanks for your quick answer. 

I refined one of the assembly because of ambiguous remaining contamination (eukaryotic host sequences) in the final assembly and one of my MAG. So I just removed the ambiguous contigs from the final assembly file and would like to rerun the entire process, to have something "clean".
My first tries was to only copy few folders/files (sample/assembly/, sample_contigs.fasta, sequence_quality_control/). It was not the good strategy.
As you suggested, I just copy the entire workdir and replace sample/sample_contigs.fasta and deleted sample/assembly/contig_stats/*final* stats. After using --reason option, and  overwriting timestamp, it seems to be OK. 

It could be a great idea to add a column in the sample table ! I vote for it ;-)

**Comment by slambrechts** [comment]
Hi,

Just wanted to ask whether it's already possible to specify an external assembly? I previously ran megahit using the `--presets meta-large` flag, and it still needed a very long time to complete, so I would like to avoid having to redo that. Is there any way how to do that without having an atlas working directory from a previous run?

**Comment by SilasK** [comment]
I assume you have created an atlas project with the raw or qc reads with atlas init. Then, you could, in theory copy your assemblies into the working directory into as "{sample}/assembly/{sample}_raw_contigs.fasta” for each sample.

Atlas should continue without assembly from there.
Maybe try with one sample and do always a dryrun to see if atlas does what you want.

I think I should add an option to provide assemblies in the sample table ..

For the next time there is also the option to use megabit with meta-large with atlas.

**Comment by slambrechts** [comment]
Ok thanks! What I didn't realize is that atlas assembles each sample separately? The assembly I was talking about is one big coassembly. So I will run atlas as is, will be interesting to compare assembly and binning results between the single and coassembly approaches
