### ISSUE TITLE
Working HPC - is there a docker version, singularity version

### ISSUE THREAD

**Issue by soilmicrobiome** [metagenome-atlas/atlas#359]
Hi there,

I am working on a HPC that we are not permitted to use conda on.  Is there instruction to compile from scratch or a docker or singularity version available?

Thanks

**Comment by SilasK** [comment]
Oh, this is unfortunate. It won't allow you to access other nodes on your cluster. 

Here would be the instructions to use Docker.
https://github.com/metagenome-atlas/atlas/blob/a744644956ab143b1a0005f6c6022a0e027fcf8c/docs/usage/docker.rst

The atlas verison in the Docker container are V2.3 

If you want you to rebuild the docker file it uses the old one and updates atlas: https://github.com/metagenome-atlas/atlas/blob/master/Dockerfile

**Comment by soilmicrobiome** [comment]
I am also working on a HPC that does not allow conda.  But i found when i use:

$singularity pull metagenomeatlas/atlas

I get the following message:
"FATAL:   While pulling library image: error fetching image: image does not exist in the library: metagenomeatlas/atlas:latest (amd64)"

Any ideas?

**Comment by SilasK** [comment]
Hmm, I should find a solution for this use case. 

Is there a container with miniconda or mambaforge for singularity?

https://github.com/conda-forge/miniforge#mambaforge

**Comment by soilmicrobiome** [comment]
I could not see if this was the case.  And on the HPC i use there is not option for docker.   any ideas on what i can do?

**Comment by SilasK** [comment]
Ok, @soilmicrobiome 

My solution would be as follows:

1. Install all [dependencies](https://github.com/metagenome-atlas/atlas/blob/master/atlasenv.yml) for atlas. 

    - Except for bbmap all others are python packages and should be on pip. 
    - Install or load singularity.
2. Install atlas. 
    - For now, install metagenome atlas from Github (see docs). The changes e54a76e are not yet in the conda version.
3. Run atlas with the additional argument `--use-singularity`
    - I also recommend to use `--singularity-prefix /path/to/store/syngularity/packages` and if you need `--singularity-args`

atlas should now create each conda env in a singularity container.

The important advantage this solution is compatible with cluster execution. E.g. It is possible to let atlas submit multiple jobs to your cluster system. See the docs for more info.

**Comment by soilmicrobiome** [comment]
great! i'll give it a try

**Comment by soilmicrobiome** [comment]
I finally got a version of atlas working with singularity (apparently one of our servers has a file system that is not compatible with the container, but another one was).  I can successfully run "atlas init".  But when it comes to "atlas run all" there are still conda issues:

part of the error message:

_[2021-05-15 11:22 INFO] Executing: snakemake --snakefile /cvmfs/HPC_name/easybuild/software/2020/avx2/Compiler/intel2020/metagenome-atlas/2.4.3/lib/python3.6/site-packages/atlas/Snakefile --directory /project/6010084/user/path_to_files  --rerun-incomplete --configfile '/project/6010084/user/path_to_files/config.yaml' --nolock   --use-conda --conda-prefix /project/6010084/databases_software/atlas/databases/conda_envs   all   

Building DAG of jobs...
Creating conda environment /opt/conda/lib/python3.6/site-packages/atlas/rules/../envs/mmseqs.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /opt/conda/lib/python3.6/site-packages/atlas/rules/../envs/mmseqs.yaml:
Collecting package metadata (repodata.json): ...working... failed_


I guess this means the HPC can't create a conda env in a singularity container?  Is it time i find a Conda friendly place to run atlas?

**Comment by SilasK** [comment]
Sorry for the delay. Obviously a conda-frendly version would help. I for example just installed conda in my scratch directory. 

Is there no other error about why the conda installation failed? 
Often it is an internet connection. Do you think there is a problem with the internet connection within the singularity container? 

Maybe an stupid error from my side would be solved by using `--conda-frontend conda` 
You can also use `atlas run assembly <other options> --use-singularity --conda-create-envs-only` to only create the conda enfs

**Comment by soilmicrobiome** [comment]
The people that are in charge of the HPC have been working on it over the last few weeks.  They think they have it solved -- the last few lines of the output in a test run stated :

"10 of 10 steps (100%) done
Complete log: /scratch/user/consultation/metagenome-atlas/container/.snakemake/log/2021-07-16T205659.541503.snakemake.log
ATLAS finished"

Once i get the details, I'll let you know how they got it to run in case thats of use to anyone!

**Comment by SilasK** [comment]
Great! Yes, It hink, it would be beneficial to others.

**Comment by soilmicrobiome** [comment]
they did not give me too much info apart from: 

the previous singularity had a "mamba" installed with bugs, which could not create environments. The mamba installed in ubuntu 18.04 works, but not in ubuntu 20.04.
