### ISSUE TITLE
Zenodo ERROR 500: INTERNAL SERVER ERROR for CheckM and refseq.tree

### ISSUE THREAD

**Issue by jjsanchezgil** [metagenome-atlas/atlas#363]
Hi!

ATLAS raised an error when trying to download CheckM from Zenodo. I checked manually in Zenodo and this happens for both CheckM and refseq.tree apparently

```
--2021-01-27 14:53:32--  https://zenodo.org/record/1134890/files/checkm_data_v1.0.9.tar.gz
Resolving zenodo.org (zenodo.org)... 137.138.76.77
Connecting to zenodo.org (zenodo.org)|137.138.76.77|:443... connected.
HTTP request sent, awaiting response... 500 INTERNAL SERVER ERROR
2021-01-27 14:53:35 ERROR 500: INTERNAL SERVER ERROR.
```

**Comment by SilasK** [comment]
Could you raise the error directly at the Check repo. I think it's probably only a temporary problem with the internet connection or the server. 

Yopu may want to start running atlas up to the point checkM is needed. e.g with `atlas run assembly `
