### ISSUE TITLE
Cluster configuration does not overwrite main config

### ISSUE THREAD

**Issue by jjsanchezgil** [metagenome-atlas/atlas#368]
Hi,

I am running assembly on metagenomes on a CentOS with Slurm and I was having heap space errors from Java. In the main config.yaml, mem is configured to 80Gb, and I preferred not to increase all steps to 120Gb because the HPC seems busy. I added these lines to cluster_config.yaml:
```
error_correction:
  mem: 120

```
However, this is not taken into account during execution. The sbatch command constructor takes this value (below in the command there's mem=120). However, the actual resources assigned are those from the main configuration file, but not from the updated cluster_config:

```
CLUSTER: submit command: sbatch --parsable --output=cluster_log/slurm-%j.out --error=cluster_log/slurm-%j.out --job-name=error_correction --cpus-per-task=15 -n 1 --mem=120g --time=600 -N 2 /hpc/Metagenomes/ATLAS/.snakemake/tmp.kzoqg9n8/snakejob.error_correction.518.sh
Submitted job 518 with external jobid '1117773'.

[Mon Feb  1 18:11:14 2021]
rule error_correction:
    input: S-3-24/assembly/reads/QC_R1.fastq.gz, S-3-24/assembly/reads/QC_R2.fastq.gz, S-3-24/assembly/reads/QC_se.fastq.gz
    output: S-3-24/assembly/reads/QC.errorcorr_R1.fastq.gz, S-3-24/assembly/reads/QC.errorcorr_R2.fastq.gz, S-3-24/assembly/reads/QC.errorcorr_se.fastq.gz
    log: S-3-24/logs/assembly/pre_process/error_correction_QC.log
    jobid: 514
    benchmark: logs/benchmarks/assembly/pre_process/S-3-24_error_correction_QC.txt
    wildcards: sample=S-3-24, previous_steps=QC
    threads: 15
    resources: mem=80, java_mem=68, time=10
```
This ended up giving me the same memory error at the same point, so in the end I decided to increase memory for all steps to 120Gb, and then the resources are updated to mem=120, java_mem=102. Why does not the cluster configuration overwrite the standard one? 
Thank you

**Comment by SilasK** [comment]
Sory my message was not send:
Unfortunately, there is no easy way of achiving what you want other than setting config values dor each rule.

However, I thinkt that if error correction needs more memory, then the next step merging would also. So I would suggest to increase the mem for all steps.

Some steps use lower memory, specified by the hidden variable simplejob_mem .
