### ISSUE TITLE
error in rule run_das_tool at binning step, out of memory?

### ISSUE THREAD

**Issue by boaty** [metagenome-atlas/atlas#370]
Hi there,

I found error while running das_tool step,  my sample's size is around 5GB(paired) and i run with a single machine with 1TB mem and 80 cores.

Strange thing is that these error only happened for certain samples, some of samples can pass the das_tool step with 950GB mem, some does not. But for these passed samples, I got only 40+ final genome as output, is this normal?

thank you

I run with :

threads: 20
mem: 500 (or 950 for some samples)

large_mem: 200
large_threads: 50
assembly_threads: 50
assembly_memory: 300

----------------------------------------------error line----------------------------------------------------------------
rule run_das_tool:
    input: L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/metabat.scaffolds2bin, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/maxbin.scaffolds2bin, L1EEL101099-E3795-C-S162-L002-001/L1EEL101099-E3795-C-S162-L002-001_contigs.fasta, L1EEL101099-E3795-C-S162-L002-001/annotation/predicted_genes/L1EEL101099-E3795-C-S162-L002-001.faa
    output: L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_summary.txt, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_hqBins.pdf, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_scores.pdf, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_metabat.eval, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_maxbin.eval, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/cluster_attribution.tsv
    log: L1EEL101099-E3795-C-S162-L002-001/logs/binning/DASTool.log
    jobid: 5
    wildcards: sample=L1EEL101099-E3795-C-S162-L002-001
    threads: 20
    resources: mem=950, time=5

Activating conda environment: /home/Desktop/atlas_databases/databases/conda_envs/594cd97a
[Sun Feb 14 11:50:59 2021]
Error in rule run_das_tool:
    jobid: 5
    output: L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_summary.txt, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_hqBins.pdf, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_scores.pdf, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_metabat.eval, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_maxbin.eval, L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/cluster_attribution.tsv
    log: L1EEL101099-E3795-C-S162-L002-001/logs/binning/DASTool.log (check log file(s) for error message)
    conda-env: /home/Desktop/atlas_databases/databases/conda_envs/594cd97a
    shell:
         DAS_Tool --outputbasename L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001  --bins L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/metabat.scaffolds2bin,L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/maxbin.scaffolds2bin  --labels metabat,maxbin  --contigs L1EEL101099-E3795-C-S162-L002-001/L1EEL101099-E3795-C-S162-L002-001_contigs.fasta  --search_engine diamond  --proteins L1EEL101099-E3795-C-S162-L002-001/annotation/predicted_genes/L1EEL101099-E3795-C-S162-L002-001.faa  --write_bin_evals 1  --create_plots 1 --write_bin_evals 1  --megabin_penalty 0.5 --duplicate_penalty 0.6  --threads 20  --debug  --score_threshold 0.5 &> L1EEL101099-E3795-C-S162-L002-001/logs/binning/DASTool.log  ; mv L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_scaffolds2bin.txt L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/cluster_attribution.tsv &>> L1EEL101099-E3795-C-S162-L002-001/logs/binning/DASTool.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /data/atlasTest/.snakemake/log/2021-02-14T094311.893288.snakemake.log
[2021-02-14 11:51 CRITICAL] Command 'snakemake --snakefile /home/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/Snakefile --directory /data/atlasTest --jobs 80 --rerun-incomplete --configfile '/data/atlasTest/config.yaml' --nolock   --use-conda --conda-prefix /home/Desktop/atlas_databases/databases/conda_envs   binning  --resources mem=950 ' returned non-zero exit status 1.

---------------------------------------------error line ends-----------------------------------------------------------------------

When i check the log file mentioned above, I found those fault

-------------------------------log line--------------------------------------------

[1;33mThe host system is detected to have 1080 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b12 -c1
[0;39mstarting annotations of single copy cogs...
successfully finished
calculating contig lengths.

 *** caught segfault ***
address 0x7fab3e7c5164, cause 'invalid permissions'

Traceback:
 1: forderv(x, cols, sort = TRUE, retGrp = FALSE)
 2: setkeyv(x, cols, verbose = verbose, physical = physical)
 3: setkey(assembly_info, scaffold_name)
 4: cherry_pick(scaffolds_to_bins = scaffolds_to_bins, bin_set_labels = bin_set_labels,     bac_scg_matrix = bac_scg_matrix, arc_scg_matrix = arc_scg_matrix,     score_threshold = score_threshold, a = a, b = b, c = c, output_basename = output_basename,     length_table = length_table, use_N50 = use_Nfifty, write_bin_evals = write_bin_evals,     write_unbinned = write_unbinned, debug = debug)
An irrecoverable exception occurred. R is aborting now ...
/home/Desktop/atlas_databases/databases/conda_envs/594cd97a/bin/DAS_Tool: line 436: 2013529 Segmentation fault      (core dumped) Rscript $DIR\/src/DAS_Tool.R $scaffoldstobins $binlabels $contigs $bscg $ascg $outputbasename $score_threshold $threads $thisdir $length_table $write_bin_evals $write_unbinned $create_plots $debug $b_weight $c_weight
mv: cannot stat 'L1EEL101099-E3795-C-S162-L002-001/binning/DASTool/L1EEL101099-E3795-C-S162-L002-001_DASTool_scaffolds2bin.txt': No such file or directory

------------------------------------------log line ends-------------------------------------------------------

**Comment by SilasK** [comment]
If you run atlas alone on your big machine you should configure it to do so: https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#single-machine-execution


See also #344

The threads you specify you specify in the config file are per sample and therefore too high. Keep them in the range of 8-16 in order to execute multiple samples on the same time.

**Comment by boaty** [comment]
Thanks SilasK, I will re-run atlas with new parameters

**Comment by boaty** [comment]
Hi Silas,

I run the binning step with 8 cores and 500 GB mem, it works fine, thanks.
But is it normal? I found only 56 genomes after dereplication in genomes step, from 144 bins ?

Thanks
