### ISSUE TITLE
Error in creating directory

### ISSUE THREAD

**Issue by jonnatauriainen** [metagenome-atlas/atlas#372]
At rule cluster_genes I am facing attached error. I am running analysis via Finnish Centre for Scientific Computing (CSC). When running example data, analysis run smoothly but for my metagenomics jobs are analyzed until cluster genes. In my log file I get: cannot create directory ”/run/nvme/job_4721497”- permission denied.

Thank you for all your help!

<img width="1274" alt="kuva" src="https://user-images.githubusercontent.com/79629057/109121082-7987d980-774f-11eb-9947-d034f586aa93.png">

**Comment by SilasK** [comment]
Set the `tmpdir` in the config.yaml to a directory that is writeable. Often something like `/tmp`
