### ISSUE TITLE
missing taxonomy.tsv

### ISSUE THREAD

**Issue by ninashenker** [metagenome-atlas/atlas#376]
Hi Silas,

I am trying to use atlas_analyze for the results of my atlas output, but it seems I am missing several files - most importantly taxonomy.tsv (it's not under genome/checkm). I ran atlas by saying atlas run qc/assembly/ binning/genome/genecatalog, so separately instead of run all. I'm wondering if I say run all if the file will appear?

Is there a way for me to rerun atlas run all but skipping qc and assembly? Or another command to get the taxonomy.tsv?

Thanks!

**Comment by SilasK** [comment]
I think you need to install andbrun the small pipeline atlas_analyze. It's the scripts in atlas_analyze that produce the taxonomy.tsv file.

**Comment by SilasK** [comment]
I hope this solved the issue
