### ISSUE TITLE
error Resources have to be defined as name=value pairs

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#379]
Hi, 

When trying to run atlas on a single machine like so: 

```
atlas init --db-dir $HOME/atlas/DB --threads 48 -w $HOME $HOME/CLEAN_READS/test

atlas run qc --resources mem=125 --jobs 48 -w $HOME $HOME/CLEAN_READS/test -c $HOME/config.yaml

```

I get the following error message:

> [2021-04-19 13:06 INFO] Configuration file written to /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/config.yaml
> You may want to edit it using any text editor.
> [2021-04-19 13:06 INFO] Found 4 samples under /scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test
> [2021-04-19 13:06 INFO] Executing: snakemake --snakefile /user/gent/423/vsc42339/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN --jobs 48 --rerun-incomplete --configfile '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/config.yaml' --nolock   --use-conda --conda-prefix /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs   qc  --resources mem=125 /scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test 
> Resources have to be defined as name=value pairs.
> 
> [2021-04-19 13:06 CRITICAL] Command 'snakemake --snakefile /user/gent/423/vsc42339/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN --jobs 48 --rerun-incomplete --configfile '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/config.yaml' --nolock   --use-conda --conda-prefix /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs   qc  --resources mem=125 /scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test ' returned non-zero exit status 1.

As far as I can tell mem=125 is defined as name=value, and jobs is set as explained in [getting started](https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html)? Or is there something else wrong here? there doesn't seem to be a snakemake log file, so I cannot share one

Best,
Sam

**Comment by SilasK** [comment]
You got the `$HOME/CLEAN_READS/test` too much which was then interpreted as a key without value. (Is there an error in the docs?)

The `-c $HOME/config.yaml` is not necessary if the config is in the working dir. I however suggest to use another dir as working directory at least for other runs.

The command should work. 

`atlas run qc --resources mem=125 --jobs 48 -w $HOME`

**Comment by slambrechts** [comment]
Thanks! No error in the docs, my mistake, I specified the working directory followed by the directory were the reads are located, but didn't realize you only have to do that once, i.e. when running `atlas init`
