### ISSUE TITLE
error during bbmerge

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#381]
Hi,

When running 

`atlas run assembly --resources mem=732 -w $HOME/CLEAN_READS/test --omit-from run_spades
`

I seem to get the following error during bbmerge:

> "one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode"

full output:

> [2021-04-20 07:27 INFO] Executing: snakemake --snakefile /user/gent/423/vsc42339/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test  --rerun-incomplete --configfile '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/config.yaml' --nolock   --use-conda --conda-prefix /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs   assembly  --resources mem=732 --omit-from run_spades 
> Building DAG of jobs...
> Using shell: /bin/bash
> Provided cores: 1 (use --cores to define parallelism)
> Rules claiming more threads will be scaled down.
> Provided resources: mem=732
> Job counts:
> 	count	jobs
> 	4	error_correction
> 	4	init_pre_assembly_processing
> 	4	merge_pairs
> 	4	passtrough_se_merged
> 	16
> 
> [Tue Apr 20 07:27:54 2021]
> localrule init_pre_assembly_processing:
>     input: DV-OTC13-B/sequence_quality_control/DV-OTC13-B_QC_R1.fastq.gz, DV-OTC13-B/sequence_quality_control/DV-OTC13-B_QC_R2.fastq.gz, DV-OTC13-B/sequence_quality_control/DV-OTC13-B_QC_se.fastq.gz
>     output: DV-OTC13-B/assembly/reads/QC_R1.fastq.gz, DV-OTC13-B/assembly/reads/QC_R2.fastq.gz, DV-OTC13-B/assembly/reads/QC_se.fastq.gz
>     log: DV-OTC13-B/logs/assembly/init.log
>     jobid: 35
>     wildcards: sample=DV-OTC13-B
>     resources: mem=60, time=5
> 
> [33mJob counts:
> 	count	jobs
> 	1	init_pre_assembly_processing
> 	1[0m
> [Tue Apr 20 07:27:55 2021]
> Finished job 35.
> 1 of 16 steps (6%) done
> 
> [Tue Apr 20 07:27:55 2021]
> rule error_correction:
>     input: DV-OTC13-B/assembly/reads/QC_R1.fastq.gz, DV-OTC13-B/assembly/reads/QC_R2.fastq.gz, DV-OTC13-B/assembly/reads/QC_se.fastq.gz
>     output: DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr_se.fastq.gz
>     log: DV-OTC13-B/logs/assembly/pre_process/error_correction_QC.log
>     jobid: 18
>     benchmark: logs/benchmarks/assembly/pre_process/DV-OTC13-B_error_correction_QC.txt
>     wildcards: sample=DV-OTC13-B, previous_steps=QC
>     resources: mem=60, java_mem=51, time=5
> 
> Activating conda environment: /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/a6b9691d
> Removing temporary output file DV-OTC13-B/assembly/reads/QC_se.fastq.gz.
> Removing temporary output file DV-OTC13-B/assembly/reads/QC_R1.fastq.gz.
> Removing temporary output file DV-OTC13-B/assembly/reads/QC_R2.fastq.gz.
> [Tue Apr 20 08:35:53 2021]
> Finished job 18.
> 2 of 16 steps (12%) done
> 
> [Tue Apr 20 08:35:53 2021]
> rule merge_pairs:
>     input: DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz
>     output: DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz
>     log: DV-OTC13-B/logs/assembly/pre_process/merge_pairs_QC.errorcorr.log
>     jobid: 5
>     benchmark: logs/benchmarks/assembly/pre_process/merge_pairs_QC.errorcorr/DV-OTC13-B.txt
>     wildcards: sample=DV-OTC13-B, previous_steps=QC.errorcorr
>     resources: mem=60, java_mem=51, time=5
> 
> [33mJob counts:
> 	count	jobs
> 	1	merge_pairs
> 	1[0m
> [32m[Tue Apr 20 09:13:11 2021][0m
> [31mError in rule merge_pairs:[0m
> [31m    jobid: 0[0m
> [31m    output: DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz[0m
> [31m    log: DV-OTC13-B/logs/assembly/pre_process/merge_pairs_QC.errorcorr.log (check log file(s) for error message)[0m
> [31m    conda-env: /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/a6b9691d[0m
> [31m    shell:
>         
>         bbmerge.sh -Xmx51G threads=1             in1=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz             outmerged=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz             outu=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz outu2=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz             ecct iterations=5 k=62             extend2=40 2> DV-OTC13-B/logs/assembly/pre_process/merge_pairs_QC.errorcorr.log
>         
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)[0m
> [31m[0m
> [31mExiting because a job execution failed. Look above for error message[0m
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/.snakemake/log/2021-04-20T072752.633121.snakemake.log
> [2021-04-20 09:13 CRITICAL] Command 'snakemake --snakefile /user/gent/423/vsc42339/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test  --rerun-incomplete --configfile '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/CLEAN_READS/test/config.yaml' --nolock   --use-conda --conda-prefix /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs   assembly  --resources mem=732 --omit-from run_spades ' returned non-zero exit status 1.
>

**Comment by SilasK** [comment]
What does the `DV-OTC13-B/logs/assembly/pre_process/merge_pairs_QC.errorcorr.log` state? 

Maybe you want to use the command line argument `--no-temp` in order not to delete the temporary intermediate files (e.g. the merged reads)?

**Comment by slambrechts** [comment]
ok thank you, ran out of memory apparently:

> java -Djava.library.path=/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/a6b9691d/opt/bbmap-37.99/jni/ -ea -Xmx51G -Xms51G -cp /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/a6b9691d/opt/bbmap-37.99/current/ jgi.BBMerge -Xmx51G threads=1 in1=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz outmerged=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz outu=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz outu2=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz ecct iterations=5 k=62 extend2=40
> Executing jgi.BBMerge [-Xmx51G, threads=1, in1=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz, outmerged=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz, outu=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, outu2=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, ecct, iterations=5, k=62, extend2=40]
> Version 37.99 [-Xmx51G, threads=1, in1=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz, outmerged=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_me.fastq.gz, outu=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, outu2=DV-OTC13-B/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, ecct, iterations=5, k=62, extend2=40]
> 
> Set threads to 1
> Executing assemble.Tadpole2 [in=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz, branchlower=3, branchmult1=20.0, branchmult2=3.0, mincountseed=3, mincountextend=2, minprob=0.5, k=62, prealloc=false, prefilter=0, ecctail=false, eccpincer=false, eccreassemble=true]
> Version 37.99 [in=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz, branchlower=3, branchmult1=20.0, branchmult2=3.0, mincountseed=3, mincountextend=2, minprob=0.5, k=62, prealloc=false, prefilter=0, ecctail=false, eccpincer=false, eccreassemble=true]
> 
> Using 1 threads.
> Executing ukmer.KmerTableSetU [in=DV-OTC13-B/assembly/reads/QC.errorcorr_R1.fastq.gz, in2=DV-OTC13-B/assembly/reads/QC.errorcorr_R2.fastq.gz, branchlower=3, branchmult1=20.0, branchmult2=3.0, mincountseed=3, mincountextend=2, minprob=0.5, k=62, prealloc=false, prefilter=0, ecctail=false, eccpincer=false, eccreassemble=true]
> 
> Initial:
> Ways=31, initialSize=128000, prefilter=f, prealloc=f
> Memory: max=54760m, free=54735m, used=25m
> 
> Estimated kmer capacity: 	1022013718
> After table allocation:
> Memory: max=54760m, free=54651m, used=109m
> 
> java.lang.OutOfMemoryError: Java heap space
> 	at shared.KillSwitch.allocLong2D(KillSwitch.java:234)
> 	at ukmer.AbstractKmerTableU.allocLong2D(AbstractKmerTableU.java:196)
> 	at ukmer.HashArrayU1D.resize(HashArrayU1D.java:187)
> 	at ukmer.HashArrayU1D.incrementAndReturnNumCreated(HashArrayU1D.java:75)
> 	at ukmer.HashBufferU.dumpBuffer_inner(HashBufferU.java:196)
> 	at ukmer.HashBufferU.dumpBuffer(HashBufferU.java:168)
> 	at ukmer.HashBufferU.incrementAndReturnNumCreated(HashBufferU.java:57)
> 	at ukmer.KmerTableSetU$LoadThread.addKmersToTable(KmerTableSetU.java:576)
> 	at ukmer.KmerTableSetU$LoadThread.run(KmerTableSetU.java:511)
> 
> This program ran out of memory.
> Try increasing the -Xmx flag and using tool-specific memory-related parameters.

Because this is a rather large soil sample (81M reads) I increased the `large memory` and `assembly memory` in the config.yaml file to the maximum limit of the machine (because I read in [344](https://github.com/metagenome-atlas/atlas/issues/344) that somebody needed up to 900 GB for the tadpole step). But I kept the memory and threads specs for the `most jobs` parameters at default:

```
# threads and memory (GB) for most jobs especially from BBtools, which are memory demanding
threads: 36
mem: 60
```

To the contrary of what I read in [344](https://github.com/metagenome-atlas/atlas/issues/344), it does not seem like tadpole used a lot of memory, only 54 GB! So maybe it's rather the mem for most jobs that needs to be set as high as possible for very large samples?

**Comment by SilasK** [comment]
tadpole and other bbmap use the mem for most tools. (actually bbmap are used in most of the steps)

Set large_mem to 110GB and the mem: to 120 or higher.

**Comment by slambrechts** [comment]
ok interesting, thanks for the info. Out of curiosity, any idea how it's possible that one big soil sample needs 900 GB of RAM, and another only 53GB?

**Comment by SilasK** [comment]
Try how many kmers you have there: 


```
loglog.sh in=reads_errcorrected_R1.fastq.gz ins=reads_errorcorrected_R2.fastq.gz khist=khist.txt
```

the loglog.sh is part of bbmap shipped with atlas.


You may also be interested in #289
