### ISSUE TITLE
Running atlas:

### ISSUE THREAD

**Issue by masun** [metagenome-atlas/atlas#383]
Dear Silas,

I am trying to run atlas on the cluster and I am getting the following error, which I don't find it here.

AttributeError in line 37 of /gpfs1/.../.../tools/atlas/atlasenv/lib/python3.6/site-packages/atlas/rules/assemble.snakefile:
'function' object has no attribute 'deepcopy'
  File "/gpfs1/.../.../tools/atlas/atlasenv/lib/python3.6/site-packages/atlas/Snakefile", line 178, in <module>
  File "/gpfs1/.../.../tools/atlas/atlasenv/lib/python3.6/site-packages/atlas/rules/assemble.snakefile", line 37, in <module>

Command: atlas run all --profile cluster --jobs 16 
What should I do?

Thank you

**Comment by SilasK** [comment]
Could you just verify that you use a up to date atlas and python 3.5 - 3.7

**Comment by masun** [comment]
Yes, I do. 
I am using python 3.6.6 and today morning, I have downloaded Atlas
Thank you for your prompt reply
Masun

**Comment by masun** [comment]
My samples.tsv has the following format:, is it ok?
Reads_raw_R1	Reads_raw_R2	BinGroup
SRR1	/gpfs1/.../.../users/.../co/raw_fast/SRR1_1.fastq	/gpfs1/.../.../users/.../co/raw_fast/SRR1_2.fastq	g1
SRR2	/gpfs1/.../.../users/.../co/raw_fast/SRR2_1.fastq	/gpfs1/.../.../users/.../co/raw_fast/SRR2_2.fastq	g1
SRR3	/gpfs1/.../.../users/.../co/raw_fast/SRR3_1.fastq	/gpfs1/.../.../users/.../co/raw_fast/SRR3_2.fastq	g2
SRR4	/gpfs1/.../.../users/.../co/raw_fast/SRR4_1.fastq	/gpfs1/.../.../users/.../co/raw_fast/SRR4_2.fastq	g2

**Comment by SilasK** [comment]
sample table should be fine if there are tabs between the columns. 

Could you just verify the version of atlas. 
e.g. `conda list metagenome-atlas` The bug seems like an error I fixed in an older version.

**Comment by masun** [comment]
version 2.1.1

**Comment by SilasK** [comment]
Try to use mamba and update to version 2.4.5

**Comment by masun** [comment]
Thank you SilasK. It works, but I have the following error. what should I do?

Building DAG of jobs...
MissingInputException in line 25 of /gpfs1/.../../tools/atlas/atlasenv/lib/python3.6/site-packages/atlas/rules/genecatalog.snakefile:
Missing input files for rule concat_genes:
genomes/annotations/orf2genome.tsv

Thank you very much
Masun

**Comment by SilasK** [comment]
Ah, I assume that you kept the same config file from the first init. I'ts not overwritten. 

I suggest you to delete the config file and to redo an init. 

otherwise you can set 
```
genecatalog:
  source: contigs  
```

I hope you get it working.

**Comment by masun** [comment]
Thank you Silas,
Now it is downloading and installing the remote packages, but why after creating ../python3.6/site-packages/atlas/envs/report.yaml , it takes a long time, more than two hours. Is this ok? or there is something wrong!

**Comment by SilasK** [comment]
The report code needs some outdated dependencies. I try to solve this in #354
