### ISSUE TITLE
No module named "Snakemake"

### ISSUE THREAD

**Issue by masun** [metagenome-atlas/atlas#384]
Dear Silas,

Now I am getting the following error. What should I do?. 
Thank you

Traceback (most recent call last):
  File "/gpfs1/.../.../tools/atlas/cluster/scheduler.py", line 8, in <module>
    from snakemake.logging import logger
ModuleNotFoundError: No module named 'snakemake'
Error submitting jobscript (exit code 1):

**Comment by SilasK** [comment]
Could you check the version of snakemake you are using?

`snakemake --version``

As fix I suggest to open the file `/gpfs1/.../.../tools/atlas/cluster/scheduler.py`

And comment line 8 and 12. 
And uncomment line 11

**Comment by masun** [comment]
Thank you, and I come back to you

**Comment by SilasK** [comment]
Does the error persist?

**Comment by SilasK** [comment]
I hope it's solved otherwise don't hesitate to comment.
