### ISSUE TITLE
How to prepare the input file with assembled files' paths to run Binning directly? 

### ISSUE THREAD

**Issue by masun** [metagenome-atlas/atlas#386]
Dear SilasK,

I have to questions:
1) I have my metagenome files assembled by metaspace, so I wonder how to indicate to Atlas where they are to continue with the process (binning)? and Should I format the samples.tsv file?
2) When I run "atlas run binning", do the Atlas continue with the next steps automatically? or should I run step by step manually?

Thank you
Masun

**Comment by SilasK** [comment]
Do I see it correctly that this issue is a duplicate of #377

If you have an assembly and qc reads you can follow this instruction there.

**Comment by SilasK** [comment]
What is metaspace?
