### ISSUE TITLE
Multi-lane readfiles

### ISSUE THREAD

**Issue by MalbertR** [metagenome-atlas/atlas#389]
I noticed when I ran the pipeline on a Novaseq run with 2 lanes per sample, that the pipeline did treat these lanes as separate samples. Now, this isn't necessarily a bug or a huge issue (the read files of the different lanes can be simply concatenated into 1 file), however it would've been nice to know in advance that the pipeline would not be able to handle these. The pipeline took about a week to sort of complete, so it would've been nice if I knew about this in advance :( Maybe there is a "warning" for this somewhere and I completely missed it? 

And since I'm already posting about it, I'm going to be bold and ask for this feature of dealing with multilane samples to be added to the pipeline in the future :D

**Comment by SilasK** [comment]
I understand your frustration. Waiting for so long and not getting the results you want.

There is a small warning after atlas into that shows please check the sample file.

I had multilane support but then I didn’t know what to do whit the different lanes. How would you compare that they are the same or different? Can you get some useful information for it?

Obviously I can create a wrapper that concatenates the files but I’m not sure if I can make a tool that suits everyone.

I suggest you to concatenate the QC reads. And restart assembly. You can concantenate directly the fast.gz files and probably drop the single end files.

**Comment by MalbertR** [comment]
So, the name of the files from different lanes are pretty much the same except for the L-number. Example: 

**Sample ID: 2020-04-IBD-S0026**

Lane1:
2020-04-IBD-S0026_BHYGT3DMXX_S19_**L001**_R1_001.fastq.gz
2020-04-IBD-S0026_BHYGT3DMXX_S19_**L001**_R2_001.fastq.gz

Lane2: 
2020-04-IBD-S0026_BHYGT3DMXX_S19_**L002**_R1_001.fastq.gz
2020-04-IBD-S0026_BHYGT3DMXX_S19_**L002**_R2_001.fastq.gz

So basically just simply concatenating XXX_L00*_R1_XXX to XXX_L00*_R1_XXX. And I put wildcard ("*"), since samples coming from NextSeq for example, can also have data splitted into up to 4 lanes. So, it's not in all cases only L001 and L002. But on the flip side, there will also be times were there's only L001. 

Thanks for the suggestion. That should indeed save some time!

**Comment by SilasK** [comment]
I also suggest you to simplify the sample name. I find it much easier if the sample name is short. Because then the config will be named sample_1 ...

And genes sample_1_1 ...
