### ISSUE TITLE
Wrong checksum for eggnog.db v. 5.0.2

### ISSUE THREAD

**Issue by johanneswerner** [metagenome-atlas/atlas#391]
Hello, 
I wanted to update the databases and therefore run `atlas download ...` into a new folder. 

However, I get a checksum mismatch error, see below

```
Error in rule verify_eggNOG_files:
    jobid: 0
    output: /data_iow/db_atlas/EggNOGV2/checksum_checked

RuleException:
FileNotFoundError in line 117 of /home/ubuntu/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/rules/download.snakefile:
[Errno 2] Invalid checksum: '/data_iow/db_atlas/EggNOGV2/eggnog.db'
  File "/home/ubuntu/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/rules/download.snakefile", line 117, in __rule_verify_eggNOG_files
  File "/home/ubuntu/miniconda3/envs/atlas/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

I checked that eggnog is downloading the current release (http://eggnog5.embl.de/download/emapperdb-5.0.2/eggnog.db.gz) earlier in the logs and redownloaded it manually, although I obtained twice the same MD5sum (which I think would be unlikely if the download interrupted somewhere in the middle). 

This is the checksum I obtained `065763df8f1593dc6d08c5ce06401fcf`, however in `.../atlas/lib/python3.6/site-packages/atlas/rules/download.snakefile`, this is the checksum that is expected: 

```bash
"eggnog.db": "7923d3bb7eca8e0e8f122be4b5ca6997" # line 39
```

Could you please look into that and check if the hashsum is still correct? (And if this is the case, maybe you have an idea why I obtained the wrong hashsum twice and how to avoid it as well? ;-) )

Thank you very much!

**Comment by SilasK** [comment]
I waited because eggNOG mapper did some big changes. But unfortunately the download is not version specific. 

I suggest to run `atlas run genomes` which will get you all the mags and don't rely on eggNOG mapper to annotate genes.

**Comment by soilmicrobiome** [comment]
I am running atlas on an HPC (version 2.5.0) whilst running "atlas run all" it fails at the eggnog step.  From my error message I think i am having the same issues as above?  if so, would the solution be the same as above  -- "atlas run genomes"?

### slurm output:

> [Wed Jul  7 09:27:58 2021]
> localrule verify_eggNOG_files:
>     input: /project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog.db, /project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog_proteins.dmnd
>     output: /project/6010084/databases_software/atlas/databases/EggNOGV2/checksum_checked
>     jobid: 150
>     resources: mem=187, time=71

> ESC[33mJob counts:
>         count   jobs
>         1       verify_eggNOG_files
>         1ESC[0m
> ESC[32m[Wed Jul  7 09:29:56 2021]ESC[0m
> ESC[31mError in rule verify_eggNOG_files:ESC[0m
> ESC[31m    jobid: 0ESC[0m
> ESC[31m    output: /project/6010084/databases_software/atlas/databases/EggNOGV2/checksum_checkedESC[0m
> ESC[31mESC[0m
> ESC[31mRuleException:
> FileNotFoundError in line 117 of /cvmfs/soft.hpc.ca/easybuild/software/2020/avx2/Compiler/intel2020/metagenome-atlas/2.5.0/lib/python3.6/site-packages/atlas/rules/download.snakefile:
> [Errno 2] Invalid checksum: '/project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog.db'
>   File "/cvmfs/soft.hpc.ca/easybuild/software/2020/avx2/Compiler/intel2020/metagenome-atlas/2.5.0/lib/python3.6/site-packages/atlas/rules/download.snakefile", line 117, in __rule_verify_eggNOG_files
>   File "/cvmfs/soft.hpc.ca/easybuild/software/2020/avx2/Core/python/3.6.10/lib/python3.6/concurrent/futures/thread.py", line 56, in runESC[0m
> ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /project/6010084/user/atals_test_data/.snakemake/log/2021-07-07T085919.394446.snakemake.log
> Note the path to the log file for debugging.
> Documentation is available at: https://metagenome-atlas.readthedocs.io
> Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
> [2021-07-07 09:29 CRITICAL] Command 'snakemake --snakefile /cvmfs/soft.hpc.ca/easybuild/software/2020/avx2/Compiler/intel2020/metagenome-atlas/2.5.0/lib/python3.6/site-packages/atlas/Snakefile --directory /project/6010084/user/atals_test_data  --rerun-incomplete --configfile '/project/6010084/user/atals_test_data/config.yaml' --nolock   --use-conda --conda-prefix /project/6010084/databases_software/atlas/databases/conda_envs   all  --cores 24 ' returned non-zero exit status 1.
> (END)

### snakemake log output:

> localrule download_eggNOG_files:
>     output: /project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog.db, /project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog_proteins.dmnd
>     jobid: 149
>     resources: mem=187, time=71
> 
> [Wed Jul  7 09:09:15 2021]
> Finished job 66.
> 13 of 54 steps (24%) done
> Activating conda environment: /project/6010084/databases_software/atlas/databases/conda_envs/f70a0c49
> [Wed Jul  7 09:27:58 2021]
> Finished job 149.
> 14 of 54 steps (26%) done
> 
> [Wed Jul  7 09:27:58 2021]
> localrule verify_eggNOG_files:
>     input: /project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog.db, /project/6010084/databases_software/atlas/databases/EggNOGV2/eggnog_proteins.dmnd
>     output: /project/6010084/databases_software/atlas/databases/EggNOGV2/checksum_checked
>     jobid: 150
>     resources: mem=187, time=71
> 
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /project/6010084/user/atals_test_data/.snakemake/log/2021-07-07T085919.394446.snakemake.log
> (END)
>

**Comment by SilasK** [comment]
The comments above mean that the changes leading up to v2.6a2 solved the issue. 

If you are mainly interested in the genomes you can run `atlas run genomes` and skip this error. 
If you want the eggNOG annotations I recommend updating to v2.6a2 . In theory you can continue where you left off with v2.5 but It could be any way better to run `atlas run genomes` first.
