### ISSUE TITLE
download-db.sh error

### ISSUE THREAD

**Issue by kazumaxneo** [metagenome-atlas/atlas#392]
Hi,
I'm getting an error downloading the database. It seems to be caused by a change in the URL of the GTDB archive.
I rewrote the 6th line of "download-db.sh" script as follows

wget https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz -P ${GTDBTK_DATA_PATH}
=> 
wget https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/gtdbtk_r89_data.tar.gz -P ${GTDBTK_DATA_PATH}

Now it works. 
Is this the correct way to fix it?

Here is the first error message I encountered in docker environment: metagenomeatlas/atlas: latest.
Xeon V4 2680 dual
512GB memory

========================
[Wed May 12 03:03:47 2021]
Error in rule download_gtdb:
    jobid: 121
    output: /databases/GTDB-TK/downloaded_success
    conda-env: /databases/conda_envs/27b2c927
    shell:
        GTDBTK_DATA_PATH=/databases/GTDB-TK ;  download-db.sh ;
        (one of the commands exited with non-zero exit code; note that
snakemake uses bash strict mode!)

**Comment by jmtsuji** [comment]
@kazumaxneo I believe this issue was just addressed in #388 -- GTDB just updated their database version. Are you running the new release of ATLAS, version 2.5.0? This should solve your problem, in theory.

**Comment by kazumaxneo** [comment]
Dear jmtsuji.

Thanks for your reply.
I used the latest image available on docker hub, which was version 2.3.0.
<https://hub.docker.com/r/metagenomeatlas/atlas/tags?page=1&ordering=last_updated>

I used docker image because it was taking too much time to create the new conda environment.
So, I'll try again using version 2.5.0.

Thank you for the fast reply.

**Comment by jmtsuji** [comment]
@kazumaxneo Ah, I see. Yes, it is slow to install ATLAS using conda. If possible, I recommend installing ATLAS using [mamba](https://github.com/mamba-org/mamba) instead, as mentioned in [the ATLAS docs](https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html).

For example:
```bash
conda create -y -n atlas -c conda-forge mamba
conda activate atlas
mamba install -y -c bioconda -c conda-forge metagenome-atlas
```

This gets everything set up much faster. Note that you might need to specify `python=3.6` when running `conda create -y -n atlas -c conda-forge mamba` if it does not work the first time.

**Comment by kazumaxneo** [comment]
@jmtsuji 
Thanks!
I'll try the "mamba" command instead.

**Comment by jmtsuji** [comment]
@kazumaxneo Okay, sounds good. For now, I will close this issue, but if you have further problems, you can re-open this issue or create a new one. All the best with ATLAS!
