### ISSUE TITLE
Complete taxonomic lineage of Genecatalog

### ISSUE THREAD

**Issue by CedricMidoux** [metagenome-atlas/atlas#396]
Hi,

I can acces to taxonomic affiliation of Genecatalog in the 5th colum of Genecatalog/annotations/eggNog.tsv.gz (like #334)
But is there a easy way to access to the full taxonomic lineage ?

For example :
```
Query	Taxonomy
Gene17901443	Clostridiaceae
Gene17901444	Tenericutes
```

to :

```
Query	tax_id	superkingdom	phylum	class	order	family	genus	species
Gene17901443	31979	Bacteria	Firmicutes	Clostridia	Eubacteriales	Clostridiaceae	NA	NA
Gene17901444	544448	Bacteria	Tenericutes	NA	NA	NA	NA	NA
```

 Thanks a lot in advance !

**Comment by SilasK** [comment]
Sorry, best if you ask the authors from eggNOGDB. I don't know which taxonomy they are using. 
Maybe using ete3 in python or the new [NCBI Taxonomy toolkit](https://twitter.com/shenwei356/status/1382950018382897153) can help you to go from name to lineage. 

http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html


We are working on getting contig-level taxonomy.
