### ISSUE TITLE
Short read data types accepted by ATLAS

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#397]
Hello @SilasK ,

A quick question: until now, I have only worked with Illumina-based short read sequencing metagenome data. However, a new sequencing center I am now working with (nearby my new institute) uses MGI's DNBSEQ-G400 for short read sequencing instead. Based on your experience, do you expect data from this alternative short read sequencing method to be compatible with ATLAS (especially QC and error correction)?

After a quick discussion with @LeeBergstrand, it seems like the answer is probably yes, if all QC / error correction tools are k-mer based and not using sequencer-specific error profile info. In that case, so long as the read error rate is low and the errors are random, can ATLAS theoretically accept short read data generated by any method?

Thanks a bunch.

**Comment by SilasK** [comment]
Atlas mainly uses bbmap tools and spades or megahit. I don't think any of those use platform-dependent methods. As long as you get fastq files with the newest format. Even if the fastq format is not the newest this can be solved. 

You may want to add platform-specific adapters that will be filtered out but It is not necessary.

**Comment by jmtsuji** [comment]
@SilasK Thanks for your opinion and your quick response. Good suggestion that platform-specific adaptor sequences could be helpful to add when I run QC.
