### ISSUE TITLE
Problems with initialize_qc

### ISSUE THREAD

**Issue by johanneswerner** [metagenome-atlas/atlas#400]
With Atlas v. 2.6a2, I have problems with all my `initialize_qc` steps: 

It always returns this error message, but the number of reads are the same in both files. 

```bash
Set INTERLEAVED to false
Set threads to 4
Input is being processed as paired
pigz: resource unavailable (pigz.c:3393:create)
pigz: resource unavailable (pigz.c:3392:create)
java.lang.AssertionError: 
There appear to be different numbers of reads in the paired input files.
The pairing may have been corrupted by an upstream process.  It may be fixable by running repair.sh.
java.lang.AssertionError: 
There appear to be different numbers of reads in the paired input files.
The pairing may have been corrupted by an upstream process.  It may be fixable by running repair.sh.
        at stream.ConcurrentGenericReadInputStream.pair(ConcurrentGenericReadInputStream.java:497)
        at stream.ConcurrentGenericReadInputStream.readLists(ConcurrentGenericReadInputStream.java:362)
        at stream.ConcurrentGenericReadInputStream.run0(ConcurrentGenericReadInputStream.java:206)
        at stream.ConcurrentGenericReadInputStream.run(ConcurrentGenericReadInputStream.java:182)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Any ideas what `pigz: resource unavailable (pigz.c:3393:create)` could indicate? Thank you very much.

**Comment by SilasK** [comment]
I don't know. I think the error comes from:

`There appear to be different numbers of reads in the paired input files.`

Apparently there is a problem with some your input fastqs files. 
 It may be fixable by running repair.sh.

**Comment by SilasK** [comment]
Maybe it's due to the pigz (paralell gzip) you can try to run `reformat.sh in=sample_R1.fastq.gz in2=sample_R2.fastq.gz` 
without pigz by default.

**Comment by johanneswerner** [comment]
It was a restart of the dataset I had problems with as described in #398 and #401. I also checked, the number of reads is the same in forward and reverse files. I am not sure what the error caused, but since the dataset now runs well (after downgrading snakemake, see https://github.com/metagenome-atlas/atlas/issues/401#issuecomment-855461536), I will not rerun the dataset. Still not sure, what is causing it. If this happens for my next dataset as well, I will have check if `pigz` is involved.
