### ISSUE TITLE
Error in rule error_correction

### ISSUE THREAD

**Issue by rbis3636** [metagenome-atlas/atlas#403]
jobid: 29
    output: SBS/assembly/reads/QC.errorcorr_R1.fastq.gz, SBS/assembly/reads/QC.errorcorr_R2.fastq.gz, SBS/assembly/reads/QC.errorcorr_se.fastq.gz
    log: SBS/logs/assembly/pre_process/error_correction_QC.log (check log file(s) for error message)
    conda-env: /home/microlab/atlas_database/conda_envs/aa23247dd702ddbb985cc51c8c607499
    shell:
        
        tadpole.sh -Xmx51G             prealloc=1             in1=SBS/assembly/reads/QC_R1.fastq.gz,SBS/assembly/reads/QC_se.fastq.gz in2=SBS/assembly/reads/QC_R2.fastq.gz             out1=SBS/assembly/reads/QC.errorcorr_R1.fastq.gz,SBS/assembly/reads/QC.errorcorr_se.fastq.gz out2=SBS/assembly/reads/QC.errorcorr_R2.fastq.gz             mode=correct             threads=80             ecc=t ecco=t 2>> SBS/logs/assembly/pre_process/error_correction_QC.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by SilasK** [comment]
Could you please check the  Log files.
SBS/logs/assembly/pre_process/error_correction_QC.log

**Comment by rbis3636** [comment]
[error_correction_QC.log](https://github.com/metagenome-atlas/atlas/files/6692319/error_correction_QC.log)

**Comment by rbis3636** [comment]
please check the file. i can not understand error

**Comment by SilasK** [comment]
It's a simple out of memory error.

Maybe the 80gb specified in the config file are not enough. 

What I rather think is that multiple jobs are run in parallel by atlas (or other programs).
I think what you need to do is to specify the max memory available. Check the docs for single machine execution.
