### ISSUE TITLE
Beginner

### ISSUE THREAD

**Issue by laineybright** [metagenome-atlas/atlas#405]
Hello! I'm only a beginner in bioinformatics. As I am writing my review, I came across ATLAS and it's perfect for my study. I already have metagenome contigs (fasta files), but i'm not sure how I can use these files in ATLAS for binning and annotation. I already installed anaconda, installed metagenome-atlas, and mamba. Do you have any tutorial that I can follow? Thank you so much! I hope you can help me. 

Btw, I also tried the example data from the ATLAS documentation but I can't execute the `conda init` command and always get the `No files found in path/to/fastq` error. 

Thank you!

**Comment by SilasK** [comment]
Hey, @laineybright Thank you for trying out Atlas. I tried it to make as simple as possible to get started. 

First, be aware of all the resources I have to understand learn Atlas:
1. The Documentation of Atlas
2. [Video conference](https://www.youtube.com/watch?v=k9nkPvY4wBU)
3. [My Thesis should be a good introduction to genome-resolved metagenomics](https://silask.github.io/post/phd-thesis/)
4. [Atlas Tutorial, there are two parts for it](https://github.com/metagenome-atlas/Tutorial)

So about your problems. Atlas is supposed to work with fastq reads. Do you have those? Then you should be able to use `atlas init`. 

You said you have fast files. Do you have one for each sample? There is a hacky way to include them into atlas #377

**Comment by laineybright** [comment]
Thank you for this! atlas init finally worked. But after running the atlas this error is always what I get.

Also, I realized that I only have fasta files of my contigs, is there a way how I can use them? Thank you so much!

![Capture](https://user-images.githubusercontent.com/70334841/123463741-75e16200-d61e-11eb-8a64-c355415dc449.JPG)

**Comment by SilasK** [comment]
Hey @laineybright ,
If you only have the fasta then I fear atlas is not the right tool for you. 
Atlas is all about binning and getting genomes from the assembly. In theory binning can be achieved without the reads, but this is very difficult. 

What I would do is predicting genes from your assembly using 'prodigal' and then annotate them with eggNOG mapper.

Don't you have access to the initial reads? Or are they from a public repository?
