### ISSUE TITLE
Error in rule download_gtdb

### ISSUE THREAD

**Issue by SF-Dragon** [metagenome-atlas/atlas#407]
I am a researcher who is about to start using atlas.
When I did a test run, I got the following error. I would be very grateful if you could give me some advice on how to deal with this.

`Error in rule download_gtdb:
    jobid: 130
    output: /home/user/databases/GTDB_V06/downloaded_success
    conda-env: /home/user/databases/conda_envs/cc99fe8f53e842fd9a75a91f3d8e1930
    shell:
        GTDBTK_DATA_PATH=/home/user/databases/GTDB_V06 ;  download-db.sh ;
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)`

**Comment by SilasK** [comment]
Thanky ou for trying out atlas

It seems to me that you are using an older version of atlas. In the newest one there is a `mkdir` in the command which might solve your error.  

Use mamba and install the newest atlas version 2.6a2

`mamba install metagenome-atlas=2.6a2` You don't need to restart you can simply continue where you left off. 


If the error persists try to look for an error message put out by the bash script which is printed in the stdout.

**Comment by SilasK** [comment]
I hope it's solved otherwise don't hesitate to comment.
