### ISSUE TITLE
Error in Rule Pileup Prefilter

### ISSUE THREAD

**Issue by JLammons14** [metagenome-atlas/atlas#409]
I have been running Atlas using the cookiecutter scheduler, with not too much trouble except with the QC_report. However when running rule pileup_prefilter, Im having some problems, and not quite sure how to troubleshoot this problem. Looking at our clustervisor, the nodes these jobs are being allocated to are not doing any heavy computing, and eventually the jobs time out. I copied over the error messages I've been getting below:

Error in rule pileup_prefilter:
    jobid: 637
    output: K18D55-S35-L003-001/assembly/contig_stats/prefilter_coverage_stats.txt
    log: K18D55-S35-L003-001/logs/assembly/post_process/pilup_prefilter_contigs.log (check log file(s) for error message)
    conda-env: /mnt/beegfs/home/jlamm1/databases/conda_envs/34107f8b9bb538f6657b7ec6c88221e7
    shell:
        
            pileup.sh ref=K18D55-S35-L003-001/assembly/K18D55-S35-L003-001_prefilter_contigs.fasta in=K18D55-S35-L003-001/sequence_alignment/alignment_to_prefilter_contigs.sam                 threads=40                 -Xmx85G                 covstats=K18D55-S35-L003-001/assembly/contig_stats/prefilter_coverage_stats.txt                 concise=t                 secondary=t 2> K18D55-S35-L003-001/logs/assembly/post_process/pilup_prefilter_contigs.log
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 21524

Error executing rule pileup_prefilter on cluster (jobid: 637, external: 21524, jobscript: /mnt/beegfs/home/jlamm1/.snakemake/tmp.1toi_o2z/snakejob.pileup_prefilter.637.sh). For error details see the cluster log and the log files of the involved rule(s).

**Cluster Log error message:** 

localrules directive specifies rules that are not present in the Snakefile:
	verify_eggNOG_files

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 40
Rules claiming more threads will be scaled down.
Singularity containers: ignored

[Thu Jul  1 21:40:18 2021]
rule pileup_prefilter:
    input: K19D27-S39-L004-001/assembly/K19D27-S39-L004-001_prefilter_contigs.fasta, K19D27-S39-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam
    output: K19D27-S39-L004-001/assembly/contig_stats/prefilter_coverage_stats.txt
    log: K19D27-S39-L004-001/logs/assembly/post_process/pilup_prefilter_contigs.log
    jobid: 0
    wildcards: sample=K19D27-S39-L004-001
    threads: 40
    resources: mem_mb=41761, disk_mb=41761, tmpdir=/tmp, mem=100, java_mem=85, time=5

Activating conda environment: /mnt/beegfs/home/jlamm1/databases/conda_envs/34107f8b9bb538f6657b7ec6c88221e7
slurmstepd: error: *** JOB 21527 ON node13 CANCELLED AT 2021-07-02T02:40:34 DUE TO TIME LIMIT *

**Comment by SilasK** [comment]
Check the log file, if there is an internal error `K18D55-S35-L003-001/logs/assembly/post_process/pilup_prefilter_contigs.log`

I think it's due to the time limit. 
> JOB 21527 ON node13 CANCELLED AT 2021-07-02T02:40:34 DUE TO TIME LIMIT 

Probably you need to increase the runtime
In the config.yaml set
```
runtime: #in h
    default: 10
```

If you don't have time restriction on your cluster system you can remove any time restriction by removing the key.value pair in the cluster wrapper/ keymappings.yaml

I hope this helps.

**Comment by JLammons14** [comment]
I appreciate the help, and Thanks for the quick response. I'll try increasing the runtime, but I think it running long is a symptom of some other problem because the nodes these jobs are being allocated to arent increasing their work load/utilization when running  pilup prefilter contig like they did when running all the other jobs with atlas. 

Also this is the log file: 

java -ea -Xmx85G -cp /mnt/beegfs/home/jlamm1/databases/conda_envs/34107f8b9bb538f6657b7ec6c88221e7/opt/bbmap-37.99/current/ jgi.CoveragePileup ref=K18D55-S35-L003-001/assembly/K18D55-S35-L003-001_prefilter_contigs.fasta in=K18D55-S35-L003-001/sequence_alignment/alignment_to_prefilter_contigs.sam threads=40 -Xmx85G covstats=K18D55-S35-L003-001/assembly/contig_stats/prefilter_coverage_stats.txt concise=t secondary=t
Executing jgi.CoveragePileup [ref=K18D55-S35-L003-001/assembly/K18D55-S35-L003-001_prefilter_contigs.fasta, in=K18D55-S35-L003-001/sequence_alignment/alignment_to_prefilter_contigs.sam, threads=40, -Xmx85G, covstats=K18D55-S35-L003-001/assembly/contig_stats/prefilter_coverage_stats.txt, concise=t, secondary=t]

Set threads to 40
Exception in thread "Thread-2" java.lang.AssertionError: 17 = A
array=CCTAAGCCACCTCATCTGGCCTCCCCTGGTATTTTCAAAGTAGAACGTAGACTAACATGGGAAGTTT	AAFFFJJFFFFJJJFJJJJJJJ77<AJJJJJJJJJJ-7AJJJJJFJFJF<JJJFJJJ-<JFJFJFF<AJJFJFJJJJJ<7A<AJJJAF-AFAAFJJJJJJJJJJ<JFJJJJJJJJ?GFIJGJJJ0JJJJJAGJJGGJJJ>JJJDFJ:5DIG, start=68, stop=219
	at shared.Tools.parseInt(Tools.java:2451)
	at stream.SamLine.<init>(SamLine.java:491)
	at stream.SamLineStreamer$ProcessThread.makeReads(SamLineStreamer.java:205)
	at stream.SamLineStreamer$ProcessThread.run(SamLineStreamer.java:135)
Exception in thread "Thread-1" java.lang.AssertionError: Missing field 0: 	0	*	*	0	0	GCCGAGATCCATTTCCAACCCAGTTGCGTTGGGAGAGGGTTGGGAGGCAGCAGAGCATGGGTGACAGTGGGAGCACACGACTTCCTTGGAGCCTGGGCCTTTGCGGGTCCCAGGTGGTCAGGCAGCTGGAGCAGAAGTGGAAATGGCTTA	AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
	at stream.SamLine.<init>(SamLine.java:484)
	at stream.SamLineStreamer$ProcessThread.makeReads(SamLineStreamer.java:205)
	at stream.SamLineStreamer$ProcessThread.run(SamLineStreamer.java:135

**Comment by SilasK** [comment]
Hmm. I don't completely understand the error message, but there is something wrong with the SAM file. 
In theory, the SAM file should only be created if the alignment has finished. 

Could you check if in the `{sample}/logs/assembly/post_process/align_reads_to_prefiltered_contigs.log` is something suspicious? 

Also 90s for the other samples is very short I think.


Let's try this: 
1. update bbmap 
```
conda activate /mnt/beegfs/home/jlamm1/databases/conda_envs/34107f8b9bb538f6657b7ec6c88221e7
conda install bbmap=38
conda deactivate
```

# update SAM file to v1.4
```
mv K19D27-S39-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam K19D27-S39-L004-001/sequence_alignment/alignment_to_prefilter_contigs.v1.3.sam

reformat.sh in=K19D27-S39-L004-001/sequence_alignment/alignment_to_prefilter_contigs.v1.3.sam out=K19D27-S39-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam sam=1.4

```

Rerun atlas for this file: 
`atlas run None  K19D27-S39-L004-001/assembly/contig_stats/prefilter_coverage_stats.txt`

**Comment by JLammons14** [comment]
I think updating bbmap and maybe updating the SAM file has worked to fix the problem, once I started atlas again on all samples, the pipeline completed rule_pileup_prefilter for all the samples I tested the fix on. 
What is weird is the output from reformatting.sh doesnt look like it worked, and I cant find the updated sam v1.4 files:

Heres the output from the fix you suggested:

mv K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.v1.3.sam

(atlasenv) $ reformat.sh in=K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.v1.3.sam out=K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam sam=1.4
java -ea -Xms300m -cp /mnt/beegfs/home/jlamm1/miniconda3/envs/atlasenv/opt/bbmap-38.90-3/current/ jgi.ReformatReads in=K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.v1.3.sam out=K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam sam=1.4
Executing jgi.ReformatReads [in=K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.v1.3.sam, out=K19D25-S38-L004-001/sequence_alignment/alignment_to_prefilter_contigs.sam, sam=1.4]

Input is being processed as unpaired
Waiting on header to be read from a sam file.
java.lang.AssertionError: Missing field 0: 	NH:i:2
	at stream.SamLine.<init>(SamLine.java:486)
	at stream.SamReadInputStream.toReadList(SamReadInputStream.java:119)
	at stream.SamReadInputStream.fillBuffer(SamReadInputStream.java:90)
	at stream.SamReadInputStream.nextList(SamReadInputStream.java:74)
	at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:681)
	at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:657)
Input:                  	14738800 reads          	2162422423 bases
Output:                 	14738800 reads (100.00%) 	2162422423 bases (100.00%)

Time:                         	26.285 seconds.
Reads Processed:      14738k 	560.72k reads/sec
Bases Processed:       2162m 	82.27m bases/sec
Exception in thread "main" java.lang.RuntimeException: ReformatReads terminated in an error state; the output may be corrupt.
	at jgi.ReformatReads.process(ReformatReads.java:1282)
	at jgi.ReformatReads.main(ReformatReads.java:53)



I attached the pilup_prefilter_contigs log file for the sample above as a text file as well:
[K19D25 Pilup_prefilter_contigs.txt](https://github.com/metagenome-atlas/atlas/files/6785911/K19D25.Pilup_prefilter_contigs.txt)



Also here is align_reads_to_prefiltered_contigs as a text file, the results didnt seem particularly odd although I'm not an expert.
[align_reads_to_prefiltered_contigs.txt](https://github.com/metagenome-atlas/atlas/files/6785824/align_reads_to_prefiltered_contigs.txt)

Again thanks for the help your a legend

**Comment by SilasK** [comment]
Ok, the logs seem all ok. But the reformat.sh command claims that there is something strange in the SAM file. 
Renaming the SAM files essentially removes them, and atlas maps the reads again. IF the solution works this means that the mapping worked the second time. 

I think you can remove all `*.v1.3.sam` files.- Run `atlas run assembly` and if you encounter the same problem. Try to remove the corresponding SAM files. 

Using `--keep-going` you can tell atlas to continue even if some files failed.

**Comment by JLammons14** [comment]
I got it all fixed, I had to rerun a corrupted sample, but after rerunning it, everything is good. Thanks so much for the help, your a legend! I have 2 separate minor questions but Ill just send them in a email if thats alright

**Comment by SilasK** [comment]
Yes you can send a mail or in the [chat](https://gitter.im/metagenome-atlas/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
