### ISSUE TITLE
genecatalog 

### ISSUE THREAD

**Issue by SF-Dragon** [metagenome-atlas/atlas#411]
I run the commands in order because atlas run all does not work to the end, but I get the following error at genecatalog.
Is there any way to circumven this error?

MissingOutputException in line 111 of /root/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/download.smk:
Job Missing files after 5 seconds:
/home/guest/databases/EggNOG_V5/eggnog.db
/home/guest/databases/EggNOG_V5/eggnog_proteins.dmnd
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 48 completed successfully, but some output files are missing. 48
  File "/root/anaconda3/envs/atlasenv/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 584, in handle_job_success
  File "/root/anaconda3/envs/atlasenv/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 259, in handle_job_success
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by SilasK** [comment]
I fixed this error in the latest version. Update to the latest atlas version `mamba  install metagenome-atlas=2.6a2` and rerun.
