### ISSUE TITLE
erroe in Job id:: 79

### ISSUE THREAD

**Issue by SohaibNQ** [metagenome-atlas/atlas#434]
Activating conda environment: /home/marco/miniconda3/atlas-testing/databases/conda_envs/a9edfae27a655bd09214c428877367b0
Waiting at most 5 seconds for missing files.
MissingOutputException in line 562 of /home/marco/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/rules/binning.smk:
Job Missing files after 5 seconds:
sample1/binning/DASTool/sample1_DASTool_hqBins.pdf
sample1/binning/DASTool/sample1_DASTool_scores.pdf
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 91 completed successfully, but some output files are missing. 91
Removing output files of failed job run_das_tool since they might be corrupted:
sample1/binning/DASTool/sample1_DASTool_summary.txt, sample1/binning/DASTool/sample1_metabat.eval, sample1/binning/DASTool/sample1_maxbin.eval, sample1/binning/DASTool/cluster_attribution.tsv
Waiting at most 5 seconds for missing files.
MissingOutputException in line 562 of /home/marco/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/rules/binning.smk:
Job Missing files after 5 seconds:
sample2/binning/DASTool/sample2_DASTool_hqBins.pdf
sample2/binning/DASTool/sample2_DASTool_scores.pdf
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 79 completed successfully, but some output files are missing. 79
Removing output files of failed job run_das_tool since they might be corrupted:
sample2/binning/DASTool/sample2_DASTool_summary.txt, sample2/binning/DASTool/sample2_metabat.eval, sample2/binning/DASTool/sample2_maxbin.eval, sample2/binning/DASTool/cluster_attribution.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /home/marco/miniconda3/atlas-testing/.snakemake/log/2021-08-27T141222.783585.snakemake.log
[2021-08-27 14:12 CRITICAL] Command 'snakemake --snakefile /home/marco/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /home/marco/miniconda3/atlas-testing  --rerun-incomplete --configfile '/home/marco/miniconda3/atlas-testing/config.yaml' --nolock   --use-conda --conda-prefix /home/marco/miniconda3/atlas-testing/databases/conda_envs   --scheduler greedy  all  --cores all ' returned non-zero exit status 1.
(atlas) marco@marco-HP-Z840-Workstation:~/miniconda3/atlas-testing$

**Comment by SilasK** [comment]
Fixed in the latest version 2.6a4
