### ISSUE TITLE
bioconda

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#44]
need to add `click` as prerequisite

**Comment by rec3141** [comment]
same, tried uninstalling and installing click using conda, still didn't work

Erics-Mac-Pro:~ cryomics$ atlas -h
Traceback (most recent call last):
  File "/usr/local/bin/atlas", line 7, in <module>
    from atlas.atlas import cli
  File "/usr/local/lib/python3.6/site-packages/atlas/atlas.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by rec3141** [comment]
I tried installing in linux and didn't have this problem. If ATLAS is not compatible with macos you should put that up front

**Comment by brwnj** [comment]
The only portion not compatible with macOS is genomic binning and is due to maxbin2 compatibility issues. We're considering other binning approaches to get around this issue. `click` is absolutely compatible with macOS, so it's likely an issue with your PATH.
