### ISSUE TITLE
Error in rule dereplication

### ISSUE THREAD

**Issue by SohaibNQ** [metagenome-atlas/atlas#445]
- [ ] I checked and didn't found a related issue,e.g. while typing the title
- [ ] ** I got an error in the following rule(s):** `   `

- [ ] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output:

```



```

** Atlas version**

**Additional context**

**Comment by SohaibNQ** [comment]
Hi there,
I am having the following issue while running my shotgun metagenome data in atlas. Fro this sample the problem occurred during the dereplication step. Another sample created a similar error message during the next "gene catalogue" step instead. Can you please tell me the solution or reason for this issue. There are no issues when running the test sample provided by Atlas. That run completed without any issues. 

Error in rule dereplication:
    jobid: 0
    output: genomes/Dereplication/dereplicated_genomes
    log: logs/genomes/dereplication.log (check log file(s) for error message)
    conda-env: /home/marco/miniconda3/atlas-testing/databases/conda_envs/23193c1d48f7bf25d67e11b02043a2b6
    shell:
         rm -rf genomes/Dereplication ; dRep dereplicate  --genomes genomes/all_bins/*.fasta  --genomeInfo genomes/quality.csv  --S_ani 0.5  --completeness_weight 1  --contamination_weight 5  --strain_heterogeneity_weight 1  --N50_weight 0.5  --size_weight 0  --MASH_sketch 5000  --processors 8    genomes/Dereplication  &> logs/genomes/dereplication.log 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.

**Comment by SohaibNQ** [comment]
I want to add that i am using the atlas 2.6a3 version.

**Comment by SilasK** [comment]
please go to the check list above. 

What does the log file say? logs/genomes/dereplication.log

**Comment by SohaibNQ** [comment]
Please look at the image below for the error. 
ValueError("No objects to concatenate")

![IMG-20210923-WA0009](https://user-images.githubusercontent.com/79035346/134457553-c52f18c6-0a60-4657-96b5-65d4785d84d9.jpg)

**Comment by SilasK** [comment]
For next time Copy paste the message in a code block between ```
would it make it easier?

Do you understand the error?  You only have one genome which is low quality. 

Any idea why this could be?
