### ISSUE TITLE
No Results/ output folder

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#451]
Hi Silas,

All the atlas steps ran succesfully (I think) on my own data (except for eggnog), and I'm trying to start analyzing the output, but I don't seem to have a `Results/` output folder. I have `genomes`, `Genecatalog`, `logs`, `ref`, `reports`, and sample specific output folders, but no `Results/` output folder (like were you should find `Example/Results/taxonomy.tsv` or `Example/Results/genome_completeness.tsv`). And I notice you need these kind of files if one wants to [analyze atlas output in R](https://github.com/metagenome-atlas/Tutorial/blob/master/R/Annotations.Rmd)

Any idea why this folder was not created?

**Comment by jmtsuji** [comment]
@slambrechts The Results folder is not output by the default ATLAS. I think you can generate it using the ATLAS analyze extension (although I have not tried this myself): https://github.com/metagenome-atlas/atlas_analyze

**Comment by slambrechts** [comment]
@jmtsuji ok thank you, will try that!

**Comment by SilasK** [comment]
@slambrechts  wait until Friday..

**Comment by slambrechts** [comment]
@SilasK ok thanks, looking forward to it!
