### ISSUE TITLE
job rule dram_download gets classified as finished even though download of kofam DB fails

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#457]
When rerunning `atlas run genomes` with atlas-dev 2.8 to test the DRAM implementation I noticed that atlas/snakemake continues when not all databases needed for DRAM downloaded correctly:

```
--2021-10-01 16:34:45--  ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz
           => â€˜/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/kofam_profiles.tar.gzâ€™
Resolving ftp.genome.jp (ftp.genome.jp)... 133.103.200.25
Connecting to ftp.genome.jp (ftp.genome.jp)|133.103.200.25|:21... failed: Connection refused.

downloading ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz
Traceback (most recent call last):
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 475, in prepare_databases
    output_dbs['kofam_hmm_loc'] = download_and_process_kofam_hmms(kofam_hmm_loc, temporary, verbose=verbose)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 83, in download_and_process_kofam_hmms
    download_file('ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz', kofam_profile_tar_gz, verbose=verbose)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/utils.py", line 28, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/utils.py", line 39, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/kofam_profiles.tar.gz', 'ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz']' returned non-zero exit status 4.
```

So it seems the rule dram_download gets classified as finished even though download of kofam fails

I'm downloading the kofam profiles manually now, but is there a way to rerun a rule that supposedly already finished?

**Comment by SilasK** [comment]
Did you use by mistake the `-k`/`--keep-going` flag?

If you look in the snakemake log there is no error for the rule download_db?

You can download the databases externally. or use dram. 

```
conda activate /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162
DRAM-setup.py prepare_databases 

```

Important is that you get a Dram config file. 




Then you can tell atlas to use this dram config file by giving it to the atlas config.yaml file `dram_config_file: path/to/config file`

**Comment by SilasK** [comment]
Can you try with atlas 2.8 if the error persists?

**Comment by slambrechts** [comment]
Hi Silas,

I haven't tried with atlas 2.8 yet, but I think it'ts because access to FTP servers is blocked on our HPC infrastructure (because of security reasons). The administrators advised me to check whether there are ways to use a different protocol, like SFTP or HTTPS. But I'm not sure dram/atlas will recognize it  then if I download it manually first using a different protocol.

**Comment by slambrechts** [comment]
@SilasK does atlas need the Uniref database for DRAM? Because on the [DRAM github](https://github.com/shafferm/DRAM) I read:

> NOTE: Setting up DRAM can take a long time (up to 5 hours) and uses a large about of memory (512 gb) by default. To use less memory you can use the --skip_uniref flag which will reduce memory usage to ~64 gb if you do not provide KEGG Genes and 128 gb if you do.

I would like to avoid needing 512 gb to install the database

**Comment by SilasK** [comment]
In atlas Indo not download uniref db

**Comment by slambrechts** [comment]
Ok. Downloading and installing the DRAM db manually worked. If anyone else experiences a problem where DRAM-setup.py tells you the ko list is missing, see [here](https://github.com/shafferm/DRAM/issues/120)

You wrote:

> Important is that you get a Dram config file.
> 
> Then you can tell atlas to use this dram config file by giving it to the atlas config.yaml file dram_config_file: path/to/config file


I could not find `dram_config_file:` in the `config.yaml` file, should I just add the line under the annotations part like so:

```
#######################
# Annotations
#######################

dram_config_file: /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/DRAM.config

annotations:
- gtdb_tree
- gtdb_taxonomy
- genes
- kegg_modules
- dram
```

?

**Comment by SilasK** [comment]
Yes, that would be the way to import it into atlas. Check with a dryrun if it actually skips the dram download. 
You need to import the dram config only once.
