### ISSUE TITLE
Error in rule deduplicate_reads, or How can i skip QC(my command is:atlas run assembly -w xx)

### ISSUE THREAD

**Issue by kuangzhuoran** [metagenome-atlas/atlas#465]
Because I have already finish QC, so I dont run all
I begin from assembly，Then run binning, genomes, genecatalog.   Is this consistent with the result of 'run all'? I see run none

But there is still "logs/benchmarks/QC/deduplicate/1A.txt" in log.
Then I met Below error
"""
java.lang.Exception: 
Mismatch between length of bases and qualities for read 1032 (id=E00499:125:H2FCJCCXY:3:1113:7841:4175 /1).
# qualities=119, # bases=150

AAAFAJJJJ7JJJFJJJJFJJJJF--FAJAJJJF<FFJ<JJJF-FJJF<F7F<JFFFJ7-F-AA-FJFJJJFJAJFJJAAJ77F7FAAJ7F<JAA---AAAJAF-FJJF7-AFJFFF--
AGCAAAGCAAAGCCATTGAAAAAACCACCGCAAGTATTTTCTTTTTCACAATATACTCCTCACTTTCCGCGCTTTTTCGGCAATGCTCTGGCAGGCGTACCCGCTTCTTTAAGCTCGTTTATCTTTTCACGGAGATACGCCGCCTGCTCG

This can be bypassed with the flag 'tossbrokenreads' or 'nullifybrokenquality'
"""

I try to add    tossbrokenreads: true      and      nullifybrokenquality: true    in  config.yaml, but it does not work.
"""
########################
# Quality control
########################
data_type: metagenome # metagenome or metatranscriptome
interleaved_fastqs: false
    
# remove (PCR)-duplicated reads using clumpify
deduplicate: true
duplicates_only_optical: false
duplicates_allow_substitutions: 2
**_nullifybrokenquality: true
tossbrokenreads: true_**
"""

atlas, version 2.7.0

I don't know what to do next. I didn't find relevant information on Google

Best
kzr

**Comment by SilasK** [comment]
Next time, could you use the issue template, please?  Also, use the code-text feature of GitHub.

Duplicte of #226 

I'm not sure where the error lies. If you have already done the qc you shouldn't get an error like 
> Mismatch between length of bases and qualities for read 1032

If you want atlas to do the qc and remove the bad reads add the following line to the config.yaml

importqc_params:  "iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t tossbrokenreads=t"





Update to v 2.8 which is more stable!
