### ISSUE TITLE
Error in rule run_checkm_lineage_wf

### ISSUE THREAD

**Issue by kayobianco** [metagenome-atlas/atlas#469]
Can you help me with this error?

Error in rule run_checkm_lineage_wf:
    jobid: 145
    output: jut/binning/DASTool/checkm/completeness.tsv, jut/binning/DASTool/checkm/storage/tree/concatenated.fasta
    log: jut/logs/binning/DASTool/checkm.log (check log file(s) for error message)
    conda-env: /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/9b28d67047d731d5b7406d25be3a47f7
    shell:
        
        rm -r jut/binning/DASTool/checkm
        checkm lineage_wf             --file jut/binning/DASTool/checkm/completeness.tsv             --tmpdir /tmp             --tab_table             --quiet             --extension fasta             --threads 2             jut/binning/DASTool/bins             jut/binning/DASTool/checkm &> jut/logs/binning/DASTool/checkm.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job run_checkm_lineage_wf since they might be corrupted:
jut/binning/DASTool/checkm/storage/tree/concatenated.fasta
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /media/archaea/UBUNTU-HD/Illumina/doutorado/atlas/.snakemake/log/2021-11-11T204722.806559.snakemake.log
[Atlas] CRITICAL: Command 'snakemake --snakefile /media/archaea/UBUNTU-HD/miniconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/Snakefile --directory /media/archaea/UBUNTU-HD/Illumina/doutorado/atlas --jobs 2 --rerun-incomplete --configfile '/media/archaea/UBUNTU-HD/Illumina/doutorado/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs   --scheduler greedy  all   ' returned non-zero exit status 1.

**Comment by SilasK** [comment]
can you check th elog file, please? jut/logs/binning/DASTool/checkm.log



** Atlas version**

**Comment by kayobianco** [comment]
Hi @SilasK,

First, thank you for help.

    Finished processing 0 of 2 (0.00%) bins.
    Finished processing 1 of 2 (50.00%) bins.
    Finished processing 2 of 2 (100.00%) bins.
    Finished processing 0 of 2 (0.00%) bins.
    Finished processing 1 of 2 (50.00%) bins.
    Finished processing 2 of 2 (100.00%) bins.
    Finished parsing hits for 1 of 2 (50.00%) bins.
    Finished parsing hits for 2 of 2 (100.00%) bins.
    Finished extracting 0 of 43 (0.00%) HMMs.
    Finished extracting 1 of 43 (2.33%) HMMs.
    Finished extracting 2 of 43 (4.65%) HMMs.
    Finished extracting 3 of 43 (6.98%) HMMs.
    Finished extracting 4 of 43 (9.30%) HMMs.
    Finished extracting 5 of 43 (11.63%) HMMs.
    Finished extracting 6 of 43 (13.95%) HMMs.
    Finished extracting 7 of 43 (16.28%) HMMs.
    Finished extracting 8 of 43 (18.60%) HMMs.
    Finished extracting 9 of 43 (20.93%) HMMs.
    Finished extracting 10 of 43 (23.26%) HMMs.
    Finished extracting 11 of 43 (25.58%) HMMs.
    Finished extracting 12 of 43 (27.91%) HMMs.
    Finished extracting 13 of 43 (30.23%) HMMs.
    Finished extracting 14 of 43 (32.56%) HMMs.
    Finished extracting 15 of 43 (34.88%) HMMs.
    Finished extracting 16 of 43 (37.21%) HMMs.
    Finished extracting 17 of 43 (39.53%) HMMs.
    Finished extracting 18 of 43 (41.86%) HMMs.
    Finished extracting 19 of 43 (44.19%) HMMs.
    Finished extracting 20 of 43 (46.51%) HMMs.
    Finished extracting 21 of 43 (48.84%) HMMs.
    Finished extracting 22 of 43 (51.16%) HMMs.
    Finished extracting 23 of 43 (53.49%) HMMs.
    Finished extracting 24 of 43 (55.81%) HMMs.
    Finished extracting 25 of 43 (58.14%) HMMs.
    Finished extracting 26 of 43 (60.47%) HMMs.
    Finished extracting 27 of 43 (62.79%) HMMs.
    Finished extracting 28 of 43 (65.12%) HMMs.
    Finished extracting 29 of 43 (67.44%) HMMs.
    Finished extracting 30 of 43 (69.77%) HMMs.
    Finished extracting 31 of 43 (72.09%) HMMs.
    Finished extracting 32 of 43 (74.42%) HMMs.
    Finished extracting 33 of 43 (76.74%) HMMs.
    Finished extracting 34 of 43 (79.07%) HMMs.
    Finished extracting 35 of 43 (81.40%) HMMs.
    Finished extracting 36 of 43 (83.72%) HMMs.
    Finished extracting 37 of 43 (86.05%) HMMs.
    Finished extracting 38 of 43 (88.37%) HMMs.
    Finished extracting 39 of 43 (90.70%) HMMs.
    Finished extracting 40 of 43 (93.02%) HMMs.
    Finished extracting 41 of 43 (95.35%) HMMs.
    Finished extracting 42 of 43 (97.67%) HMMs.
    Finished extracting 43 of 43 (100.00%) HMMs.
    Finished aligning 0 of 43 (0.00%) marker genes.
    Finished aligning 1 of 43 (2.33%) marker genes.
    Finished aligning 2 of 43 (4.65%) marker genes.
    Finished aligning 3 of 43 (6.98%) marker genes.
    Finished aligning 4 of 43 (9.30%) marker genes.
    Finished aligning 5 of 43 (11.63%) marker genes.
    Finished aligning 6 of 43 (13.95%) marker genes.
    Finished aligning 7 of 43 (16.28%) marker genes.
    Finished aligning 8 of 43 (18.60%) marker genes.
    Finished aligning 9 of 43 (20.93%) marker genes.
    Finished aligning 10 of 43 (23.26%) marker genes.
    Finished aligning 11 of 43 (25.58%) marker genes.
    Finished aligning 12 of 43 (27.91%) marker genes.
    Finished aligning 13 of 43 (30.23%) marker genes.
    Finished aligning 14 of 43 (32.56%) marker genes.
    Finished aligning 15 of 43 (34.88%) marker genes.
    Finished aligning 16 of 43 (37.21%) marker genes.
    Finished aligning 17 of 43 (39.53%) marker genes.
    Finished aligning 18 of 43 (41.86%) marker genes.
    Finished aligning 19 of 43 (44.19%) marker genes.
    Finished aligning 20 of 43 (46.51%) marker genes.
    Finished aligning 21 of 43 (48.84%) marker genes.
    Finished aligning 22 of 43 (51.16%) marker genes.
    Finished aligning 23 of 43 (53.49%) marker genes.
    Finished aligning 24 of 43 (55.81%) marker genes.
    Finished aligning 25 of 43 (58.14%) marker genes.
    Finished aligning 26 of 43 (60.47%) marker genes.
    Finished aligning 27 of 43 (62.79%) marker genes.
    Finished aligning 28 of 43 (65.12%) marker genes.
    Finished aligning 29 of 43 (67.44%) marker genes.
    Finished aligning 30 of 43 (69.77%) marker genes.
    Finished aligning 31 of 43 (72.09%) marker genes.
    Finished aligning 32 of 43 (74.42%) marker genes.
    Finished aligning 33 of 43 (76.74%) marker genes.
    Finished aligning 34 of 43 (79.07%) marker genes.
    Finished aligning 35 of 43 (81.40%) marker genes.
    Finished aligning 36 of 43 (83.72%) marker genes.
    Finished aligning 37 of 43 (86.05%) marker genes.
    Finished aligning 38 of 43 (88.37%) marker genes.
    Finished aligning 39 of 43 (90.70%) marker genes.
    Finished aligning 40 of 43 (93.02%) marker genes.
    Finished aligning 41 of 43 (95.35%) marker genes.
    Finished aligning 42 of 43 (97.67%) marker genes.
    Finished aligning 43 of 43 (100.00%) marker genes.
Killed
guppy: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
    Finished parsing hits for 1 of 2 (50.00%) bins.
    Finished parsing hits for 2 of 2 (100.00%) bins.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/9b28d67047d731d5b7406d25be3a47f7/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/9b28d67047d731d5b7406d25be3a47f7/lib/python3.6/site-packages/checkm/main.py", line 859, in parseOptions
    self.lineageSet(options)
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/9b28d67047d731d5b7406d25be3a47f7/lib/python3.6/site-packages/checkm/main.py", line 215, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/9b28d67047d731d5b7406d25be3a47f7/lib/python3.6/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/9b28d67047d731d5b7406d25be3a47f7/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'jut/binning/DASTool/checkm/storage/tree/concatenated.tre'

**Comment by SilasK** [comment]
I don't know exactly what's the error here if it's a problem of not enough disk space/memory or that a file is not accessible.

- Can you tell me which version of atlas you are using `atlas --version` 
- What is in the `tempdir` in your config.yaml ? 
- Do you have enough disk space there? 
- Do you have enough memory (RAM) e.g. 100gb?
- Do you follow the instructions on [how to run atlas in the docs](https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#execue-atlas)?

**Comment by SilasK** [comment]
Actually, I got the same error on running atlas on colab. I think it's the limitation of ram. as checkM needs quite a lot.

**Comment by kayobianco** [comment]
Hi Silas,
You're right, I added more memory and everything went well.

thanks
