### ISSUE TITLE
Atlas/snakemake doesn't pick the right tmpdir 

### ISSUE THREAD

**Issue by Laura-Alex** [metagenome-atlas/atlas#473]
Hello,

I've installed Atlas and just started debugging what went wrong on my first run. One aspect that should not affect the run, but it will make my life easier when I run this again if solved, is that snakemake doesn't seem to pick the right tmpdir from the config file.

```
# Local directory for temp files, useful for cluster execution without shared file system
tmpdir: ~/../../scratch/[username]
# directory where databases are downloaded with 'atlas download'
database_dir: /home/[username]/atlas/databases
```

I've originally tried` /scratch/[username]/` for tmpdir, and that didn't seem to work in the actual run (even though it works with other commands such as ls). I also tried dry-runs with` /scratch/[username]`  ,  `~/../../scratch/[username]` and `/home/../scratch/[username]` (which should all be the same), but what I get listed in the dry run is 'resources: tmpdir=/tmp'.

Strangely enough, the databse_dir seems to work correctly.

I'm working on a CentOS 7 computer cluster, with Slurm as batch manager (but the issue also happened in the dry-run, when I didn't submit it as a job)

I would appreciate your help!

**Comment by SilasK** [comment]
Don't be disturbed by twhat is wrotten as  resources tmpdir.  It's a new feature that I dont't use yet.  
In the rules that need temp I specify it via the params. 

e.g. checkM

You can set it to /scratch/user ...

Which is on the shared filesystem.

Even better would be to use the cluster wrapper. And to specify a drive that is only avalable on the executing node. 

In my case they are called /scratch

**Comment by Laura-Alex** [comment]
Thank you very much!

(also, if anyone as clueless as me has the same problem and reads this, quotes might help. I tried adding `tmpdir=/scratch` under 'resources' for the rules which required temporary files, and it didn't work, but `tmpdir='/scratch'` seems okay for now.)
