### ISSUE TITLE
No module named 'snakemake'

### ISSUE THREAD

**Issue by Laura-Alex** [metagenome-atlas/atlas#477]
Hello,

I'm in the process of debugging and would appreciate your help. I've tried running Atlas on a cluster and get the following error:

```
CLUSTER: 2021-11-19 15:52:56 Uncaught exception: Traceback (most recent call last):
  File "/home/[username]/.config/snakemake/[username]/scheduler.py", line 40, in <module>
    from snakemake.utils import read_job_properties
ModuleNotFoundError: No module named 'snakemake'

Error submitting jobscript (exit code 1):

[...]

CLUSTER: 2021-11-19 15:52:56 Uncaught exception: Traceback (most recent call last):
  File "/home/[username]/.config/snakemake/[username]/scheduler.py", line 40, in <module>
    from snakemake.utils import read_job_properties
ModuleNotFoundError: No module named 'snakemake'

Error submitting jobscript (exit code 1):
```

I saw that issue #384 appeared similar, but due to the different lines mentioned, I didn't think it would have the same fix (for example, line 11 is empty for me, I assume I must have a different version)
Line 40 in the respective document is: `from snakemake.utils import read_job_properties`

I don't know whether this has anything to do with me using the same name for the profile as for my username.

Thank you for your time!

**Comment by SilasK** [comment]
strange. I assume you have the newest cluster wrapper re-installed. and running atlas form a conda environment that has snakemake. 

do you have conda init in your bash rc?

**Comment by Laura-Alex** [comment]
> I assume you have the newest cluster wrapper re-installed
I'm sorry, I don't know what this means. Is it this command?
`cookiecutter --output-dir ~/.config/snakemake https://github.com/metagenome-atlas/clusterprofile.git`
If so, yes, it should be pretty recent. I added my username as a profile and kept the cluster name as ' cluster '.

>and running atlas form a conda environment that has snakemake.
Yes. The dry-run on a local node in the environment gives the expected results. It also worked for running on a cluster core, back when I didn't realize I needed to add '--profile [name of profile]' to the atlas run command (I mean, it ran out of memory pretty soon, but the snakemake part was solid)
 
> do you have conda init in your bash rc?
Yes.

**Comment by Laura-Alex** [comment]
Update:
Upon seeing this Q&A on stackoverflow (https://stackoverflow.com/questions/59493422), I checked what version of python my job was using and, surprisingly, when running as a parallel job, it was preferentially selecting my standard version (as opposed to the one in the conda env, which has snakemake)

I have added the line `PATH=$HOME/.conda/envs/atlasenv/bin:$PATH` right after activating my environment.

However, while it seems to work (in that the original issue doesn't happen anymore), there is a different error message appearing.

```
CLUSTER: 2021-11-25 16:26:50 Uncaught exception: Traceback (most recent call last):
  File "/home/[username]/.config/snakemake/[username]/scheduler.py", line 120, in <module>
    command = command_options[system]["command"]
KeyError: 'cluster'

Error submitting jobscript (exit code 1):
```

I would appreciate your help.

**Comment by SilasK** [comment]
Sorry for the delay at the end of the year. 
If I understand it correctly the variable `system` is `"cluster"` in your case. where it should e slurm or lsf depending on your cluster system.

You can change this, I think at the top of the 

/home/[username]/.config/snakemake/[username]/key_mapping.yaml

**Comment by SilasK** [comment]
I assume you don't have this issue anymore. Otherwise reopen or reply.
