### ISSUE TITLE
Blocked at "Downloading and installing remote packages."

### ISSUE THREAD

**Issue by steven-bioinfo** [metagenome-atlas/atlas#479]
Hello,

I have install (v2.8.0) and run atlas on my computer with your tutorial and i have no problem (I make this during October)

Now, i want to install and run atlas on an hpc (rockylinux8).
But on the cluster, all scripts are blocked at the creating conda environment.

for example : 
 ```bash
atlas download -d ./atlas_db
    Building DAG of jobs...
    Creating conda environment atlas/workflow/envs/eggNOG.yaml...
    Downloading and installing remote packages.
```

It's the same if i run : atlas run all with the gtdbtk.yaml environment 

I try with an installation from conda only and from github.

I use conda v4.10.1

Do you have any dependencies that could block this step?
Do you know how i can solve this issues ?

EDIT : 
I install again atlas in my computer in a new conda environment (from conda : v2.7.0, v2.8.0 and v2.8.1) and i have the same problem. My old atlas env work well but all my new atlas env is blocked. Maybe, a dependencie was updated and this update crash your pipeline.

Thanks in advance,

Steven

**Comment by crusher083** [comment]
I have exactly the same issue, no analysis is possible for the moment. Has been trying different things, but nothing helps. @SilasK could you please tell if it works for you? Any tips on this?

**Comment by kayobianco** [comment]
I have the same issue,  no analysis is possible for the moment.

**Comment by SilasK** [comment]
Sorry to hear that. I don't know if it's a problem of atlas or simply that conda/mamaba is slow on HPCs in general.

I managed to install metagenome-atlas and many of the dependenvies on a google colab. 

Could you check if you have mamba installed, usually this is installed with atlas. 

A possible cause could be the rolling out of python 3.10. 

Atlas requires py3.8 in the atlas env. But maybe for all dependencies python 3.19 is installed by default. 


What is the python version you have in your **base** environment?

```
conda activate base; python --version
```

**Comment by crusher083** [comment]
In my case, it's running on VM with 16CPUs and 128GB RAM. `atlasenv` has `python 3.8.10` installed. But still, something happens on the stage of setting up environments.

**Comment by steven-bioinfo** [comment]
My python version for the base environment is 3.6.8

It's not a problem of conda/mamba in hpc.
Now I have the same problem in my computer, with a new installation from conda or git. In the same computer, the "old" env can  always download and install the other environment.

So, I have exported my "old" computer environment and i create a new conda env in the hpc

```bash
git clone https://github.com/metagenome-atlas/atlas.git
cd atlas || exit
git checkout tags/v2.8.0
conda env create -n atlas --file "${HOME}"/my_atlas_computer_env.yml
conda activate atlas
pip install --editable .
conda deactivate
```
With this installation atlas can download and install the other environment when I run a pipeline.
If i run the same command line with your atlasenv.yml in github, the pipeline is blocked.

I thinks we have one dependence that has been updated and this update is incompatible with the others that are used in these steps to download and install packages.

Thanks for your help and for your great works.

**Comment by kayobianco** [comment]
Hi,
I created atlasenv using mamba. I was using it normally, but I needed to download the database again.

Now I can't perform any analysis. Has anyone been successful in solving this? 

Thanks for your help.

**Comment by crusher083** [comment]
@steven-bioinfo could you please add file "my_atlas_computer_env.yml"? I guess it could help me to start or analyze the problem better?

**Comment by SilasK** [comment]
@kayobianco did I understand you correctly that with mamba you were able to install a atlas version that can install packages .

** It's important to use mamba. Conda is too slow**, but mamba should be included in the atlas env.

You need to redownload wich database? E.g. GTDB? Maybe I got a new updat or som did you specify the sama database folder as before?

**Comment by kayobianco** [comment]
Hi Silas,

Sorry, but I don't think I expressed myself correctly.

When I use the command "atlas download" I get:

atlas download -d ./atlas_db
    Building DAG of jobs...
    Creating conda environment atlas/workflow/envs/eggNOG.yaml...
    Downloading and installing remote packages.

Download doesn`t take place. I've used another computer, another operating system and another internet connection, but nothing has changed. 

Thanks for your help @SilasK

**Comment by SilasK** [comment]
I made [google colab](https://colab.research.google.com/drive/1X5CZFYii_Sx2ELzbUEcHyKQ8-Alk4N-N?usp=sharing) notebook where I can install miniconda, atlas and then run atlas download.

**Comment by kayobianco** [comment]
Hi @SilasK,

I couldn't find out what the error was, but I reinstalled the miniconda, mamba and atlas.

Finally everything worked. Sorry for the annoyance.

Thank you so much for your help.

**Comment by SilasK** [comment]
I'm happy for you. Do others have still the same problem?
