### ISSUE TITLE
Lock Error

### ISSUE THREAD

**Issue by scastanedag** [metagenome-atlas/atlas#484]
atlas run all produce an error related with message:

CreateCondaEnvironmentException:
Could not create conda environment from /home/sergio.castaneda/data/conda/envs/atlasenv/lib/python3.8/site-packages/atlas/rules/../envs/report.yaml:
Exceeded max retries, giving up
LockError:
LOCKERROR: It looks like conda is already doing something.
The lock ['/home/sergio.castaneda/data/conda/pkgs/cache.pid106598.conda_lock'] was found. Wait for it to finish before continuing.
If you are sure that conda is not running, remove it and try again.
You can also use: $ conda clean --lock

However, conda clean --lock, doesnt work.

Thanks for your help

**Comment by SilasK** [comment]
apparently conda clean --lock doesn't exist yet/anymore. What happens if you delete simply the indicate lock file?
