### ISSUE TITLE
Error in rule

### ISSUE THREAD

**Issue by scastanedag** [metagenome-atlas/atlas#486]
I have an error in firsts steps of process. atlas run all.  Pipeline keep working but I am not sure if I will have issues caused by this error:

Activating conda environment: /datacnmat01/biologia/gimur/proyectos/microbiomas/7_19_Metagenomics_SAC/usftp21.novogene.com/atlas1/databases/conda_envs/23555bdec138d5f54a24020b39a8ace2
[Sat Dec 11 10:26:48 2021]
Error in rule initialize_checkm:
    jobid: 376
    output: logs/checkm_init.txt
    log: logs/initialize_checkm.log (check log file(s) for error message)
    conda-env: /datacnmat01/biologia/gimur/proyectos/microbiomas/7_19_Metagenomics_SAC/usftp21.novogene.com/atlas1/databases/conda_envs/23555bdec138d5f54a24020b39a8ace2
    shell:
        checkm data setRoot /datacnmat01/biologia/gimur/proyectos/microbiomas/7_19_Metagenomics_SAC/usftp21.novogene.com/atlas1/databases/checkm &> logs/initialize_checkm.log
        **(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)**

**Comment by SilasK** [comment]
Sorry for the delay. 

Check the ` logs/initialize_checkm.log``
Probably you don't have write access to the folder /datacnmat01/biologia/gimur/proyectos/microbiomas/7_19_Metagenomics_SAC/usftp21.novogene.com/atlas1/databases

Maybe you need to specify a database folder where you have write access to during atlas init
