### ISSUE TITLE
DRAM --min_contig_size

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#487]
Hi,

By default DRAM first filters the MAGs to remove short contigs (by default contigs < 2500 bp). Is there a way to lower that `--min_contig_size` parameter in the atlas `config.yaml` file?

**Comment by SilasK** [comment]
Not directly, maybe should be added. dram has the parameter `--min_contig_size` ?

**Comment by slambrechts** [comment]
yes indeed, `DRAM.py annotate` has the parameter `--min_contig_size`
