### ISSUE TITLE
Forcing ATLAS to not run SPAdes jobs in parallel

### ISSUE THREAD

**Issue by MaxRubinBlum** [metagenome-atlas/atlas#494]
Hi @SilasK, when using merged reads, SPAdes read correction results in memory issues. Reducing the number of threads solves the problem, yet ATLAS executes the SPADes jobs in parallel, running into a memory problem again. Is there an elegant way to solve this, besides letting the jobs fail until only one SPADes assembly remains running, and then restart? I am working on a high-end Linux workstation, not a server. Thanks!

**Comment by SilasK** [comment]
By default I skip read error correction and do it with taedpole before the reads are merged. But you changed this, did you?


If you increase the assembly memory to the max memory of your machine and then tell atlas how much memory you have on the machine it executes only one job after the other. 

Check the docs how to execute atlas on a single machine.

Tell me how it goes l.

**Comment by MaxRubinBlum** [comment]
Many thanks! I tried to do it in SPAdes because I also ran into memory issues with tadpole, but I missed setting the java_mem parameter. Seems to work fine now.
