### ISSUE TITLE
Error in config file for metatranscriptome

### ISSUE THREAD

**Issue by steven-bioinfo** [metagenome-atlas/atlas#501]
Hello,

With the option metatranscriptome, we have the rRNA database with [ ] in the config.yaml file as a python list. So we get an error in the pipeline when this file is used.
It's here : https://github.com/metagenome-atlas/atlas/blob/97ad47f6810142f0137a0b8f01ce613f8761e2d2/atlas/make_config.py#L222

possible change
```
conf["contaminant_references"]["rRNA"] = (
    os.path.join(database_dir, "silva_rfam_all_rRNAs.fa"),
)
```
to
```
conf["contaminant_references"]["rRNA"] = os.path.join(
    database_dir, "silva_rfam_all_rRNAs.fa"
)
```

Have a good day,

Steven

**Comment by SilasK** [comment]
What do you try to do. I'm not shure if the assembly would work out of the box.
