### ISSUE TITLE
Error in rule initialize_qc: reformat.sh running with -Xmx0G

### ISSUE THREAD

**Issue by bcpd** [metagenome-atlas/atlas#504]
- [ ] ** I got an error in the following rule(s):** `   `
initialize_qc

- [ ] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output:
(from sample2/logs/QC/init.log)
```
java -ea -Xmx0G -cp /root/databases/atlas/conda_envs/0e32d1caf90387ed3d41579252fae827/opt/bbmap-37.99/current/ jgi.ReformatReads in1=/home/atlas/example_data/reads/test/sample2.fastq.gz interleaved=t out1=sample2/sequence_quality_control/sample2_raw_R1.fastq.gz out2=sample2/sequence_quality_control/sample2_raw_R2.fastq.gz iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t qin=33 tossbrokenreads overwrite=true verifypaired=t threads=4 -Xmx0G
Invalid maximum heap size: -Xmx0G
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


```

** Atlas version**
2.9
**Additional context**
ATLAS 2.9 is running inside a docker container. The test dataset was downloaded from ``` https://github.com/metagenome-atlas/example_data.git ```

**Comment by SilasK** [comment]
Could you give me the exact command you run atlas run... ? Did you use the max-mem attribute?

**Comment by bcpd** [comment]
The sequence of commands was the following:

```git clone https://github.com/metagenome-atlas/example_data.git
atlas init --db-dir $databases --working-dir testrun --interleaved-fastq example_data/reads/test
atlas run all -w testrun -j 10
```

I got the same error as in #358, but the init.log diagnosed a different problem.

I'm not sure what the max-mem attribute is; from what I can gather, the execution parameter in the config file that affects memory usage of bbtools is ``` mem ``` , which I changed without success.

Thanks very much.

**Comment by SilasK** [comment]
The problem comes from that the maximum memory is set to 0GB.

Atlas should automatically detect the memory available on your system. Maybe you have less than 1 GB of ram or there is some problem to infer the resources inside the docker container. 

Do you see something in the log that indicates how much memory is specified? 


The solution would be to use the --max-mem flag described here. https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#single-machine-execution

**Comment by bcpd** [comment]
Indeed, ATLAS was having trouble figuring out the resources inside the container. Using the --max-mem appears to have worked. Thanks very much for your help.

**Comment by animesh** [comment]
I have the same issue and using --max-mem 80 seems to have worked @SilasK , wondering if there is a way to put this in config? My current config [config.yaml.txt](https://github.com/metagenome-atlas/atlas/files/8441602/config.yaml.txt)  has mem: 60 and large_mem: 250.
