### ISSUE TITLE
Error in gtdb download

### ISSUE THREAD

**Issue by bryshalm** [metagenome-atlas/atlas#509]
- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x] ** I got an error in the following rule(s):** `  download_gtdb`

- [x] I checked the log files indicated indicated in the error message

I am getting this error message if an incomplete gtdbtk download already exists, it is neither removed nor overwritten, and an error occurs

The error message should look something like the rule below 
```

Error in rule download_gtdb:
    jobid: 124
    output: /home/brymoore/testatlas/databases/GTDB_V06/download_success
    log: logs/download/gtdbtk.log (check log files(s) for error message)
    conda-env: /home/brymoore/testatlas/databases/conda_envs/bda6ca6bc3e9415778d37cd3b9615549
    shell:
        GTDBTK_DATA_PATH=/home/brymoore/testatlas/databases/GTDB_V06  ;  download-db.sh &> logs/download/gtdbtk.log;
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shuttting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

@ctb 

** Atlas version 2.9**

**Comment by bryshalm** [comment]
looked at logs/download/gtdbtk.log `logs/download/gtdbtk.log` and noticed the download was being saved to `2022-04-14 01:12:29 (3.59 MB/s) - '/home/brymoore/testatlas/databases/GTDB_V06/gtdbtk_r202_data.tar.gz.1' saved [50840267340/50840267340]`

Suggests that the  download is deciding not to overwrite an existing file (and downloading to a `.1` file instead.
`ls /home/brymoore/testatlas/databases/GTDB_V06/gtdbtk_r202_data.tar.gz*`

produces
`/home/brymoore/testatlas/databases/GTDB_V06/gtdbtk_r202_data.tar.gz`
`/home/brymoore/testatlas/databases/GTDB_V06/gtdbtk_r202_data.tar.gz.1`

**To attempt to resolve this issue:**
- we removed the file
  `rm /home/brymoore/testatlas/databases/GTDB_V06/gtdbtk_r202_data.tar.gz*`

- re-ran atlas, (which is currently still running)
- will update on the results of this  resolution

@ctb

**Comment by ctb** [comment]
without having looked into the snakemake situation, my guess is that:

* one resolution could be to specify a flag to wget or curl to overwrite the file
* another resolution could be to split the snakemake rule into download and unpack steps

**Comment by bryshalm** [comment]
**UPDATE**
- the above seems method seems to have worked!

**Comment by SilasK** [comment]
It's a problem of the gtdb-tk script. I forward the issue. 

Note: there was a recent release of GTDB, wich is not yet incorporated.
