### ISSUE TITLE
Error in rule combine_gene_coverages: not enough memory for large datasets

### ISSUE THREAD

**Issue by leasi** [metagenome-atlas/atlas#515]
- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x] I got an error in the following rule(s): `combine_gene_coverages`
- [x] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Error message: `MemoryError in line 327 of [PATH]/atlas2.8.2/lib/python3.8/site-packages/atlas/workflow/rules/genecatalog.smk`
(note : 500Gb memory required in the `config.yaml` file)

**Atlas version** 2.8.2

**Additional context**

Hi Silas!

I am trying to merge gene abundance tables on a dataset > 1000 samples ; you can imagine how it is impossible to fit all of these tables in memory (already checked the "quick fix" mentioned in #483 but still, our cluster memory is not enough). Any possibility for this merging to be done without such huge memory requirements?

Thank you!
Léa.

**Comment by SilasK** [comment]
Hey @leasi, 
I will have a look at it.

**Comment by SilasK** [comment]
This is fixed with v 2.11
