### ISSUE TITLE
Invalid maximum heap size: -Xmx0G

### ISSUE THREAD

**Issue by HamzaMbareche** [metagenome-atlas/atlas#516]
Hello,

I am getting an error while running atlas run all.

This is copy paste of the logfile. 

java -ea -Xmx0G -cp /media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/f0698431ea1cd74b5c42a7674831a6ae/opt/bbmap-37.99/current/ jgi.ReformatReads in1=/media/hmbareche/data2/MAGs_Discovery/PR1_fastq/5283C1_R1.fastq in2=/media/hmbareche/data2/MAGs_Discovery/PR1_fastq/5283C1_R2.fastq interleaved=f out1=S5283C1/sequence_quality_control/S5283C1_raw_R1.fastq.gz out2=S5283C1/sequence_quality_control/S5283C1_raw_R2.fastq.gz iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t overwrite=true verifypaired=t threads=4 -Xmx0G
Invalid maximum heap size: -Xmx0G
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

It seems like its related to Java. I have checked that the Java is installed and updated. From my research, this looks like the code is telling the QC step to use 0 GB memory. Is that what -Xmx0G mean?

By the way, I am running ATLAS from an UBUNTU 20.04 machine.

Thanks in advance for any guidance on this.

**Comment by SilasK** [comment]
Hello @HamzaMbareche , It's an error in my code, not your fault. 

Updating to atlas v2.9.1 should solve the problem.
