### ISSUE TITLE
Question: restarting after pipeline interrupted

### ISSUE THREAD

**Issue by skeffington** [metagenome-atlas/atlas#517]
Hi - thanks for the amazing pipeline!

I was trying to run Atlas via the snakemake automatic scheduler on our cluster. Unfortunately the screen session I was running it in didn't preserve the process when the terminal was closed for some reason. There are still a couple of jobs pending on the cluster: 2x run_deco and 1x error_co.

What do you think will happen if I simply do `atlas run` again? Will it pick up where it left off? Or do I need to start again?

Many thanks,
Alastair

**Comment by SilasK** [comment]
The magic of snakemake is that you can restart where you left off, usually without any problem.

However, you need to kill all atlas-related jobs before rerunning atlas. 
I recommend killing the running jobs and to restart them.

Alternatively to screen you can also run a long-lasting job where you run atlas.

**Comment by skeffington** [comment]
Great - thanks for the advice! So you mean I could run a long lasting job that will itself submit more jobs ...? And I guess that lon-lasting job just needs one thread and little memory?
