### ISSUE TITLE
Insufficient memory for the Java Runtime Environment to continue

### ISSUE THREAD

**Issue by HamzaMbareche** [metagenome-atlas/atlas#519]
Hi, I got the following error while running  _atlas run genome_ 

The error is occurring at the assembly step (after QC and host decontamination), and It is a memory issue. Is there a way to work around it? Would reducing the number of samples per run help? Can you specifically specify to use the available memory?
I'm using atlas on a single machine. 

#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 54760833024 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /media/hmbareche/data2/MAGs_Discovery/.snakemake/shadow/tmp1ee2kxqn/hs_err_pid944173.log
[Thu May 19 12:54:12 2022]
Error in rule merge_pairs:
    jobid: 0
    output: S2179C1/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, S2179C1/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, S2179C1/assembly/reads/QC.errorcorr.merged_me.fastq.gz
    log: S2179C1/logs/assembly/pre_process/merge_pairs_QC.errorcorr.log (check log file(s) for error message)
    conda-env: /media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/f0698431ea1cd74b5c42a7674831a6ae
    shell:
        
        bbmerge.sh -Xmx51G threads=8             in1=S2179C1/assembly/reads/QC.errorcorr_R1.fastq.gz in2=S2179C1/assembly/reads/QC.errorcorr_R2.fastq.gz             outmerged=S2179C1/assembly/reads/QC.errorcorr.merged_me.fastq.gz             outu=S2179C1/assembly/reads/QC.errorcorr.merged_R1.fastq.gz outu2=S2179C1/assembly/reads/QC.errorcorr.merged_R2.fastq.gz             ecct iterations=1 k=62             pigz=t unpigz=t             extend2=50 2> S2179C1/logs/assembly/pre_process/merge_pairs_QC.errorcorr.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

** Atlas version**
2.9.1

Any help or guidance would be greatly appreciated. 

Hamza

**Comment by SilasK** [comment]
Increase the mem in the config file

**Comment by HamzaMbareche** [comment]
Thanks Silas. I decreased the memory on the config file to meet the available memory on my machine, which below the 250GB suggested on the default config file. It's slow but at least no error messages so far.
