### ISSUE TITLE
how to activate SemiBin

### ISSUE THREAD

**Issue by Mechah** [metagenome-atlas/atlas#521]
Hi Silas,
very naive question - I was wondering how to actually use SemiBin in the ATLAS workflow.
Is it sufficient to add - SemiBin as another binner into your config.yaml file?
Thanks!

**Comment by SilasK** [comment]
You can, I would set it as your final Binner tough. 

I wrote in the comment in the [template config ](https://metagenome-atlas.readthedocs.io/en/latest/usage/configuration.html#example-config-file)

**Comment by Mechah** [comment]
That simple... thanks

**Comment by raw937** [comment]
@Mechah hey. How are you?

**Comment by Mechah** [comment]
Hey @raw937,
good currently at UCSD as a visiting scholar. How about you?
