### ISSUE TITLE
Merging annotations across samples

### ISSUE THREAD

**Issue by brwnj** [metagenome-atlas/atlas#53]
As a final rule, merge annotations across samples.

This was implemented at one point, but it's such a trivial operation that I perform the merge after running ATLAS. You can see remnants of this feature here: https://github.com/pnnl/atlas/blob/90f295f31375b498c7db2204d15f987721a1770a/scripts/blast2assignment.py#L1097

**Comment by SilasK** [comment]
@brwnj what was the reason you removed the eggnog function from atlas? 
Not enough mapping results?

**Comment by brwnj** [comment]
The database we had at the time was an incomplete representation of eggnog and I wasn't happy with how we were using that to assign function. It's likely worth considering dumping prokka in favor of prodigal + https://github.com/jhcepas/eggnog-mapper.

**Comment by SilasK** [comment]
I added my eggnog scripts see #99

**Comment by SilasK** [comment]
I have errors when I want to convert the prodigal gff to gtf. Apparently prodigal doesn't name the genes the same way as does prokka. 

@brwnj have you already encountered this?

**Comment by brwnj** [comment]
We can always update the downstream steps to accommodate changes to the attributes field. Is the GFF compatible (with slight changes in params as -t and -g may be different) with featureCounts?
