### ISSUE TITLE
Error in rule root_tree from gtdbtk 

### ISSUE THREAD

**Issue by yotsa** [metagenome-atlas/atlas#530]
Hi,

I was running atlas on my workstation with 256 GB ram with 16 threads. Everything worked fine from QC on down until the GTDB-TK root_tree step. 

Here is the relevant log output:

```
Error in rule root_tree:
    jobid: 6847
    output: genomes/tree/gtdbtk.ar122.nwk
    log: logs/genomes/tree/root_tree_gtdbtk.ar122.log (check log file(s) for error message)
    conda-env: /home/cbs_cri/database/conda_envs/b783d806deffb58075801281939c6ecf

RuleException:
CalledProcessError in line 125 of /home/cbs_cri/anaconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/rules/gtdbtk.smk:
Command 'source /home/cbs_cri/anaconda3/envs/atlasenv/bin/activate '/home/cbs_cri/database/conda_envs/b783d806deffb58075801281939c6ecf'; set -euo pipefail;  python /home/cbs_cri/atlas-tiger/.snakemake/scripts/tmp_e0b11si.root_tree.py' returned non-zero exit status 1.
  File "/home/cbs_cri/anaconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/rules/gtdbtk.smk", line 125, in __rule_root_tree
  File "/home/cbs_cri/anaconda3/envs/atlasenv/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

```

** Atlas version 2.9.1**

I searched in the previous issues on GitHub and found something similar but not quite the same. What's weird is that the log file for this command is empty, so I don't know what is the real issue. Can you please help? 

Best 
Yot

**Comment by SilasK** [comment]
I'm almost Shure that you don't have any or only 1 or two archae genomes. Which makes the tree unrootable. 

The error handling should be better, I check that. 

What you can do:

Run atlas with the --dryrun option.

Then, for this rule, simply copy the input: tree as output tree file. 

And continue running atlas.

**Comment by skeffington** [comment]
I have the same issue - and I only have 2 archaeal genomes in the data set.

in the dir genomes/tree I have:

```
gtdbtk.ar122.unrooted.nwk  gtdbtk.bac120.nwk  gtdbtk.bac120.unrooted.nwk
```

Does this mean I should do:

```
cp gtdbtk.ar122.unrooted.nwk gtdbtk.ar122.nwk
```

And what is the purpose of doing the --dryrun option first?

Thanks!

**Comment by skeffington** [comment]
It worked for me anyway - atlas finally ran to completion! :)

**Comment by SilasK** [comment]
Dryrun is just for testing.
I should improve this script.
