### ISSUE TITLE
Speed up DRAM annotations

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#533]
Hi @SilasK ,

I've started using ATLAS 2.9.1 -- nice work with the added features!

I noticed that annotations via DRAM can be a bit slow. On my lab server (running Ubuntu 20.04 LTS), each MAG takes about 10-30 minutes to run through `rule DRAM_annotate`. However, `rule DRAM_annotate` only uses 2-3 threads for most of the run (I think being throttled by hmmsearch). For a metagenome set with ~200 MAGs, DRAM annotations are actually proving to be one of the major analysis bottlenecks.

I'm wondering if we can change `rule DRAM_annotate` to use `simplejob_threads` instead of `threads`. When tested on my lab's server, if `simplejob_threads` is set to 4, for example, this change provides a substantial speedup by allowing multiple instances of `rule DRAM_annotate` to run simultaneously.

I will make a PR to master with this proposed change -- feel free to accept or decline the PR depending on your thoughts.

Thanks!

Jackson

**Comment by SilasK** [comment]
Thank you for your investigation. and a good idea. 

There is a snakemnake argument that should you let change the resources arguments maybe also the threads.

**Comment by jmtsuji** [comment]
Thanks! Yes, I think the max threads can be set easily using the `--jobs` flag.
