### ISSUE TITLE
Error with spades when installing remote packages

### ISSUE THREAD

**Issue by DaniAlvy** [metagenome-atlas/atlas#537]
- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x] ** I got an error in the following rule(s):** `   `

Dear Silas,
I'm a new ATLAS user and I'm practicing with the test samples. I have a problem with Spades when I run ATLAS for assembly, at the very beginning, when installing the packages. I get the following error which I can't solve : “nothing provides requested spades >=3.15.3“. Dry running works normally.
Thank you :)

Creating conda environment /opt/anaconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/rules/../envs/spades.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /opt/anaconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/rules/../envs/spades.yaml:
Command:
mamba env create --quiet --file "/Users/annacarratala/Desktop/run_test/databases/conda_envs/226f63742e9b34aad13e154aa6b92a3b.yaml" --prefix "/Users/annacarratala/Desktop/run_test/databases/conda_envs/226f63742e9b34aad13e154aa6b92a3b"
Output:
Encountered problems while solving:
  - nothing provides requested spades >=3.15.3

- [ ] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

** Atlas version 2.9.1**

**Comment by SilasK** [comment]
Could you try to run the command 

mamba env create  --file "/Users/annacarratala/Desktop/run_test/databases/conda_envs/226f63742e9b34aad13e154aa6b92a3b.yaml" --prefix "/Users/annacarratala/Desktop/run_test/databases/conda_envs/226f63742e9b34aad13e154aa6b92a3b"

This should give more info.

I could imagine that the python 3.8 in the atlasenv somehow restricts the spades. For me it works with python 3.10

You could also install metagenome-atlas=3.10 with python=3.10

**Comment by DaniAlvy** [comment]
I can't install metagenome-atlas (neither 2.9 nor 2.10) with another version than python 3.8 .

For example, when I try the following command :

"conda create -y -n atlasenv metagenome-atlas=2.10 python=3.10"

I get the following message :

"Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
metagenome-atlas=2.10 -> python[version='>=3.8,<3.11']
python=3.10
metagenome-atlas=2.10 -> biopython=1.74 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.6|>=3.7|3.4.*|>=3.7.1,<3.8.0a0|>=3.5,<3.6.0a0'] "

**Comment by DaniAlvy** [comment]
The command 

>mamba env create --file "/Users/annacarratala/Desktop/run_test/databases/conda_envs/226f63742e9b34aad13e154aa6b92a3b.yaml>" --prefix "/Users/annacarratala/Desktop/run_test/databases/conda_envs/226f63742e9b34aad13e154aa6b92a3b"

Gives :

>conda-forge/osx-64                                          Using cache
>conda-forge/noarch                                          Using cache
>bioconda/osx-64                                             Using cache
>bioconda/noarch                                             Using cache
>pkgs/main/osx-64                                            Using cache
>pkgs/main/noarch                                            Using cache
>pkgs/r/osx-64                                               Using cache
>pkgs/r/noarch                                               Using cache
>
>
>Looking for: ["spades[version='>=3.15.3']"]
>
>
>Encountered problems while solving:
>  - nothing provides requested spades >=3.15.3

**Comment by SilasK** [comment]
You have a linux computer, do you? 

Very strange errors. 

Try to install atlas 2.10  or 2.11 with python 3.9 or 3.10 in a new environment. 
But use mamba not conda. 

in v 2.11 I remove the dependency on biopython

**Comment by DaniAlvy** [comment]
I have a Mac computer, I am so sorry I didn't specify, I understood that it worked too.

**Comment by SilasK** [comment]
If you want to analyze real metagen datsets. The computational resources of your mac wont be enough. (250GB ram )

There fore you usually need a linux server. 

If you only want to test atlas out. I have a solution to let it run on google colab. 


There is the Tutorial with already processed data. I usually want to know what the output is.
