### ISSUE TITLE
Upgrading to CheckM2

### ISSUE THREAD

**Issue by bcpd** [metagenome-atlas/atlas#539]
Are there plans to replace CheckM1 with CheckM2 in ATLAS? https://www.biorxiv.org/content/10.1101/2022.07.11.499243v1.full

**Comment by SilasK** [comment]
It is planned. Is there a API description somewhere?

**Comment by SilasK** [comment]
#607 adds checkm2

**Comment by SilasK** [comment]
this will be atlas v 3.14
