### ISSUE TITLE
Error in rule build_qc_report:

### ISSUE THREAD

**Issue by omrctnr** [metagenome-atlas/atlas#541]
Hello,

Although the ATLAS ran with test data, I encountered this error. 

I use this command to start the pipeline
`atlas run qc -j 20 --conda-frontend mamba --profile cluster`

Some _get read stats__ jobs were finishing correctly but I didn't understand why not all.

**ATLAS version: 2.9.1**

If you need further information please contact me.

(I use the `screen` command instead of my default terminal running with ATLAS to avoid timeout) 

### **Error**
`[Fri Jul 29 07:41:50 2022]
Error in rule get_read_stats:
    jobid: 2749
    output: S3735D7-S12/sequence_quality_control/read_stats/filtered.zip, S3735D7-S12/sequence_quality_control/read_stats/filtered_read_counts.tsv
    log: S3735D7-S12/logs/QC/read_stats/filtered.log (check log file(s) for error message)
    cluster_jobid: 8558386
Error executing rule get_read_stats on cluster (jobid: 2749, external: 8558386, jobscript: /data/users/ocetiner/atlas/.snakemake/tmp.50_w8ox3/snakejob.get_read_stats.2749.sh). For error details see the cluster log and the log files of the involved rule(s).`

### **Cluster_log**

> Building DAG of jobs...
> Using shell: /usr/bin/bash
> Provided cores: 99
> Rules claiming more threads will be scaled down.
> Singularity containers: ignored
> Select jobs to execute...
> 
> [Fri Jul 29 07:41:27 2022]
> rule get_read_stats:
>     input: S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_R1.fastq.gz, S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_R2.fastq.gz
>     output: S3735D7-S12/sequence_quality_control/read_stats/filtered.zip, S3735D7-S12/sequence_quality_control/read_stats/filtered_read_counts.tsv
>     log: S3735D7-S12/logs/QC/read_stats/filtered.log
>     jobid: 0
>     wildcards: sample=S3735D7-S12, step=filtered
>     priority: 30
>     threads: 99
>     resources: mem_mb=500000, disk_mb=1000, tmpdir=/tmp, mem=500, java_mem=425, time=670, time_min=40200
> 
> java -ea -Xmx425G -Xms425G -cp /data/users/ocetiner/miniconda/envs/atlasenv2/opt/bbmap-38.96-1/current/ jgi.ReformatReads in1=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_R1.fastq.gz in2=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_R2.fastq.gz bhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/base_hist.txt qhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/quality_by_pos.txt lhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/readlength.txt gchist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/gc_hist.txt gcbins=auto bqhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/boxplot_quality.txt threads=99 overwrite=true -Xmx425G
> Executing jgi.ReformatReads [in1=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_R1.fastq.gz, in2=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_R2.fastq.gz, bhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/base_hist.txt, qhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/quality_by_pos.txt, lhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/readlength.txt, gchist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/gc_hist.txt, gcbins=auto, bqhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/boxplot_quality.txt, threads=99, overwrite=true, -Xmx425G]
> 
> Set base content histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/base_hist.txt
> Set quality histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/quality_by_pos.txt
> Set length histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/readlength.txt
> Set GC histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/gc_hist.txt
> Set bquality histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/pe/boxplot_quality.txt
> Set threads to 99
> No output stream specified.  To write to stdout, please specify 'out=stdout.fq' or similar.
> Set INTERLEAVED to false
> Input is being processed as paired
> Input:                          4111542 reads           595722785 bases
> Output:                         4111542 reads (100.00%)         595722785 bases (100.00%)
> 
> Time:                           11.839 seconds.
> Reads Processed:       4111k    347.29k reads/sec
> Bases Processed:        595m    50.32m bases/sec
> java -ea -Xmx425G -Xms425G -cp /data/users/ocetiner/miniconda/envs/atlasenv2/opt/bbmap-38.96-1/current/ jgi.ReformatReads in=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_se.fastq.gz bhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/base_hist.txt qhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/quality_by_pos.txt lhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/readlength.txt gchist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/gc_hist.txt gcbins=auto bqhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/boxplot_quality.txt threads=99 overwrite=true -Xmx425G
> Executing jgi.ReformatReads [in=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_se.fastq.gz, bhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/base_hist.txt, qhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/quality_by_pos.txt, lhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/readlength.txt, gchist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/gc_hist.txt, gcbins=auto, bqhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/boxplot_quality.txt, threads=99, overwrite=true, -Xmx425G]
> 
> Set base content histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/se/base_hist.txt
> Set quality histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/se/quality_by_pos.txt
> Set length histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/se/readlength.txt
> Set GC histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/se/gc_hist.txt
> Set bquality histogram output to S3735D7-S12/sequence_quality_control/read_stats/filtered/se/boxplot_quality.txt
> Set threads to 99
> No output stream specified.  To write to stdout, please specify 'out=stdout.fq' or similar.
> Exception in thread "main" java.lang.RuntimeException: Can't find file S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_se.fastq.gz
>         at fileIO.ReadWrite.getRawInputStream(ReadWrite.java:933)
>         at fileIO.ReadWrite.getGZipInputStream(ReadWrite.java:1039)
>         at fileIO.ReadWrite.getInputStream(ReadWrite.java:848)
>         at fileIO.ByteFile1.open(ByteFile1.java:330)
>         at fileIO.ByteFile1.<init>(ByteFile1.java:100)
>         at fileIO.ByteFile2$BF1Thread.<init>(ByteFile2.java:237)
>         at fileIO.ByteFile2.open(ByteFile2.java:215)
>         at fileIO.ByteFile2.<init>(ByteFile2.java:86)
>         at fileIO.ByteFile.makeByteFile(ByteFile.java:35)
>         at fileIO.ByteFile.makeByteFile(ByteFile.java:27)
>         at stream.FastqReadInputStream.<init>(FastqReadInputStream.java:59)
>         at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:116)
>         at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:69)
>         at jgi.ReformatReads.process(ReformatReads.java:481)
>         at jgi.ReformatReads.main(ReformatReads.java:53)
> [Fri Jul 29 07:41:40 2022]
> Error in rule get_read_stats:
>     jobid: 0
>     output: S3735D7-S12/sequence_quality_control/read_stats/filtered.zip, S3735D7-S12/sequence_quality_control/read_stats/filtered_read_counts.tsv
>     log: S3735D7-S12/logs/QC/read_stats/filtered.log (check log file(s) for error message)
> 
> RuleException:
> CalledProcessError in line 159 of /data/users/ocetiner/miniconda/envs/atlasenv2/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk:
> Command 'set -euo pipefail;
>         mkdir -p S3735D7-S12/sequence_quality_control/read_stats/filtered/se 2> S3735D7-S12/logs/QC/read_stats/filtered.log
> 
>         reformat.sh in=S3735D7-S12/sequence_quality_control/S3735D7-S12_filtered_se.fastq.gz         bhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/base_hist.txt         qhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/quality_by_pos.txt         lhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/readlength.txt         gchist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/gc_hist.txt         gcbins=auto         bqhist=S3735D7-S12/sequence_quality_control/read_stats/filtered/se/boxplot_quality.txt         threads=99         overwrite=true         -Xmx425G         2> >(tee -a S3735D7-S12/logs/QC/read_stats/filtered.log S3735D7-S12/sequence_quality_control/read_stats/filtered/se/read_stats.tmp )' returned non-zero exit status 1.
>   File "/data/users/ocetiner/miniconda/envs/atlasenv2/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk", line 215, in __rule_get_read_stats
>   File "/data/users/ocetiner/miniconda/envs/atlasenv2/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk", line 159, in get_read_stats
>   File "/data/users/ocetiner/miniconda/envs/atlasenv2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message

### **data/users/ocetiner/miniconda/envs/atlasenv2/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk**
[error.txt](https://github.com/metagenome-atlas/atlas/files/9216647/error.txt)

### **my config file**
[config.txt](https://github.com/metagenome-atlas/atlas/files/9216652/config.txt)

### **S3735D7-S12/logs/QC/read_stats/filtered.log**
[log.txt](https://github.com/metagenome-atlas/atlas/files/9216687/log.txt)

**Comment by SilasK** [comment]
I think 99 threads is clearly too much. You reduced it to 18 threads, isn't it?
Also the memory (for the normal and simple jobs) can be lower.  

error 2: What is in the `logs/QC/report.log`

**Comment by omrctnr** [comment]
I never set the threads to 99. The first time, I had replaced it with 18 and again I set it to 15, and it worked.

`logs/QC/report.log` is empty. Although I have not changed anything it works interestingly. But I am fearful that it will get error end of the pipeline again. Because I have 434 samples.

**Comment by SilasK** [comment]
Ok, strange
- [ ] I need to check why 99 is passed to the readstats. 

I know that the part of the readstats is not 100% optimal. Also a job can fail due to whatever reason. 


 You managed to pass the qc (report) for all samples ?

Than you can savely proceed with assembly. There you might get other problems bit not the same.

**Comment by omrctnr** [comment]
Actually, when I get the read_stats error, I advance the same command. Finally, All read_stats were finished but the build_qc_report gives the error above.

I proceed to assembly and encountered the same problem. 

> Error in rule build_qc_report:
>     jobid: 13031
>     output: reports/QC_report.html
>     log: logs/QC/report.log (check log file(s) for error message)
>     conda-env: /data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596
> 
> RuleException:
> CalledProcessError in line 798 of /data/users/ocetiner/miniconda/envs/atlasenv3/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk:
> Command 'source /data/users/ocetiner/miniconda/envs/atlasenv3/bin/activate '/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596'; set -euo pipefail;  python /data/users/ocetiner/atlas/.snakemake/scripts/tmp6uoh_v0p.qc_report.py' returned non-zero exit status 1.
>   File "/data/users/ocetiner/miniconda/envs/atlasenv3/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk", line 798, in __rule_build_qc_report
>   File "/data/users/ocetiner/miniconda/envs/atlasenv3/lib/python3.8/concurrent/futures/thread.py", line 57, in run


**Now, `logs/QC/report.log` was created**.

> 2022-07-31 09:29:49 Uncaught exception: Traceback (most recent call last):
>   File "/data/users/ocetiner/atlas/.snakemake/scripts/tmp8j02h4u8.qc_report.py", line 272, in <module>
>     div = make_plots(
>   File "/data/users/ocetiner/atlas/.snakemake/scripts/tmp8j02h4u8.qc_report.py", line 167, in make_plots
>     Quality_QC_pe, Quality_QC_se = get_stats_from_zips(zipfiles_QC, samples)
>   File "/data/users/ocetiner/atlas/.snakemake/scripts/tmp8j02h4u8.qc_report.py", line 79, in get_stats_from_zips
>     (quality_pe, df[["mean_1", "mean_2"]]), axis=1
>   File "/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596/lib/python3.9/site-packages/pandas/core/frame.py", line 3030, in __getitem__
>     indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
>   File "/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596/lib/python3.9/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
>     indexer, keyarr = ax._convert_listlike_indexer(key)
>   File "/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2568, in _convert_listlike_indexer
>     raise KeyError(f"{keyarr[mask]} not in index")
> KeyError: "['mean_2'] not in index"

**Comment by jmtsuji** [comment]
@SilasK @omrctnr  I'm not sure if this helps, but a while ago (e.g., using ATLAS 2.8.2), I also noticed non-optimal behaviour of some rules in the QC module. Unfortunately, I didn't note exactly what happened... but I think some of the rules were run out of order. (For example, the read stats rule tried to run on a file that didn't exist yet, or no longer existed.)

I overcame the problem by setting `simplejob_threads` to be the same as `threads` in the config file, and `threads` to be the same as --jobs in the CLI, when running the QC module. This prevents multiple rules from running at the same time in the QC module. Then, everything executed in the proper order.

Sorry that I don't have more clear notes/logs on this. However, I wonder if the issue I observed could be related to the issue described by @omrctnr. If it really is an execution order issue, then it makes sense that deleting the directory and running again with fewer threads (like what @omrctnr did) should more-or-less solve the issue.

**Comment by SilasK** [comment]
@omrctnr please, could you write here again your most recent error. It's difficult to  read error logs from mail.

Yes the readstats sometimes raisses errors but usually re-runing should pass all samples. 
If one sample is really messed up, you can simply delete the corresponding folder and restart from the raw reads. But you don't want to do it for all samples. 

You also got an error in the qc report, isn't it?

**Comment by omrctnr** [comment]
Hello @SilasK and @jmtsuji,

Firstly, I had the pipeline run with the same number of `simple job threads`, `threads `, and `--jobs`

My pipeline had been interrupted many times due to _get_reads_stats_ (more than 10 times). As @silas mentioned, I deleted the folders that belong to troubler samples. Finally, I reached the error of the build_qc_report step:

```

Activating conda environment: database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596
Activating conda environment: database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596
[Sat Aug  6 11:36:53 2022]
Error in rule build_qc_report:
    jobid: 5650
    output: reports/QC_report.html
    log: logs/QC/report.log (check log file(s) for error message)
    conda-env: /data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596

RuleException:
CalledProcessError in line 798 of /data/users/ocetiner/miniconda/envs/atlasenv3/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk:
Command 'source /data/users/ocetiner/miniconda/envs/atlasenv3/bin/activate '/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596'; set -euo pipefail;  python /data/users/ocetiner/atlas/.snakemake/scripts/tmppuyu4afc.qc_report.py' returned non-zero exit status 1.
  File "/data/users/ocetiner/miniconda/envs/atlasenv3/lib/python3.8/site-packages/atlas/workflow/rules/qc.smk", line 798, in __rule_build_qc_report
  File "/data/users/ocetiner/miniconda/envs/atlasenv3/lib/python3.8/concurrent/futures/thread.py", line 57, in run


```
 
**Here is _logs/QC/report.log_**

```
2022-08-06 11:36:52 Uncaught exception: Traceback (most recent call last):
  File "/data/users/ocetiner/atlas/.snakemake/scripts/tmppuyu4afc.qc_report.py", line 272, in <module>
    div = make_plots(
  File "/data/users/ocetiner/atlas/.snakemake/scripts/tmppuyu4afc.qc_report.py", line 167, in make_plots
    Quality_QC_pe, Quality_QC_se = get_stats_from_zips(zipfiles_QC, samples)
  File "/data/users/ocetiner/atlas/.snakemake/scripts/tmppuyu4afc.qc_report.py", line 79, in get_stats_from_zips
    (quality_pe, df[["mean_1", "mean_2"]]), axis=1
  File "/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596/lib/python3.9/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596/lib/python3.9/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/data/users/ocetiner/atlas/database/conda_envs/ad204e84c0b2a5cc6244dc834cb7b596/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2568, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")
KeyError: "['mean_2'] not in index"

```

The last problem was with my QC step.

**Comment by SilasK** [comment]
Hmm, You got single-end reads to start, isn't it? Atlas should handle them without a problem. But it seems that there is an error in the qc report rule. I will try to fix it. But in the meantime, you can continue running atlas. `atlas run assembly --keep-going` 

Not also to select `megahit` as an assembler in the config file. (spades cannot handle sonly single-end reads. 


Any idea why the read stats what executed with 99 threads?  this might be the cause why it was failing.

**Comment by omrctnr** [comment]
Hello again,

I'm sorry for the late reply because I had to consult my professor about the quality of the samples.

My samples are paired-end. And actually, I have never set the threads to 99. But I remember once I set it to 32 and the pipeline supposed 99 threads. Consequently, I always used the pipeline with 16 threads. 

I think the problem originated from the quality of fastq files. I realized that much later, some of them have a very low number of reads. When I ignored some samples which have fewer read count smaller than 100.000, the QC report was created. 

For now, the pipeline is running well.  

I apologiaze for the verboseness, I mean,  many comments and files. 

Thank you for your patience.

**Comment by SilasK** [comment]
Thank you for your feedback. I should find a way to improve this. As the qc report should precisely allow you to see that some samples are of bad quality.

If you check the file stats/read_stats.tsv you got 0 or very view reads for those samples that you removed. Isn't it?

**Comment by omrctnr** [comment]
**> I should find a way to improve this. As the qc report should precisely allow you to see that some samples are of bad quality.**

Before analyzing the samples, some samples which have a number of reads smaller than a specific threshold can be ignored by the ATLAS. Maybe, It should say: Hey, these samples have very low reads, I will ignore it.


**> If you check the file stats/read_stats.tsv you got 0 or very view reads for those samples that you removed. Isn't it?**

Yes, just as you said. 

Thank you for your great effort, help, and patience. 
@SilasK @jmtsuji
