### ISSUE TITLE
Incomplete documentation missing human genome link

### ISSUE THREAD

**Issue by bnm1317** [metagenome-atlas/atlas#542]
At this page https://metagenome-atlas.readthedocs.io/en/latest/advanced/qc.html 

At the bottom of the document 

```
For human reads we recommend to download the genome [here](), where contaminants and low complexity regions were masked.
```
I was hoping to find the human genome suggested in this documentation. Thank you very much!!

**Comment by SilasK** [comment]
here we go: https://drive.google.com/file/d/0B3llHR93L14wd0pSSnFULUlhcUk/edit?resourcekey=0-PsIKmg2q4EvTGWGOUjsKGQ

**Comment by bnm1317** [comment]
Thank you!
