### ISSUE TITLE
Mamba installation Problem

### ISSUE THREAD

**Issue by ChristophKnapp** [metagenome-atlas/atlas#544]
Hi,
I'm just getting started with metagenome-atlas. When I try to install, it tells me that my version of biopython is not correct. 

Problem: package metagenome-atlas-2.9.0-pyhdfd78af_0 requires biopython 1.74.*, but none of the providers can be installed

I'm at an debian machine where the current version of biopython is 1.79. I would rather avoid downgrading it. Is there any way I can solve this?

Thanks a lot 

Christoph

**Comment by jmtsuji** [comment]
Hi @ChristophKnapp , I think that the biopython requirement has been dropped in the latest version of ATLAS, v2.11.0. You could try installing that version.

**Comment by ChristophKnapp** [comment]
Thanks @jmtsuji for the fast reply. I'm afraid the situation is unchanged.

Problem: package metagenome-atlas-2.11.0-pyhdfd78af_0 requires biopython 1.74.*, but none of the providers can be installed

Regards 

Christoph

**Comment by SilasK** [comment]
I made a fix, but it din't passed in the bioconda repository: https://github.com/bioconda/bioconda-recipes/pull/36226
Once this is passed, you should be able to install atlas v 2.11 without the biopython

What you can do now is **creating a new environment** with atlas installed.
or install atlas from github see the instructions in the docs.

**Comment by ChristophKnapp** [comment]
Thank you @SilasK.

**Comment by ChristophKnapp** [comment]
Thank you @SilasK, the Mamba installation worked.
