### ISSUE TITLE
Can this atlas analyze human metagenome? 

### ISSUE THREAD

**Issue by luozhy88** [metagenome-atlas/atlas#548]
Can this atlas analyze human metagenome?  Can the metagenome of human feces be analyzed by atlas?

**Comment by luozhy88** [comment]
If I want to add a command about in the config "hsa: /data2/zhiyu/database/sunbeam/host_hsa/Homo_sapiens.GRCh38.dna.primary_assembly.fa", right? 

![image](https://user-images.githubusercontent.com/94740863/190318816-a083f095-2c56-49fd-96c6-175cebbe90d1.png)

**Comment by SilasK** [comment]
Yes.

**Comment by luozhy88** [comment]
Because I changed the samples.tsv file, and save as samles_new.tsv .  how can I specify its absolute path?
atlas run qc --samples  /home/zhiyu/atlas/samles_new.tsv   ,right?

**Comment by luozhy88** [comment]
Help!
