### ISSUE TITLE
Can this function be realized for atlas?

### ISSUE THREAD

**Issue by luozhy88** [metagenome-atlas/atlas#559]
Hi,Can this function be realized by atlas?
Coassembly mode: Reads from all samples are pooled and a single assembly is performed. Then reads from individual samples are mapped to the coassembly to obtain gene abundances in each sample. Binning methods allow to obtain genome bins.

**Comment by SilasK** [comment]
For no no. I have started to implement it. But do you really need it. Co-assembly needs a lot of resources and creates more chimeras. What would you need it for?

**Comment by luozhy88** [comment]
Yes, my server has a lot of computing resources, and I am more concerned about getting a better result. If you can do this, it will be great.

**Comment by luozhy88** [comment]
I expect better mainly  assembly .
