### ISSUE TITLE
Error_gtdb, dram_download

### ISSUE THREAD

**Issue by bioforkgithub** [metagenome-atlas/atlas#562]
Error in rule download_gtdb:
    jobid: 124
    output: /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/GTDB_V07/gtdb_data.tar.gz
    log: logs/download/gtdbtk.log (check log file(s) for error message)
    conda-env: /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/conda_envs/67a5e045324006e028514025d0499295
    shell:
         wget https://data.gtdb.ecogenomic.org/releases/release207/207.0/auxillary_files/gtdbtk_r207_v2_data.tar.gz -O /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/GTDB_V07/gtdb_data.tar.gz &> logs/download/gtdbtk.log 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Thu Sep 29 10:32:10 2022]
Error in rule dram_download:
    jobid: 132
    output: /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/Dram, /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/DRAM.config
    log: logs/dram/download_dram.log (check log file(s) for error message)
    conda-env: /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/conda_envs/a096d17ba31a674b938191e2dc36569b
    shell:
         DRAM-setup.py prepare_databases  --output_dir /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/Dram  --threads 8  --verbose  --skip_uniref  &> logs/dram/download_dram.log  ;  DRAM-setup.py export_config --output_file /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/DRAM.config
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

MissingOutputException in line 112 of /home/a40540/anaconda3/envs/atlas/lib/python3.10/site-packages/atlas/workflow/rules/download.smk:
Job Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/EggNOG_V5/eggnog.db
/gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/EggNOG_V5/eggnog_proteins.dmnd completed successfully, but some output files are missing. 158
Removing output files of failed job download_gtdb since they might be corrupted:
/gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/GTDB_V07/gtdb_data.tar.gz
Removing output files of failed job dram_download since they might be corrupted:
/gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/Dram
[Thu Sep 29 10:36:44 2022]
Finished job 99.
117 of 155 steps (75%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: .snakemake/log/2022-09-29T101901.311599.snakemake.log
[Atlas] CRITICAL: Command 'snakemake --snakefile /home/a40540/anaconda3/envs/atlas/lib/python3.10/site-packages/atlas/workflow/Snakefile --directory /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv --jobs 72 --rerun-incomplete --configfile '/gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/config.yaml' --nolock   --use-conda --conda-prefix /gpfs/gpfs0/home/home2/a40540/manish/sequences/atlasenv/database/conda_envs    --resources mem=478 mem_mb=489932 java_mem=406   --scheduler greedy  all   ' returned non-zero exit status 1.

Hi, I am a new to this. This is the elaborate error. Please can you help me in the right direction to solve this error.

**Comment by Justan6** [comment]
I encountered the same error:






Error in rule dram_download:
    jobid: 226
    output: /home/nwezejus/Peat_metagenome2022/ATLAS/databases/Dram, /home/nwezejus/Peat_metagenome2022/ATLAS/databases/DRAM.config
    log: logs/dram/download_dram.log (check log file(s) for error message)
    conda-env: /home/nwezejus/Peat_metagenome2022/ATLAS/databases/conda_envs/140c117b8fe5c17c29da39e6b9fb5794
    shell:
         DRAM-setup.py prepare_databases  --output_dir /home/nwezejus/Peat_metagenome2022/ATLAS/databases/Dram  --threads 8  --verbose  --skip_uniref  &> logs/dram/download_dram.log  ;  DRAM-setup.py export_config --output_file /home/nwezejus/Peat_metagenome2022/ATLAS/databases/DRAM.config
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by gaworj** [comment]
Hi,

I have encountered exactly the same problem:

[Thu Oct  6 22:41:38 2022]
Error in rule dram_download:
    jobid: 179
    output: /home/data_HDD1/atlas_db/Dram, /home/data_HDD1/atlas_db/DRAM.config
    log: logs/dram/download_dram.log (check log file(s) for error message)
    conda-env: /home/data_HDD1/atlas_db/conda_envs/7a95a3064288ffca677eb9d24ff451cc
    shell:
         DRAM-setup.py prepare_databases  --output_dir /home/data_HDD1/atlas_db/Dram  --threads 40  --verbose  --skip_uniref  &> logs/dram/download_dram.log  ;  DRAM-setup.py export_config --output_file /home/data_HDD1/atlas_db/DRAM.config
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
The code used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-code-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-code-changes)'.
The input used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-input-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-input-changes)'.
The params used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-params-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-params-changes)'.
Complete log: .snakemake/log/2022-10-06T134747.740246.snakemake.log
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
[Atlas] CRITICAL: Command 'snakemake --snakefile /home/oligo/anaconda3/envs/atlas-env/lib/python3.8/site-packages/atlas/workflow/Snakefile --directory /home/data_HDD2/illumina_data/OCZ_metagenome_atlas --jobs 40 --rerun-incomplete --configfile '/home/data_HDD2/illumina_data/OCZ_metagenome_atlas/config.yaml' --nolock   --use-conda --conda-prefix /home/data_HDD1/atlas_db/conda_envs    --resources mem=478 mem_mb=490080 java_mem=406   --scheduler greedy  all   ' returned non-zero exit status 1.

Any hints?

Bests,
Jan

**Comment by SilasK** [comment]
Can you check rhe log file:

Can you try with the newest version of atlas 2.12?

**Comment by gaworj** [comment]
Problem solved by:

conda activtate /home/data_HDD1/atlas_db/conda_envs/7a95a3064288ffca677eb9d24ff451cc

pip3 uninstall scipy

pip3 install scipy==1.8.1

After completion of my recent worflow I will update atlas to the newest version.

**Comment by bioforkgithub** [comment]
Thanku. Please can you inform when updated.
Kind regards
