### ISSUE TITLE
Error in rule

### ISSUE THREAD

**Issue by luozhy88** [metagenome-atlas/atlas#563]
What does this mean about "QC_se.fastq.gz"?

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/94740863/193830608-61a2a453-52cf-4a63-999b-f1b2efb3ec8b.png">

**Comment by SilasK** [comment]
Do wonder what they are? Some paire-end reads loose their mate during quality filtering. They end up in the singletons. se.

They are usually only a view. They are integrated where useful.
