### ISSUE TITLE
Dependency conflict while installing ATLAS 2.12.0

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#567]
@SilasK Thanks for the recent release of ATLAS 2.12.0!

Unfortunately, I am not able to install this ATLAS version on my server (running Ubuntu 20.04 LTS) due to what seems to be a dependency conflict.

Command run:
```bash
mamba create -n atlas_2.12.0 -c bioconda -c conda-forge metagenome-atlas=2.12.0
```

Error:
```
- package metagenome-atlas-2.12.0-pyhdfd78af_0 requires pyarrow 8.*, but none of the providers can be installed
```

I receive the same error when trying to install ATLAS 2.11.0 and 2.11.1.

However, I am able to install ATLAS 2.12.0 directly via Github without issue:
```bash
git clone https://github.com/metagenome-atlas/atlas
cd atlas
git checkout v2.12.0
mamba env create -n atlas_2.12.0-dev --file atlasenv.yml
conda activate atlas_2.12.0-dev
pip install --editable .
```

When installed via Github, pyarrow 9.0.0 is used.

On the bioconda site, it looks like pyarrow is locked to version 8 for the bioconda install of ATLAS ([link here](https://bioconda.github.io/recipes/metagenome-atlas/README.html)). I wonder if this could be changed to version >8? The pyarrow version is not specified in `atlasenv.yaml`.

Thanks for your help.

**Comment by SilasK** [comment]
Thank you for checking. I created a PR (see above). You don't want to become part of the bioconda Github team?

**Comment by jmtsuji** [comment]
@SilasK Thanks for looking into this issue so quickly. I didn't know that this system existed to make PRs for bioconda installs! It could be handy for me to contribute directly to bioconda in the future: https://bioconda.github.io/contributor/index.html -- thanks

**Comment by SilasK** [comment]
Yes, Bioconda is a really cool system. It'easy to create a new recepie. And there are even automatic updates for each new release.

**Comment by jmtsuji** [comment]
Very good to know -- thanks!
