### ISSUE TITLE
I installed the latest version of atlas and found this error when I run "atlas run qc"

### ISSUE THREAD

**Issue by botellaflotante** [metagenome-atlas/atlas#574]
[Atlas] INFO: Atlas version: 2.9.1
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Provided resources: mem=300
Singularity containers: ignored
Traceback (most recent call last):
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/workflow.py", line 1092, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/dag.py", line 2248, in stats
    yield tabulate(rows, headers="keys")
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/rules.py", line 1215, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
[Atlas] CRITICAL: Command 'snakemake --snakefile /home/jose/miniconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/Snakefile --directory /linuxhome/tmp/jose/endophytes --jobs 20 --rerun-incomplete --configfile '/linuxhome/tmp/jose/endophytes/config.yaml' --nolock   --use-conda --conda-prefix /linuxhome/tmp/jose/endophytes/databases/conda_envs    --resources mem=478 mem_mb=489818 java_mem=406   --scheduler greedy  qc  --resources mem=300 ' returned non-zero exit status 1.

Any clue?

**Comment by SilasK** [comment]
No clue. Can you check the snakemake version. You cal also try to update snakemake to the latest version.

**Comment by SilasK** [comment]
```
mamba install snakemake=7.18.1
```

If you don't have mamaba installed:
```
conda install mamba
```

**Comment by SilasK** [comment]
ah and what is your python version? 
The update to python 3.11 could create such bugs.

**Comment by botellaflotante** [comment]
thanks, python is 3.8.13.
when I try installing snakemake I get

"
Looking for: ['snakemake=7.18.1']

ursky/linux-64                                                No change
ursky/noarch                                                  No change
r/linux-64                                                    No change
pkgs/r/noarch                                                 No change
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                   817.7kB @   1.5MB/s  0.2s
r/noarch                                                      No change
bioconda/linux-64                                    4.4MB @   3.0MB/s  1.6s
pkgs/main/linux-64                                   4.9MB @   2.6MB/s  1.2s
conda-forge/noarch                                 @   3.5MB/s  2.9s
conda-forge/linux-64                               @   4.5MB/s  6.7s
bioconda/noarch                                      3.8MB @ 289.5kB/s 13.3s

Pinned packages:
  - python 3.8.*


Encountered problems while solving:
  - package snakemake-7.18.1-hdfd78af_0 requires snakemake-minimal
7.18.1.*, but none of the providers can be installed"

best

**Comment by AroArz** [comment]
Your issue is related to https://github.com/snakemake/snakemake/issues/1899.

Solutions include upgrading to the latest snakemake version or running

`mamba install 'tabulate=0.8.10'`

**Comment by SilasK** [comment]
Should I adapt the conda package, to fix this?

**Comment by SilasK** [comment]
Thank you very much
