### ISSUE TITLE
List all installed tools and their licenses

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [metagenome-atlas/atlas#575]
Is there a way to list all used tools and maybe also their licenses? Your tools is very nice but I could not find a dependency file nor I was able to list the tools in conda.

**Comment by SilasK** [comment]
I don't know that there is a easy way, unfortunately. I asked others on [Twitter](https://twitter.com/SilasKieser/status/1588097775568183296).

This is the place with all the conda files with the main dependencies. https://github.com/metagenome-atlas/atlas/tree/master/atlas/workflow/envs However each of these tools depends on other software. 

I would love ther to be an easy way to list all the software and their version and license. 

I expect to be all tools to be usabely in academia and industry except eggNOG mapper.
