### ISSUE TITLE
Error in rule semibin_predict_taxonomy: file exists, GTDB

### ISSUE THREAD

**Issue by philippbayer** [metagenome-atlas/atlas#588]
- [X] I checked and didn't found a related issue,e.g. while typing the title
- [X] ** I got an error in the following rule(s):** `semibin_predict_taxonomy`
- [X] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

```

Error executing rule semibin_predict_taxonomy on cluster (jobid: 1365, external: 444478, jobscript: /scratch/pawsey0390/pbayer/seagrass_atlas/.snakemake/tmp.sy2nr1au/snakejob.semibin_predict_taxonomy.1365.sh). For error details see the cluster log and the log files of the involved rule(s).
[Sat Nov 26 18:36:20 2022]
Error in rule semibin_predict_taxonomy:
    jobid: 1140
    output: Cobinning/SemiBin/ARZ3/cannot/cannot_bin.txt, Cobinning/SemiBin/ARZ3/mmseqs_contig_annotation/taxonomyResult.tsv
    log: logs/semibin/predict_taxonomy/ARZ3.log (check log file(s) for error message)
    conda-env: /scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_
    shell:
         export TMPDIR=/tmp &> logs/semibin/predict_taxonomy/ARZ3.log ;SemiBin predict_taxonomy  --input-fasta Cobinning/filtered_contigs/ARZ3.fasta  --threads 20  --output Cobinning/SemiBin/ARZ3  --cannot-name cannot_bin  --reference-db /scratch/pawsey0390/pbayer/seagrass_atlas/databases/SemiBin_GTDB/GTDB  &>> logs/semibin/predict_taxonomy/ARZ3.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 444479
```

Here is the relevant log output:

```
2022-11-26 04:36:18,210 - Downloading GTDB to /scratch/pawsey0390/pbayer/seagrass_atlas/databases/SemiBin_GTDB/GTDB.  It will take a while..
Traceback (most recent call last):
  File "/scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_/lib/python3.9/site-packages/SemiBin/main.py", line 845, in main
    predict_taxonomy(
  File "/scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_/lib/python3.9/site-packages/SemiBin/main.py", line 345, in predict_taxonomy
    GTDB_reference = find_or_download_gtdb(logger, GTDB_reference, False)
  File "/scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_/lib/python3.9/site-packages/SemiBin/gtdb.py", line 94, in find_or_download_gtdb
    download_GTDB_to(logger, GTDB_reference_dir)
  File "/scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_/lib/python3.9/site-packages/SemiBin/gtdb.py", line 17, in download_GTDB_to
    os.makedirs(GTDB_dir, exist_ok=True)
  File "/scratch/pawsey0390/pbayer/seagrass_atlas/databases/conda_envs/00e4749f0d179d3cf309c23156f6cab7_/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/scratch/pawsey0390/pbayer/seagrass_atlas/databases/SemiBin_GTDB/GTDB'
```

**atlas, version 2.13.0 Snakemake 7.15.2**

**Additional context**

*all* SemiBin jobs crash for all samples, I've tried to delete the GTDB folder and let the job re-download it, but each job tries to re-download the folder, the first job re-creates the GTDB folder and then they all crash.

Relevant part from the config file:

```
final_binner: SemiBin             # [SemiBin, DASTool, vamb, maxbin]

binner:                           # If DASTool is used as final_binner, use predictions of this binners
- metabat
- maxbin
#  - vamb
```

Would it make sense to let SemiBin v1.3 use the self-training mode instead? The makers have made some good experiences with self-training vs. using GTDB:

*Since version 1.3, SemiBin supports completely self-supervised learning, which bypasses the need to annotate contigs with MMSeqs2. In benchmarks, self-supervised learning is both faster (4x faster; using only 11% of RAM at peak) and generates 8.3-21.5% more high-quality bins compared to the version tested in the [manuscript](https://www.nature.com/articles/s41467-022-29843-y) To use it, pass the option --training-mode=self to the single_easy_bin or multi_easy_bin subcommands.*

from https://github.com/BigDataBiology/SemiBin

Thread from Luis Pedro Coelho explaining the changes a bit more: https://twitter.com/luispedrocoelho/status/1588060949222596613

**Comment by philippbayer** [comment]
OK I think I've at least found a workaround -

the GTDB database of SemiBin gets extracted into databases/SemiBin_GTDB/

In there are the following files:
GTDB  GTDB.dbtype  GTDB.index  GTDB.lookup  GTDB.source  GTDB.version  GTDB_h  GTDB_h.dbtype  GTDB_h.index  GTDB_mapping  GTDB_taxonomy

I've added a small logger.info to conda_envs/00e4749f0d179d3cf309c23156f6cab7_/lib/python3.9/site-packages/SemiBin/gtdb.py

in line 82: logger.info(f'Checking {GTDB_reference} in {GTDB_reference_dir}, {path.exists(GTDB_reference)}')

which prints:

     Checking /scratch/pawsey0390/pbayer/seagrass_atlas/databases/SemiBin_GTDB/GTDB/GTDB in /scratch/pawsey0390/pbayer/seagrass_atlas/databases/SemiBin_GTDB/GTDB, False

So it somehow assumes that there's a folder named GTDB within my SemiBin_GTDB folder

What I then did is change `--reference-db {input.db}/GTDB` to `--reference-db {input.db}` in the semibin.smk file. And it hasn't crashed yet?

**Comment by philippbayer** [comment]
OK my change finished fine. To get the rule semibin_train to run, I also had to comment out the line listing the input-bams or it would complain about not knowing --input_bam:
```
        "SemiBin train "
        " --input-fasta {input.fasta} "
       *#" --input-bam {input.bams} "
        " --output {params.output_dir} "
        " --threads {threads} "
        " --data {input.data} "
        " --data-split {input.data_split} "
        " --cannot-link {input.cannot_link} "
        " --mode single "
        " {params.extra} "
        " 2> {log}"
```

**Comment by SilasK** [comment]
I know Semibin got a new update, I haven't looked into it. 

The simple solution would be to limit the semibin version in the env/semibin.yaml file to <=1.0 or to <1.0 and then the existing code should work. 

The better option would be to update to the new api, which doesn't require the taxonomic annotation of genes. 
Do you want to do look into this?

**Comment by philippbayer** [comment]
Oh interesting sugestion! I'm not the most experienced Snakemake user (I've only ever written like two smaller scripts) but this would be a nice chance to give it a try. I'll have a look asap!

**Comment by philippbayer** [comment]
OK I've updated the fork in my repo, updated semibin.yml to 1.3 and replaced most of the semibin rule by single_easy_bin and training-mode=self. I'm testing whether the speed changes are OK with a single WGS library, or whether single_easy_bin needs to be split back up into the three commands. Will let you know later this week

**Comment by philippbayer** [comment]
OK that seems to work now.  I've run into this issue while benchmarking, so other fixes might come: https://github.com/BigDataBiology/SemiBin/issues/121

I took one sample from a recent run with ATLAS v2.13.0 + SemiBin v0.5. 

The output of the 'old' benchmark for semibin/train:

|s                |hours:minutes:seconds|max_rss                                                            |max_vms|max_uss|max_pss|io_in |io_out|mean_load|cpu_time|
|-----------------|-----|-------------------------------------------------------------------|-------|-------|-------|------|------|---------|--------|
|4246.2376        |1:10:46|1657.34                                                            |4792.95|1651.03|1651.46|497.45|0.09  |906.11   |37477.90|

The output of the SemiBin v1.3 benchmark:

|s                |h:m:s|max_rss                                                            |max_vms|max_uss|max_pss|io_in |io_out|mean_load|cpu_time|
|-----------------|-----|-------------------------------------------------------------------|-------|-------|-------|------|------|---------|--------|
|3972.1639        |1:06:12|2861.91                                                            |8327.03|2857.93|2858.25|236.23|0.08  |1963.73  |78005.33|

Interestingly this took a bit longer? BUT we can skip the whole GTDB download and mmseqs clustering, not sure how long that takes.

With v0.5 SemiBin I get 76 bins, with v1.3 SemiBin I get 70 bins for this sample (genomes/all_bins/genome_stats.tsv). CheckM is currently running for the v1.3 SemiBin bins, I'm wondering whether the resulting bins have higher scores. 

Are you happy with that? I can send a PR if you're happy
