### ISSUE TITLE
Error in rule root_tree and rule DRAM_set_db_loc

### ISSUE THREAD

**Issue by HamzaMbareche** [metagenome-atlas/atlas#592]
Hi Silas, 

I checked and didn't found a related issue.

- I got an error in the following rule(s):** `   `

_Error in rule root_tree:
    jobid: 10504
    output: genomes/tree/gtdbtk.ar122.nwk
    log: logs/genomes/tree/root_tree_gtdbtk.ar122.log (check log file(s) for error message)
    conda-env: /scratch/c/croitoru/mbareche/MAGs_discovery_fullset_1/databases/conda_envs/0814b8ba2802ed87e71f5d9a7bf6dc2d

RuleException:
CalledProcessError in line 125 of /usr/local/lib/python3.8/site-packages/atlas/workflow/rules/gtdbtk.smk:
Command 'source /usr/local/bin/activate '/scratch/c/croitoru/mbareche/MAGs_discovery_fullset_1/databases/conda_envs/0814b8ba2802ed87e71f5d9a7bf6dc2d'; set -euo pipefail;  python /scratch/c/croitoru/mbareche/MAGs_discovery_fullset_1/.snakemake/scripts/tmpxjr_btdy.root_tree.py' returned non-zero exit status 1.
  File "/usr/local/lib/python3.8/site-packages/atlas/workflow/rules/gtdbtk.smk", line 125, in __rule_root_tree_

- I checked the log files indicated indicated in the error message and the cluster logs, but the log files are empty. I am suspecting a memory issue. I am using a cluster with 1 node, 40 cores, and around 200 GB memory. Is there a way to workaround this?

I tried continuing the pipeline and skip this step by adding the --keep-going option.

I am getting an error in rule DRAM_set_db_loc, I am guessing because the cluster node don't have access to internet to import the dram-config. When I ran the command on the login node with internet access, the job starts with rule classify, which is taking a long time for the login node.

Is there a way to specify to atlas running the job DRAM_set_db_loc and downloading the Dram db, so that I can run them on the login node. Then continue with the rest of the pipeline on the cluster node without internet access. 

** Atlas 2.9.1**

I am using the atlas docker. 

Thanks to anyone willing to help with this. 

Best,
Hamza

**Comment by SilasK** [comment]
I fixed multiple issues for dram in version 2.13 and the latest in root in v 2.13.1 just released.

**Comment by SilasK** [comment]
In theory you should be able to update the atlas inside the docker. 
Idealy to the dev version or you wait untill the latest fix are on bioconda.
