### ISSUE TITLE
Unable to install Atlas 2.9

### ISSUE THREAD

**Issue by rjain1990** [metagenome-atlas/atlas#597]
I am returning with below error about biopython.

(base) user@user:~$  mamba install -y -c bioconda -c conda-forge metagenome-atlas=2.9

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['metagenome-atlas=2.9']

pkgs/main/linux-64                                            No change
conda-forge/noarch                                            No change
pkgs/r/noarch                                                 No change
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                              No change
bioconda/noarch                                      4.1MB @   1.2MB/s  3.5s
bioconda/linux-64                                    4.5MB @ 822.6kB/s  5.6s
conda-forge/linux-64                                28.8MB @   3.0MB/s 10.4s

Pinned packages:
  - python 3.10.*

Could not solve for environment specs
Encountered problems while solving:
  - package metagenome-atlas-2.9.0-pyhdfd78af_0 requires biopython 1.74.*, but none of the providers can be installed

**Comment by SilasK** [comment]
Is there a reason you don't want to install the latest verion of atlas? v 2.13

**Comment by rjain1990** [comment]
No reason at all. Looks like I did not see the latest version of the altas and was trying to install the Atlas using the command given on the github page of atlas. https://github.com/metagenome-atlas/atlas.
mamba install -y -c bioconda -c conda-forge metagenome-atlas=2.9
I thought 2.9 was the latest version but I was wrong as 2.13 is the latest one. 

Below is the command for installing latest version.
conda install -c bioconda -c conda-forge metagenome-atlas

Now I have both version in my system. How do I make version 2.13 to use as default?

**Comment by SilasK** [comment]
Sorry, I made a dynamic link to the latest version. 

Have you seen that I have more extended documentation on how to install and use atlas ? https://metagenome-atlas.readthedocs.io/

Check with `atlas --version` which version you have finally installed.
