### ISSUE TITLE
Run aborted with error

### ISSUE THREAD

**Issue by rjain1990** [metagenome-atlas/atlas#601]
Hi I am retuning the following error while running atlas 2.13.1. Can someone please help me to resolve it?
....
Activating conda environment: databases/conda_envs/8e65287ce14d3f5d1da7ddd9b7f83257_
[Tue Jan 10 15:27:39 2023]
Error in rule download_gtdb:
    jobid: 305
    output: /zfs/omics/personal/rjain/PB_CS/databases/GTDB_V07/gtdb_data.tar.gz
    log: logs/download/gtdbtk.log (check log file(s) for error message)
    conda-env: /zfs/omics/personal/rjain/PB_CS/databases/conda_envs/70cc3f3f2902d60658f00b3af68ba9ab_
    shell:
         wget https://data.gtdb.ecogenomic.org/releases/release207/207.0/auxillary_files/gtdbtk_r207_v2_data.tar.gz -O /zfs/omics/personal/rjain/PB_CS/databases/GTDB_V07/gtdb_data.tar.gz &> logs/download/gtdbtk.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job download_gtdb since they might be corrupted:
/zfs/omics/personal/rjain/PB_CS/databases/GTDB_V07/gtdb_data.tar.gz
[Tue Jan 10 15:29:25 2023]
Finished job 22.
1 of 336 steps (0.3%) done
[Tue Jan 10 15:29:46 2023]
Finished job 70.
2 of 336 steps (1%) done
[Tue Jan 10 15:29:50 2023]
Finished job 7.
3 of 336 steps (1%) done
[Tue Jan 10 15:30:02 2023]
Finished job 46.
4 of 336 steps (1%) done
[Tue Jan 10 15:30:07 2023]
Finished job 58.
5 of 336 steps (1%) done
[Tue Jan 10 15:30:07 2023]
Finished job 34.
6 of 336 steps (2%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: .snakemake/log/2023-01-10T152734.904951.snakemake.log
[Atlas] CRITICAL: Command 'snakemake --snakefile /home/rjain/miniconda3/lib/python3.9/site-packages/atlas/workflow/Snakefile --directory /zfs/omics/personal/rjain/PB_CS  --rerun-triggers mtime --jobs 64 --rerun-incomplete --configfile '/zfs/omics/personal/rjain/PB_CS/config.yaml' --nolock   --use-conda --conda-prefix /zfs/omics/personal/rjain/PB_CS/databases/conda_envs    --resources mem=478 mem_mb=490128 java_mem=406   --scheduler greedy  all   ' returned non-zero exit status 1.
(base) bash-4.2$ Activating conda environment: databases/conda_envs/8e65287ce14d3f5d1da7ddd9b7f83257_
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by SilasK** [comment]
what's in logs/download/gtdbtk.log

**Comment by SilasK** [comment]
The only thing to do is to rename your downloaded file:

`mv databases/GTDB_V07/gtdbtk_r207_v2_data.tar.gz databases/GTDB_V07/gtdb_data.tar.gz`


then rerun atlas. check first with the `--dry-run` option if the rule is skiped.
