### ISSUE TITLE
Atlas 2.13 installation problem

### ISSUE THREAD

**Issue by gaworj** [metagenome-atlas/atlas#605]
Hello,

Thank you for great pipeline.

I have previously succesfully used v.2.9.1

Today wanted to install newest atlas and encountered such error:

mamba create -n atlas-2-13 -y -c bioconda -c conda-forge metagenome-atlas=2.13

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['metagenome-atlas=2.13']

pkgs/main/linux-64                                            No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
bioconda/linux-64                                    4.5MB @   3.8MB/s  1.4s
bioconda/noarch                                      4.1MB @   2.4MB/s  1.9s
conda-forge/noarch                                  10.9MB @   3.4MB/s  3.5s
conda-forge/linux-64                                29.1MB @   3.8MB/s  8.7s
Encountered problems while solving:
  - package metagenome-atlas-2.13.0-pyhdfd78af_0 requires pyarrow >=8, but none of the providers can be installed

The same problem appears when I try to install metagenome-atlas without suffix "==2.13".

Any hints?

Bests,
Jan

**Comment by SilasK** [comment]
I don't see why it doesn't work.

Try to install metagenome atlas in a fres conda environment (see docs).

You have a linux, do you?
Any success with installing pyarrow directly ?

**Comment by SilasK** [comment]
does it work now?
