### ISSUE TITLE
Error in rule run_spades

### ISSUE THREAD

**Issue by trickovicmatija** [metagenome-atlas/atlas#614]
- [X] I checked and didn't found a related issue,e.g. while typing the title
- [x] ** I got an error in the following rule(s):** `  run_spades `

- [X] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output:

```
rule run_spades:
    input: FW7-30/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, FW7-30/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, FW7-30/assembly/reads/QC.errorcorr.merged_me.fastq.gz
    output: FW7-30/assembly/contigs.fasta, FW7-30/assembly/scaffolds.fasta
    log: FW7-30/logs/assembly/spades.log
    jobid: 0
    benchmark: logs/benchmarks/assembly/spades/FW7-30.txt
    reason: Missing output files: logs/benchmarks/assembly/spades/FW7-30.txt, FW7-30/assembly/scaffolds.fasta, FW7-30/assembly/contigs.fasta
    wildcards: sample=FW7-30
    threads: 8
    resources: mem_mb=250000, disk_mb=1000, tmpdir=/tmp, mem=250, time=48, time_min=2880

Activating conda environment: ../../../../../shares/Trajkovski_Group/atlas_database/8fa643b9fffeef55f1b1293122d6a0fb_
Waiting at most 5 seconds for missing files.
MissingOutputException in rule run_spades  in line 424 of /srv/beegfs/scratch/users/t/trickovi/atlas-dev/atlas/atlas/workflow/rules/assemble.smk:
Job Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
FW7-30/assembly/contigs.fasta
FW7-30/assembly/scaffolds.fasta completed successfully, but some output files are missing. 0
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message


```

** Atlas version**
atlas, version 2.14.2+0.g1dc9419.dirty Snakemake 7.18.2
**Additional context**

Since I my dataset is metatranscriptome, I have set the spades "spades_preset" parameter to "rna". The rule executes successfully, but the expected output is missing. Is it possible that the output names are different when using "rna" setting than with the default?

Thanks,
Matija

**Comment by SilasK** [comment]
Did the metagenome run smoothly? 
There is a hack for metatranscriptome https://github.com/metagenome-atlas/atlas/discussions/604#discussioncomment-4718134

But I should find a better way.

**Comment by trickovicmatija** [comment]
Thanks for your reply!
Metagenome samples run fine (for another dataset).
I will assemble metagenome samples from the same dataset where are metatranscriptomes and map to assembled genomes.

Thanks!
