### ISSUE TITLE
Overview of the files in the genomes/counts folder.

### ISSUE THREAD

**Issue by LeeBergstrand** [metagenome-atlas/atlas#617]
I am trying to determine each dereplicated MAG's abundance in each sample.

The counts folder within genomes contains four files:
- counts_genomes.parquet
- binned_coverage.parquet
- coverage_contigs.parquet
- median_coverage_genomes.parquet

Can you provide an overview of what each file contains and how each is generated?

For example, the counts_genomes.parquet file appears to contain the number of reads mapping from each metagenome to each MAG. Is this correct?

**Comment by SilasK** [comment]
So we map the reads to the combined set of contigs of the representative MAGs. 

- counts_genomes.parquet contains the raw counts per genome
- coverage_contigs.parquet contains the coverage for all contigs of the representative MAGs
- binned_coverage.parquet contains the coverage binned in 1kb? bins of the contigs
- median_coverage_genomes.parquet is the median coverage per genome based on the binned coverage.

I suggest to use the median coverage for relative abundance calculation.
And the counts if you want /need counts.
