### ISSUE TITLE
Error in rule metabat

### ISSUE THREAD

**Issue by kmkappa** [metagenome-atlas/atlas#618]
- [ +] I checked and didn't found a related issue,e.g. while typing the title
- [ +] ** I got an error in the following rule(s):** ` metabat  `
```
Error in rule metabat:
    jobid: 83
    input: MIC-002B/binning/metabat/metabat_depth.txt, MIC-002B/MIC-002B_contigs.fasta
    output: MIC-002B/binning/metabat/cluster_attribution.tmp
    log: MIC-002B/logs/binning/metabat.txt (check log file(s) for error message)
    conda-env: /home/gs66/Atlas_run/databases/conda_envs/4a4c88f6ec23c668cfa84097f4958cd2_
    shell:
        
        metabat2 -i MIC-002B/MIC-002B_contigs.fasta             --abdFile MIC-002B/binning/metabat/metabat_depth.txt             --minContig 1500             --numThreads 8             --maxEdges 500             --saveCls --noBinOut             -o MIC-002B/binning/metabat/cluster_attribution.tmp             &> MIC-002B/logs/binning/metabat.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

- [ +] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output of logs/binning/metabat.txt :

```
MetaBAT 2 (2.15 (Bioconda)) using minContig 1500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, maxEdges 500 and minClsSize 200000. with random seed=1678561455
[Error!] There are no lines in the abundance depth file or fasta file!
```

** Atlas version 2.14.3 ; Snakemake version 7.18.2**

**Additional context**
![metabat error](https://user-images.githubusercontent.com/25985792/224535394-e336d36d-ee36-4b47-9617-7ffbd1d134b4.png)

**Comment by SilasK** [comment]
Can you check the input files mentioned to see in which there is a problem?

**Comment by kmkappa** [comment]
_metabat.txt_ has only a header:
![image](https://user-images.githubusercontent.com/25985792/224709939-6bbb57ce-fc59-46f9-93c3-7ddbd8735676.png)

and  *_contigs.fasta_ file is an empty file (0 bytes)

**Comment by SilasK** [comment]
Something screwed the assembly? Why are there no contigs? 

Maybe the assembly dind't worked at all or there might that all contigs were filtered out in the post-assembly step.

1. try to figure out what happened. Look in the log files in `MIC-002B/logs` for the assembly and post-assembly step.
2. Recreate the assemblies.
Delete the empty contigs. Delete corrupted or all files in `MIC-002B/assembly`
If you delete a file atlas should execute all steps to re-create it. 
Then run first `atlas run assembly` and look at the contig stats and assembly report. Maybe other samples have the same problem.

**Comment by kmkappa** [comment]
Dear Silas,

Many thanks for getting back to me !

As you suggested, I tried to re-assembly the reads and the pipeline crashes with error in rule predicted_genes :
![Screenshot from 2023-03-14 08-31-26](https://user-images.githubusercontent.com/25985792/224962386-e8d94e9c-58d8-488b-a6bc-73a5427d2982.png)

In fact already *_prefilter_contigs.fasta is an empty file. Do you have any suggestion what could be the reason ? and any eventual solution ? I appreciate any hint!

**Comment by SilasK** [comment]
So something went wrong during the assembly?

I assume you used the default spades assembler. 

Is there somthing in 
`{sample}/logs/assembly/spades.log`

or in the spades logfile that is in "{sample}/assembly/*.log

**Comment by kmkappa** [comment]
Correct, I used spades.
In  {sample}/logs/assembly/spades.log file all seems correct (steps K21, K33 and K55 look fine) but there are few final warnings:
![image](https://user-images.githubusercontent.com/25985792/225001103-26c50ee3-2bc1-44df-b9ad-f7cb06eff167.png)

**Comment by SilasK** [comment]
Strange that no reads aligned. 
Does the spades log say something about how many contigs it produced?

Check the reports/QC reports or reports/readcounts for that sample. maybe it only contains very view reads. 

Have you seen the problem also for other samples?

**Comment by kmkappa** [comment]
indeed, very strange because there are a lot of reads (241863 passing qc) and 90% of them is > 250 bp long.
please see attached spades.log file for more details. [spades.log](https://github.com/metagenome-atlas/atlas/files/11002924/spades.log)
when I try other samples from the same cohort - the result is the same. 
could the problem be related to technical parameters of pc ?

**Comment by SilasK** [comment]
I don't know why exactly but your assembly doesn't seems right. 

Do you have some unusual or very small data? 

I read:
```
Average coverage = 2714.88
Total length = 10'816
Median edge length: 56
Edges: 1044
Vertices: 706
```

The values for an infant metagenome is 
50 average coverage and 54'764'972 total length 


This seems like a very small but highly covered metagenome. Maybe none of the final contigs is longer than the min length?
Could it be a transcriptome?

Also, the assembly took less than 20 min, which is very fast.

Maybe it's worth contacting the spades developers. 

Other comments:
- Memory limit 29GB, is very low but it seemed not to be a problem 
- With 250bp reads you can increase the kmers

**Comment by kmkappa** [comment]
Thank you @SilasK.
According to your suggestion I have contacted spades developers (please see issue https://github.com/ablab/spades/issues/1110). it doesn't seem there is any constructive solution so I'll rather try some other tools instead of spades.

**Comment by SilasK** [comment]
I don't this it's a problem with spades. rather with your data? You could try PLASS?
