### ISSUE TITLE
Error in rule run_gunc

### ISSUE THREAD

**Issue by mladen5000** [metagenome-atlas/atlas#626]
run_gunc exits due to the lack of a series.iteritems method. I will edit the gunc.yaml file to limit pandas to 1.5.1 and see if this fixes it, since this is now deprecated in pandas 2.0.

**Comment by SilasK** [comment]
Thank you for reporting. This should solve the problem. PR is welcome.

**Comment by mladen5000** [comment]
Will do

**Comment by SilasK** [comment]
Fixed in #629
