### ISSUE TITLE
median_coverage.h5  ERROR

### ISSUE THREAD

**Issue by luozhy88** [metagenome-atlas/atlas#640]
Thank you very much for developing such a useful tool. I have a problem that needs help.The median_coverage.h5 is no rowname(gene name)

filename = "counts/median_coverage.h5"
data <- h5read(filename, "data")
attributes= h5readAttributes(filename, "data")
colnames(data) <- attributes$sample_names
<img width="717" alt="image" src="https://user-images.githubusercontent.com/94740863/235944250-af54c66f-e3ee-42c2-9079-7c466b7183b7.png">

**Comment by SilasK** [comment]
The attributes of hdf5 doesn't allow to store colnames of very large size. 

The idea is that the Genename 'Gene0001' is converted to 1, etc. 
This allows to have a pure matrix of numbers.
 

What I suggest is to parse your gene annotations e.g. eggnog and transform the 'Gene0001' is converted to 1.
I don't know on top of my head how to do this in R but  I can try to find a way. 

Note: on the master branch I have the option to annotate genecatalog with kegg via dram .

**Comment by SilasK** [comment]
Just to be shure the code snipped you send worked, isn't it?

**Comment by luozhy88** [comment]
Thank you for your advice. It worked.

**Comment by SilasK** [comment]
@luozhy88  You might want to look at the updated docs on how to read and normalize only a subset of genes. 
[56154b1](https://github.com/metagenome-atlas/atlas/commit/56154b1f7c81060f583920f7ee2f550641d9e0e3)
