### ISSUE TITLE
cluster deployment

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#65]
@camel315 have you already heard of the snakemake [cluster configuration](http://snakemake.readthedocs.io/en/stable/executable.html#cluster-execution)? 

It is the ideal way to let atlas control the submission to the cluster system.
I implemented a cluster script for a slurm system, but they should be easily adaptable for an LSF system. Do you want it to try?

**Comment by camel315** [comment]
@SilasK I am just new in this field and don't know snakemake cluster configuration. Could you please give me the cluster script so that I can try? In addition, could you please have a look at my latest comment in rule initialize_checkm failed #58? Thank you.

**Comment by brwnj** [comment]
Posting for future reference in case someone else has a question on using `--cluster`:

For SLURM, here's an example of what this looks like...

```
atlas assemble --jobs 10000 \
    --out-dir results/bsel \
    /pic/projects/bsel/bsel_config.yaml \
    --conda-prefix /pic/projects/bsel/atlas-conda-env \
    --cluster-config /pic/projects/bsel/cluster.yaml \
    --cluster '"sbatch --account {cluster.account} --partition {cluster.partition} --exclusive --nodes {cluster.nodes} --time {cluster.time} --job-name {cluster.name} --output {cluster.output} --error {cluster.error}"'
```

In this case, the SLURM err and out files are written to results/bsel.

The file /pic/projects/bsel/cluster.yaml looks like:

```
__default__:
    account: mint
    time: 1440
    partition: shared
    nodes: 1
    # ntasks: 24
    name: "atlas.{rule}.{wildcards}"
    output: "{rule}.{wildcards}.out"
    error: "{rule}.{wildcards}.err"
```

The err and out files will be named like:

```
run_prokka_annotation.sample=BSEL-pool4.err
run_prokka_annotation.sample=BSEL-pool4.out
sort_munged_blast_hits.sample=BSEL-pool1.err
sort_munged_blast_hits.sample=BSEL-pool1.out
```

**Comment by SilasK** [comment]
I had an Idea how to improve the cluster submission using scheduler scripts. Now the clean up is merged I try to implement this.

**Comment by brwnj** [comment]
Sorry about that! Looking forward to seeing the changes!
