### ISSUE TITLE
Error in rule download_gtdb

### ISSUE THREAD

**Issue by mladen5000** [metagenome-atlas/atlas#673]
- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x ] ** I got an error in the following rule(s):** `download_gtdb   `

- [ x] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output:

```
--2023-06-28 20:09:31--  https://data.gtdb.ecogenomic.org/releases/release214/214.0/auxillary_files/gtdbtk_r214_data.tar.gz
Resolving data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)... 203.101.230.53
Connecting to data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)|203.101.230.53|:443... connected.
ERROR: cannot verify data.gtdb.ecogenomic.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to data.gtdb.ecogenomic.org insecurely, use `--no-check-certificate'.



```

** Atlas version**
2.17
**Additional context**
Adding --no-check-certificate resolves the issue.

**Comment by SilasK** [comment]
Fixed by your PR #674
