### ISSUE TITLE
Error in rule rename_genomes

### ISSUE THREAD

**Issue by XC-Zhai** [metagenome-atlas/atlas#685]
- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x] ** I got an error in the following rule(s):** `   `

Hi thanks for this  good tool, I tried it but encountered the following error: 

Config file /home/projects/atlas/atlas/workflow/../config/default_config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=150000, mem_mib=150000, time_min=300
Singularity containers: ignored
Select jobs to execute...
Changing to shadow directory: /home/projects/cow_test/.snakemake/shadow/tmpcqbbx8qm
Not cleaning up /home/projects/cow_test/.snakemake/shadow/tmpcqbbx8qm/.snakemake/scripts/tmp9hz_kvbf.rename_genomes.py
[Tue Jul 25 14:55:41 2023]
Error in rule rename_genomes:
    jobid: 0
    input: Binning/DASTool/raw_bins/paths.tsv, Binning/DASTool/bins2species.tsv, Binning/DASTool/filtered_bin_info.tsv
    output: genomes/genomes, genomes/clustering/contig2genome.tsv, genomes/clustering/old2newID.tsv, genomes/clustering/allbins2genome.tsv, genomes/genome_quality.tsv
    log: logs/genomes/rename_genomes.log (check log file(s) for error details)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
[Tue Jul 25 14:55:42 2023]
Finished job 124.
111 of 137 steps (81%) done

- [x] I checked the log files indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output:

```
2023-07-25 14:55:41 Uncaught exception: Traceback (most recent call last):

Here is the log from rule of rename_genomes
  File "/home/projects/cow_test/.snakemake/shadow/tmpcqbbx8qm/.snakemake/scripts/tmp9hz_kvbf.rename_genomes.py", line 55, in <module>
    representatives = mapping.Representative.unique()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'unique'



```

** Atlas version**
2.17.2

Thanks a lot for helping me figure out the problem.

Best regards,
Xichuan

**Comment by SilasK** [comment]
I could improve this. 
But it seems you only have one species in your sample after quality filtering.

Could you please check the tables Binning/DASTool/bins2species.tsv, Binning/DASTool/filtered_bin_info.tsv
the column Representative.

I can fix the bug. but what do you intend to do with only one genome as representative?

**Comment by XC-Zhai** [comment]
> I could improve this. But it seems you only have one species in your sample after quality filtering.
> 
> Could you please check the tables Binning/DASTool/bins2species.tsv, Binning/DASTool/filtered_bin_info.tsv the column Representative.
> 
> I can fix the bug. but what do you intend to do with only one genome as representative?

Yes, you are true, only one bin remains there. I may not use a small demon dataset to run a test.

**Comment by SilasK** [comment]
Ok thenk it makes sense. 
I provide a small test dataset in the docs with 2-3 genomes. 
 I keep the issue as ref to fix this small bug. if there is only one species.

**Comment by SilasK** [comment]
can you tell me what's in /home/projects/atlas_db1/DRAM/DRAM.config

**Comment by XC-Zhai** [comment]
> can you tell me what's in /home/projects/atlas_db1/DRAM/DRAM.config

I have attached it below. DRAM database was sent (previous we have a problem downloading database) from the other server and then the path from DRAM.config was changed accordingly. 
[DRAM.config.txt](https://github.com/metagenome-atlas/atlas/files/12162975/DRAM.config.txt)

**Comment by SilasK** [comment]
It seems you modified the first key which should stay "search_databases":

```

{
  "search_databases": {
    "kegg": null,
    "kofam_hmm": "/...b/kofam_profiles.hmm",
```

**Comment by SilasK** [comment]
Strike 2 errors in less than 2 h

**Comment by XC-Zhai** [comment]
> Strike 2 errors in less than 2 h

Much appreciated for your patience and time.  ATLAS was finished perfect.

**Comment by SilasK** [comment]
You are welcome.
