### ISSUE TITLE
Updating the documentation

### ISSUE THREAD

**Issue by brwnj** [metagenome-atlas/atlas#69]
# Default protocol:
Initial QC
Deduplication (optional)
Quality trimming
Decontamination

*Reads stats after each of those steps

[There are some insert size calculation steps here, but the output is currently not used downstream]

Normalize coverage
Error correction (optional)
Merge read pairs (optional)
Assemble (and stats)
Filter contigs

On the filtered contigs we:

Prokka with annotation
Diamond blastp against RefSeq for taxonomy

Bin genomes
QC bins with CheckM

Align QC'd sequences to final contigs
Feature counts using ORFs from Prodigal

**Comment by SilasK** [comment]
### TODO
- [ ] Good documentation
- [ ] Example/ tutorial
- [ ] Test 
-  [ ] FAQ
- [ ]  requirements for bug request.

**Comment by SilasK** [comment]
@brwnj For the documentation, As now we have the explanation for the easy parameters in the comments of the config file. I would suggest that we put a great part of the exiting documentation below the heading: "advanced parameters"

some other pages with 
Explanation of the pipline, e.g. the image.
documentation of the output.

What do you think?
