### ISSUE TITLE
atlas init-public no such command

### ISSUE THREAD

**Issue by claireewilliams** [metagenome-atlas/atlas#704]
Hi Silas,
I was wondering if atlas init-public is still implemented in version 2.18.1. When we run the command 

`atlas init-public --working-dir HMP2 PRJNA398089`

we get the error "no such command" 

Just wondering if this command is still implemented in the workflow as we will be working with a lot of public data.
Thanks! 
Claire

**Comment by SilasK** [comment]
The short answer is no, It werked perfectly until there was a service on NCBI that was discontinued. I try to add an [alternative](https://github.com/metagenome-atlas/kingfisher_workflow).

Maybe I will have something next week.
