### ISSUE TITLE
Error in rule

### ISSUE THREAD

**Issue by yustinus1** [metagenome-atlas/atlas#707]
Hi Silas
 I'm Yustinus. I tried using atlas_metagenome but I got an error like the following:

Error in rule predict_genes:
    jobid: 681
    input: Assembly/fasta/S028.fasta
    output: S028/annotation/predicted_genes/S028.fna, S028/annotation/predicted_genes/S028.faa, S028/annotation/predicted_genes/S028.gff
    log: S028/logs/gene_annotation/prodigal.txt (check log file(s) for error details)
    conda-env: /home/pipetin/databases/conda_envs/d4ac37792f743396b4b89995f71f7e75_
    shell:
        
        prodigal -i Assembly/fasta/S028.fasta -o S028/annotation/predicted_genes/S028.gff -d S028/annotation/predicted_genes/S028.fna             -a S028/annotation/predicted_genes/S028.faa -p meta -f gff 2> S028/logs/gene_annotation/prodigal.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile S028/logs/gene_annotation/prodigal.txt:
===============================================
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Metagenomic, Phase:  Training
Initializing training files...done!
-------------------------------------
Request:  Metagenomic, Phase:  Gene Finding

Error:  no input sequences to analyze.

===============================================

How to resolve the error. Thank You

**Comment by SilasK** [comment]
The error message states that there are no   sequences in the assembly file. 
Check the input file. and then the assembly log.

**Comment by yustinus1** [comment]
Thank you for your response.

I have checked the assembly file and the data is empty. Please help with the solution?

the script I use is:
& atlas init --db-dir databases --working-dir WD1 /home/pipetin/Documents/Fastq_Metagenomics/optimization/
& atlas run qc --max-mem 0.95 (ATLAS finished)
then continue
& atlas run binning --max-mem 0.95
and error again. Assembly for fasta file is empty.

**Comment by yustinus1** [comment]
when running I got a warning:
[Sun Nov 12 20:24:38 2023]
rule calculate_contigs_stats:
     input: Assembly/fasta/S035.fasta
     output: S035/assembly/contig_stats/final_contig_stats.txt
     log: S035/logs/assembly/post_process/contig_stats_final.log
     jobid: 639
     reason: Missing output files: S035/assembly/contig_stats/final_contig_stats.txt; Input files updated by another job: Assembly/fasta/S035.fasta
     wildcards: sample=S035
     resources: tmpdir=/tmp, mem=1, time=1, mem_mb=1000, mem_mib=954, time_min=60, runtime=60

Is this a problem?

**Comment by SilasK** [comment]
check the `"{sample}/logs/assembly/spades.log"`

And also the reports/QC_report.html
