### ISSUE TITLE
plans for supporting fungi

### ISSUE THREAD

**Issue by jotech** [metagenome-atlas/atlas#719]
Is there a current plan to include other microorganisms like fungi?

It would most probably involve other tools and databases, but at least for the assembly, spades could work, too.

Is there a way to start from, e.g., avoid filtering before binning?

I found some references from older issues and milestones:
https://github.com/metagenome-atlas/atlas/issues/356
https://github.com/metagenome-atlas/atlas/milestone/4

**Comment by SilasK** [comment]
No plans. I would like to make a small rehaul of the pipeline first. Yes, I think assembly, and binning with vamb should you also give Fungi genomes. Should be unbiased. E.g. other binners use single-copy markers of bacteria. 

## What you can to today: 
You can check if there are big bins with very bad checkM quality scores, after atlas run binning. I could add Busco quality checking.

## Limitations
I am not sure how feasible it will be to get a MAG from fungi. Do you have data where this could be possible? 
I guess that getting quantification with reference genomes would be better. Wha do you think?

**Comment by jotech** [comment]
hi @SilasK, many thanks for your reply!

I checked the bigger bins with low-quality scores, and I found some fungi contigs, but the bins seem rather very much chimeric or contaminated (full of everything: fungi, bacteria, metazoa, phages)

In principle, it should be possible to find fungi using the dataset I have. It consists of compost samples, and I also have 16S and ITS data that indicate that many bacteria and fungi are present.

Getting quantification with reference genomes or markers might be an alternative I agree. I'm only wondering if some fungi genes or genomes could be recovered from the data

**Comment by SilasK** [comment]
On gene and even contig level. Analysis should be definitively working. But I fear MAG/Bin level not.

For example, the Atlas genecatalog should contain most of the fungi genes. The eggNOG annotation also specifies if a gene annotation is from mungi. Check this. 

Next step, that tI should implement is a larger taxonomic quantification of genes using mmseqs.

**Comment by jotech** [comment]
good idea; I will investigate the contig and gene level!

I have tried taxonomic profiling mmseqs2 so far and found fungi genes in the genecatalog fasta, which is good news.
