### ISSUE TITLE
Error in rule

### ISSUE THREAD

**Issue by bharat1912** [metagenome-atlas/atlas#733]
DRAM appears to be stuck at the database download stage: kofam_ko_list.tsv.gz (858.2 kb), kofam_profiles.tar.gz (1.5 GB), Pfam-A.full.gz (18.1). These files are not decompressing even after 6 hours 

atlas version: 2.18.2

**Comment by SilasK** [comment]
I don't really what to do. also the DRAM has stopt suporting DRAM v1. 

1. It make quite some time. Can you let it run over night. 
2. You can try to kill atlas and re-run the files to download...
3. You can try to download the files with DRAM and then pass the config file to atlas. 
4. You can deactivate the `kegg_modules`and `dram`from the section genome annotations in the atlas config file and run atlas without DRAm. 



For Nr 3. You can:
- activate the dram conda environment writen in the log of atlas/snakemake

- Download the DRAM databases
```
  DRAM-setup.py prepare_databases          --output_dir {output_dbdir}          --threads {threads}          --verbose  --skip_uniref 
 ```

- You can export the dram config file from the installed db. 
`DRAM-setup.py export_config --output_file {output_dram_configfile}`

- Set in the atlas config file the path to dram_config_file: output_dram_configfile

**Comment by bharat1912** [comment]
Thanks. 

I am using ubuntu 18.04 and had to use python 3.8, for some of my work, which I had installed in /local. I had an issue with python lib being called from /local rather from the atlas mamba installatiion. After deleting python from /local I am was able to get dram running. 

Apparently there is a "leak" when a mamba / conda environment is created and the python lib is pulled from /local.
