### ISSUE TITLE
problem with mamba 

### ISSUE THREAD

**Issue by ShevchenkoAlla** [metagenome-atlas/atlas#743]
Hello,
I have found the same mistakes, but none of the suggested solutions helped,
Please have anyone can help with this issue?

I have installed mamba - mamba 1.5.11
But It didn't changed anything

"""
[Atlas] ^[[32;21mINFO: Atlas version: 0+unknown^[[0m
Config file /fs/s_alla/s_alla/atlas/atlas/workflow/../config/default_config.yaml is extended by ad$
Building DAG of jobs...
Creating conda environment ../atlas/atlas/workflow/envs/spades.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /fs/s_alla/s_alla/atlas/atlas/workflow/rules/../envs/spade$
Command:
mamba env create --quiet --file "/fs/s_alla/s_alla/el/databases/conda_envs/9eaf9b2b1db3541ec65$
Output:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

[Atlas] ^[[31;21mCRITICAL: Command 'snakemake --snakefile /fs/s_alla/s_alla/atlas/atlas/workflow/S$
  """"

My slurm script looks this way - 

""""
#!/bin/bash
#SBATCH --job-name=atlas
#SBATCH --nodes=2
#SBATCH --ntasks=50
#SBATCH --mem=125000M
source /home/s_alla/fs/s_alla/anaconda3/etc/profile.d/conda.sh
conda activate atlas-dev
atlas run all --working-dir /home/s_alla/fs/s_alla/el/ --jobs 10
conda deactivate
 """

Thank you,
Best,
Alla

**Comment by ShevchenkoAlla** [comment]
Yes, it's the same issue.
Oops, it said I didn't have snakemake:)
Let me install it and try.

Thank you,
Best,
Alla

**Comment by ShevchenkoAlla** [comment]
Still the same issue 

 snakemake --version
8.25.5



[Atlas] ^[[32;21mINFO: Atlas version: 0+unknown^[[0m
Config file /beegfs/shevch_alla/shevch_alla/atlas/atlas/workflow/../config/defa$
Building DAG of jobs...
Creating conda environment ../atlas/atlas/workflow/envs/species_clustering.yaml$
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /beegfs/shevch_alla/shevch_alla/atlas/a$
Command:
mamba env create --quiet --file "/beegfs/shevch_alla/shevch_alla/elbrus/databas$
Output:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

[Atlas] ^[[31;21mCRITICAL: Command 'snakemake --snakefile /beegfs/shevch_alla/s$

**Comment by SilasK** [comment]
I got the same problem, with libmamba. I installed the libmamba=1.59 inside the atlas env

I hope to find a better fix in the future

**Comment by SilasK** [comment]
Continue discussion on #742
