### ISSUE TITLE
Wrong default shell when using docker

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#78]
**Problem description**

I am attempting to use ATLAS within a docker container (based off [continuumio/miniconda](https://hub.docker.com/r/continuumio/miniconda/)). Within the container, the `Snakefile` appears to run using `/bin/sh` instead of the typical default `/bin/bash`, which prevents the pipeline from recognizing where conda binaries are storied.

Both in the previous and current ATLAS releases, I get the following type of error (last line in the code block):

```
rule init_QC:
    input: /home/atlas/data/NE1_R1_sub100k.fastq, /home/atlas/data/NE1_R2_sub100k.fastq
    output: NE1-sub100k/sequence_quality_control/NE1-sub100k_raw_R1.fastq.gz, NE1-sub100k/sequence_quality_control/NE1-sub100k_raw_R2.fastq.gz
    log: NE1-sub100k/logs/NE1-sub100k_init.log
    jobid: 34
    wildcards: sample=NE1-sub100k
    priority: 80
    threads: 12
    resources: mem=32

reformat.sh in=/home/atlas/data/NE1_R1_sub100k.fastq in2=/home/atlas/data/NE1_R2_sub100k.fastq         interleaved=f         out1=NE1-sub100k/sequence_quality_control/NE1-sub100k_raw_R1.fastq.gz out2=NE1-sub100k/sequence_quality_control/NE1-sub100k_raw_R2.fastq.gz         qout=33         overwrite=true         verifypaired=t         addslash=t         trimreaddescription=t         threads=12         -Xmx32G 2> NE1-sub100k/logs/NE1-sub100k_init.log
        
/bin/sh: 1: source: not found
```

**Proposed solution**

Adding the following to the top of the `Snakefile` (as recommended [here](http://snakemake.readthedocs.io/en/stable/project_info/faq.html#i-want-to-configure-the-behavior-of-my-shell-for-all-rules-how-can-that-be-achieved-with-snakemake)) appears to solve the issue:

```
shell.executable("/bin/bash")
shell.prefix("source ~/.bashrc; ")
```

This sets the shell explicitly.

**Comment by SilasK** [comment]
Seems reasonable, 

But do we need the `shell.prefix("source ~/.bashrc; ")`, does this always working?

**Comment by SilasK** [comment]
@jmtsuji  Could you test if only putting 'shell.executable("/bin/bash")' is sufficient for you?

**Comment by jmtsuji** [comment]
Just tested on version 10.0.22. Indeed, including only `shell.executable("/bin/bash")` in the Snakefile appears to fix the issue. It looks like `shell.prefix("source ~/.bashrc; ")` is not needed.

**Comment by brwnj** [comment]
I propose we remove this strict setting and depend on the changes of Snakemake after 4.4.0. At the very least we need to use `/usr/bin/env bash`.

You can see how this is handled at:

https://bitbucket.org/snakemake/snakemake/src/580b2628514a976698c9c265eae752d354cb7372/snakemake/shell.py?at=master&fileviewer=file-view-default#shell.py-146
