### ISSUE TITLE
Be tidy with conda env

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#95]
As I'm using Atlas on different project, snakemake creates always new conda env in a folder outdir/.snakemake/... 
There is the option `--conda-prefix` to install all conda envs into this repertoire.

@brwnj Do you know a easy way to add `--conda-prefix=~/.atlas_conda_envs" to all atlas commands. I think it's better to append this command automatically to all comands instead of asking the user to do that.

**Comment by brwnj** [comment]
It's possible, but the intent was to always show that we're just executing a snakemake workflow as a subprocess. It's still important for the user to know aspects of snakemake.

If we were to implement this, I would probably just parse the configuration file prior to executing the workflow. If the user has specified to use conda, check the config for a new option, `conda_prefix`, and add that onto the snakemake command if it's in the config file and not already in `snakemake_args`.

Are other people having difficulties with this?
